package com.smartmerchant.saas.merchant.application;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.smartmerchant.saas.merchant.domain.*;
import com.smartmerchant.saas.merchant.infrastructure.*;
import com.smartmerchant.saas.security.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDateTime;
import java.util.*;
import static org.springframework.http.HttpStatus.*;

@Service
public class CatalogService {
    private final CategoryMapper categories;private final ProductSpuMapper spus;private final ProductSkuMapper skus;private final JdbcTemplate jdbc;private final StoreAccessGuard storeAccess;
    public CatalogService(CategoryMapper categories,ProductSpuMapper spus,ProductSkuMapper skus,JdbcTemplate jdbc,StoreAccessGuard storeAccess){this.categories=categories;this.spus=spus;this.skus=skus;this.jdbc=jdbc;this.storeAccess=storeAccess;}

    public List<Category> categories(){return categories.selectList(Wrappers.<Category>lambdaQuery().orderByAsc(Category::getSortOrder).orderByAsc(Category::getCategoryName));}
    public List<ProductView> products(Long storeId){
        if(storeId==null)requireTenantAll();else storeAccess.requireAccess(storeId);
        var allSpus=spus.selectList(Wrappers.<ProductSpu>lambdaQuery().orderByAsc(ProductSpu::getProductName));
        var allSkus=skus.selectList(Wrappers.<ProductSku>lambdaQuery().orderByAsc(ProductSku::getSkuName));
        var supplied=storeId==null?Set.<Long>of():new HashSet<>(jdbc.queryForList("SELECT sku_id FROM store_product WHERE tenant_id=? AND store_id=? UNION SELECT sku_id FROM inventory WHERE tenant_id=? AND store_id=?",Long.class,TenantContextHolder.requireTenantId(),storeId,TenantContextHolder.requireTenantId(),storeId));
        var grouped=new LinkedHashMap<Long,List<SkuView>>();for(var sku:allSkus)if(storeId==null||supplied.contains(sku.getId()))grouped.computeIfAbsent(sku.getSpuId(),ignored->new ArrayList<>()).add(skuView(sku,storeId));
        return allSpus.stream().filter(spu->storeId==null||grouped.containsKey(spu.getId())).map(spu->new ProductView(spu,grouped.getOrDefault(spu.getId(),List.of()))).toList();
    }
    @Transactional public ProductView createWithSku(long categoryId,String productCode,String productName,String skuCode,String skuName,String barcode,long priceCents){return createWithSku(categoryId,productCode,productName,skuCode,skuName,barcode,priceCents,null);}
    @Transactional public ProductView createWithSku(long categoryId,String productCode,String productName,String skuCode,String skuName,String barcode,long priceCents,String imageUrl){
        requireTenantAll();var product=createSpu(categoryId,productCode,productName,null,imageUrl);
        product=updateSpu(product.getId(),categoryId,productName,null,imageUrl,"ACTIVE",product.getVersion());
        var sku=createSku(product.getId(),skuCode,skuName,null,barcode,priceCents,false);
        sku=updateSku(sku.getId(),skuName,null,barcode,priceCents,false,"ACTIVE",sku.getVersion());
        return new ProductView(product,List.of(new SkuView(sku,null,null,priceCents)));
    }
    @Transactional public Category createCategory(Long parentId,String code,String name,int sortOrder){requireTenantAll();if(parentId!=null)requiredCategory(parentId);var c=TenantContextHolder.require();var now=LocalDateTime.now();var value=new Category();value.setId(Ids.next());value.setTenantId(c.tenantId());value.setParentId(parentId);value.setCategoryCode(code);value.setCategoryName(name);value.setSortOrder(sortOrder);value.setStatus("ACTIVE");value.setVersion(0);value.setCreatedBy(c.userId());value.setCreatedAt(now);value.setUpdatedAt(now);categories.insert(value);return value;}
    @Transactional public ProductSpu createSpu(long categoryId,String code,String name,String description,String imageUrl){requireTenantAll();requiredCategory(categoryId);var c=TenantContextHolder.require();var now=LocalDateTime.now();var value=new ProductSpu();value.setId(Ids.next());value.setTenantId(c.tenantId());value.setCategoryId(categoryId);value.setSpuCode(code);value.setProductName(name);value.setDescription(description);value.setImageUrl(imageUrl);value.setStatus("DRAFT");value.setVersion(0);value.setCreatedBy(c.userId());value.setCreatedAt(now);value.setUpdatedAt(now);spus.insert(value);return value;}
    @Transactional public ProductSku createSku(long spuId,String code,String name,String specJson,String barcode,long basePriceCents,boolean allowStorePrice){requireTenantAll();requiredSpu(spuId);var c=TenantContextHolder.require();var now=LocalDateTime.now();var value=new ProductSku();value.setId(Ids.next());value.setTenantId(c.tenantId());value.setSpuId(spuId);value.setSkuCode(code);value.setSkuName(name);value.setSpecJson(specJson);value.setBarcode(blankToNull(barcode));value.setBasePriceCents(basePriceCents);value.setAllowStorePrice(allowStorePrice);value.setStatus("DRAFT");value.setVersion(0);value.setCreatedBy(c.userId());value.setCreatedAt(now);value.setUpdatedAt(now);skus.insert(value);return value;}
    @Transactional public ProductSpu updateSpu(long id,long categoryId,String name,String description,String imageUrl,String status,int version){requireTenantAll();requiredSpu(id);requiredCategory(categoryId);int changed=spus.update(null,Wrappers.<ProductSpu>lambdaUpdate().eq(ProductSpu::getId,id).eq(ProductSpu::getVersion,version).set(ProductSpu::getCategoryId,categoryId).set(ProductSpu::getProductName,name).set(ProductSpu::getDescription,description).set(ProductSpu::getImageUrl,imageUrl).set(ProductSpu::getStatus,status).set(ProductSpu::getVersion,version+1).set(ProductSpu::getUpdatedAt,LocalDateTime.now()));if(changed!=1)conflict();return spus.selectById(id);}
    @Transactional public ProductSku updateSku(long id,String name,String specJson,String barcode,long basePriceCents,boolean allowStorePrice,String status,int version){requireTenantAll();requiredSku(id);int changed=skus.update(null,Wrappers.<ProductSku>lambdaUpdate().eq(ProductSku::getId,id).eq(ProductSku::getVersion,version).set(ProductSku::getSkuName,name).set(ProductSku::getSpecJson,specJson).set(ProductSku::getBarcode,blankToNull(barcode)).set(ProductSku::getBasePriceCents,basePriceCents).set(ProductSku::getAllowStorePrice,allowStorePrice).set(ProductSku::getStatus,status).set(ProductSku::getVersion,version+1).set(ProductSku::getUpdatedAt,LocalDateTime.now()));if(changed!=1)conflict();if(!allowStorePrice)jdbc.update("DELETE FROM store_price WHERE tenant_id=? AND sku_id=?",TenantContextHolder.requireTenantId(),id);return skus.selectById(id);}
    @Transactional public SkuView configureStore(long storeId,long skuId,boolean sellable,Long priceCents){storeAccess.requireAccess(storeId);var sku=requiredSku(skuId);var c=TenantContextHolder.require();var current=skuView(sku,storeId);if(!Objects.equals(current.sellable(),sellable)&&!c.permissions().contains("merchant:store-product:manage"))throw new ResponseStatusException(FORBIDDEN,"Store-product permission is required");if(!Objects.equals(current.storePriceCents(),priceCents)&&!c.permissions().contains("merchant:price:manage"))throw new ResponseStatusException(FORBIDDEN,"Store-price permission is required");if(sellable&&(!"ACTIVE".equals(sku.getStatus())||!"ACTIVE".equals(requiredSpu(sku.getSpuId()).getStatus())))throw new ResponseStatusException(BAD_REQUEST,"Only active SPU and SKU can be sold");if(priceCents!=null&&!Boolean.TRUE.equals(sku.getAllowStorePrice()))throw new ResponseStatusException(BAD_REQUEST,"This SKU does not allow a store price");int updated=jdbc.update("UPDATE store_product SET sellable=?,version=version+1,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND store_id=? AND sku_id=?",sellable,c.userId(),c.tenantId(),storeId,skuId);if(updated==0)jdbc.update("INSERT INTO store_product(tenant_id,store_id,sku_id,sellable,updated_by) VALUES (?,?,?,?,?)",c.tenantId(),storeId,skuId,sellable,c.userId());if(priceCents==null)jdbc.update("DELETE FROM store_price WHERE tenant_id=? AND store_id=? AND sku_id=?",c.tenantId(),storeId,skuId);else{updated=jdbc.update("UPDATE store_price SET price_cents=?,approved_by=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND store_id=? AND sku_id=?",priceCents,c.userId(),c.tenantId(),storeId,skuId);if(updated==0)jdbc.update("INSERT INTO store_price(tenant_id,store_id,sku_id,price_cents,approved_by) VALUES (?,?,?,?,?)",c.tenantId(),storeId,skuId,priceCents,c.userId());}return skuView(sku,storeId);}
    private SkuView skuView(ProductSku sku,Long storeId){if(storeId==null)return new SkuView(sku,null,null,sku.getBasePriceCents());var rows=jdbc.queryForList("SELECT sp.sellable,p.price_cents FROM store_product sp LEFT JOIN store_price p ON p.tenant_id=sp.tenant_id AND p.store_id=sp.store_id AND p.sku_id=sp.sku_id WHERE sp.tenant_id=? AND sp.store_id=? AND sp.sku_id=?",TenantContextHolder.requireTenantId(),storeId,sku.getId());if(rows.isEmpty())return new SkuView(sku,false,null,sku.getBasePriceCents());var row=rows.getFirst();var price=(Number)row.get("PRICE_CENTS");if(price==null)price=(Number)row.get("price_cents");Long override=price==null?null:price.longValue();Object rawSellable=row.containsKey("SELLABLE")?row.get("SELLABLE"):row.get("sellable");boolean sellable=rawSellable instanceof Boolean b?b:((Number)rawSellable).intValue()!=0;return new SkuView(sku,sellable,override,override==null?sku.getBasePriceCents():override);}
    private Category requiredCategory(long id){var value=categories.selectById(id);if(value==null)throw new ResponseStatusException(NOT_FOUND,"Category not found");return value;}
    private ProductSpu requiredSpu(long id){var value=spus.selectById(id);if(value==null)throw new ResponseStatusException(NOT_FOUND,"SPU not found");return value;}
    private ProductSku requiredSku(long id){var value=skus.selectById(id);if(value==null)throw new ResponseStatusException(NOT_FOUND,"SKU not found");return value;}
    private static String blankToNull(String value){return value==null||value.isBlank()?null:value;}
    private static void conflict(){throw new ResponseStatusException(CONFLICT,"Catalog record was changed by another request");}
    private static void requireTenantAll(){if(!"TENANT_ALL".equals(TenantContextHolder.require().dataScope()))throw new ResponseStatusException(FORBIDDEN,"TENANT_ALL data scope is required");}
    public record ProductView(ProductSpu spu,List<SkuView> skus){}
    public record SkuView(ProductSku sku,Boolean sellable,Long storePriceCents,Long effectivePriceCents){}
}
