package com.smartmerchant.saas.merchant.application;

import com.smartmerchant.saas.security.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
import static org.springframework.http.HttpStatus.*;

@Service
public class InventoryService {
 private final JdbcTemplate jdbc;private final StoreAccessGuard access;public InventoryService(JdbcTemplate jdbc,StoreAccessGuard access){this.jdbc=jdbc;this.access=access;}
 public List<Map<String,Object>> inventory(long storeId){access.requireAccess(storeId);return jdbc.queryForList("SELECT i.*,s.sku_code,s.sku_name,p.product_name FROM inventory i JOIN product_sku s ON s.tenant_id=i.tenant_id AND s.id=i.sku_id JOIN product_spu p ON p.tenant_id=s.tenant_id AND p.id=s.spu_id WHERE i.tenant_id=? AND i.store_id=? ORDER BY s.sku_code",tenant(),storeId);}
 public List<Map<String,Object>> ledger(long storeId,long skuId){access.requireAccess(storeId);return jdbc.queryForList("SELECT * FROM inventory_ledger WHERE tenant_id=? AND store_id=? AND sku_id=? ORDER BY created_at DESC,id DESC",tenant(),storeId,skuId);}
 public List<Map<String,Object>> storeLedger(long storeId){access.requireAccess(storeId);return jdbc.queryForList("SELECT l.*,s.sku_code,s.sku_name,p.product_name FROM inventory_ledger l JOIN product_sku s ON s.tenant_id=l.tenant_id AND s.id=l.sku_id JOIN product_spu p ON p.tenant_id=s.tenant_id AND p.id=s.spu_id WHERE l.tenant_id=? AND l.store_id=? ORDER BY l.created_at DESC,l.id DESC",tenant(),storeId);}
 public List<Map<String,Object>> counts(long storeId){access.requireAccess(storeId);return jdbc.queryForList("SELECT c.*, (SELECT COUNT(*) FROM stock_count_item i WHERE i.tenant_id=c.tenant_id AND i.count_id=c.id) item_count, (SELECT COALESCE(SUM(ABS(i.difference_quantity)),0) FROM stock_count_item i WHERE i.tenant_id=c.tenant_id AND i.count_id=c.id) difference_quantity, (SELECT COALESCE(SUM(CASE WHEN i.difference_quantity>0 THEN i.difference_quantity ELSE 0 END),0) FROM stock_count_item i WHERE i.tenant_id=c.tenant_id AND i.count_id=c.id) positive_difference_quantity FROM stock_count c WHERE c.tenant_id=? AND c.store_id=? ORDER BY c.created_at DESC,c.id DESC",tenant(),storeId);}
 @Transactional public Snapshot adjust(long storeId,long skuId,long delta,String key,String reason){if(delta>0)requireTenantAllocation();return mutate(storeId,skuId,delta,delta,0,"ADJUSTMENT","MANUAL",null,key,reason);}
 @Transactional public Snapshot reserve(long storeId,long skuId,long quantity,String key,Long businessId){positive(quantity);return mutate(storeId,skuId,0,-quantity,quantity,"RESERVE","ORDER",businessId,key,null);}
 @Transactional public Snapshot release(long storeId,long skuId,long quantity,String key,Long businessId){positive(quantity);return mutate(storeId,skuId,0,quantity,-quantity,"RELEASE","ORDER",businessId,key,null);}
 @Transactional public Snapshot deductReserved(long storeId,long skuId,long quantity,String key,Long businessId){positive(quantity);return mutate(storeId,skuId,-quantity,0,-quantity,"DEDUCT_RESERVED","ORDER",businessId,key,null);}
 @Transactional public Snapshot restore(long storeId,long skuId,long quantity,String key,Long businessId){positive(quantity);return mutate(storeId,skuId,quantity,quantity,0,"REFUND_RESTORE","REFUND",businessId,key,"退款回补");}
 @Transactional public Map<String,Object> createCount(long storeId,String countNo,String remark,List<CountLine> lines){access.requireAccess(storeId);if(lines.isEmpty())throw new ResponseStatusException(BAD_REQUEST,"Stock count requires items");var c=TenantContextHolder.require();long id=Ids.next();jdbc.update("INSERT INTO stock_count(id,tenant_id,store_id,count_no,status,remark,created_by) VALUES (?,?,?,?,?,?,?)",id,c.tenantId(),storeId,countNo,"DRAFT",remark,c.userId());for(var line:uniqueCountLines(lines)){ensureInventory(storeId,line.skuId());var before=snapshot(storeId,line.skuId());jdbc.update("INSERT INTO stock_count_item(tenant_id,count_id,sku_id,expected_quantity,counted_quantity,difference_quantity) VALUES (?,?,?,?,?,?)",c.tenantId(),id,line.skuId(),before.actualQuantity(),line.countedQuantity(),line.countedQuantity()-before.actualQuantity());}return count(id);}
 public Map<String,Object> count(long id){var header=one("SELECT * FROM stock_count WHERE tenant_id=? AND id=?",tenant(),id);access.requireAccess(number(header,"STORE_ID"));header.put("items",jdbc.queryForList("SELECT ci.*,s.sku_code,s.sku_name FROM stock_count_item ci JOIN product_sku s ON s.tenant_id=ci.tenant_id AND s.id=ci.sku_id WHERE ci.tenant_id=? AND ci.count_id=?",tenant(),id));return header;}
 @Transactional public Map<String,Object> completeCount(long id){var header=count(id);if(!"DRAFT".equals(value(header,"STATUS")))throw new ResponseStatusException(CONFLICT,"Only a draft count can be completed");long storeId=number(header,"STORE_ID");for(var row:(List<Map<String,Object>>)header.get("items")){long skuId=number(row,"SKU_ID"),diff=number(row,"DIFFERENCE_QUANTITY");if(diff>0)requireTenantAllocation();long actual=jdbc.queryForObject("SELECT actual_quantity FROM inventory WHERE tenant_id=? AND store_id=? AND sku_id=? FOR UPDATE",Long.class,tenant(),storeId,skuId);if(actual!=number(row,"EXPECTED_QUANTITY"))throw new ResponseStatusException(CONFLICT,"盘点期间库存已变化，请重新盘点并创建新单");if(diff!=0)mutate(storeId,skuId,diff,diff,0,"STOCK_COUNT","STOCK_COUNT",id,"COUNT:"+id+":"+skuId,"盘点差异");}var c=TenantContextHolder.require();int changed=jdbc.update("UPDATE stock_count SET status='COMPLETED',completed_by=?,completed_at=CURRENT_TIMESTAMP,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND status='DRAFT'",c.userId(),c.tenantId(),id);if(changed!=1)throw new ResponseStatusException(CONFLICT,"Stock count status changed");return count(id);}
 private Snapshot mutate(long storeId,long skuId,long actualDelta,long availableDelta,long reservedDelta,String operation,String businessType,Long businessId,String key,String reason){access.requireAccess(storeId);if(key==null||key.isBlank())throw new ResponseStatusException(BAD_REQUEST,"Idempotency key is required");var existing=jdbc.queryForList("SELECT quantity_after,available_after,reserved_after FROM inventory_ledger WHERE tenant_id=? AND idempotency_key=?",tenant(),key);if(!existing.isEmpty()){var r=existing.getFirst();return new Snapshot(read(r,"QUANTITY_AFTER"),read(r,"AVAILABLE_AFTER"),read(r,"RESERVED_AFTER"));}ensureInventory(storeId,skuId);int changed=jdbc.update("UPDATE inventory SET actual_quantity=actual_quantity+?,available_quantity=available_quantity+?,reserved_quantity=reserved_quantity+?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND store_id=? AND sku_id=? AND actual_quantity+?>=0 AND available_quantity+?>=0 AND reserved_quantity+?>=0 AND actual_quantity+?=available_quantity+?+reserved_quantity+?",actualDelta,availableDelta,reservedDelta,tenant(),storeId,skuId,actualDelta,availableDelta,reservedDelta,actualDelta,availableDelta,reservedDelta);if(changed!=1)throw new ResponseStatusException(CONFLICT,"Insufficient stock or concurrent inventory change");var after=snapshot(storeId,skuId);var c=TenantContextHolder.require();try{jdbc.update("INSERT INTO inventory_ledger(id,tenant_id,store_id,sku_id,operation_type,quantity_delta,available_delta,reserved_delta,quantity_after,available_after,reserved_after,business_type,business_id,idempotency_key,reason,operator_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",Ids.next(),c.tenantId(),storeId,skuId,operation,actualDelta,availableDelta,reservedDelta,after.actualQuantity(),after.availableQuantity(),after.reservedQuantity(),businessType,businessId,key,reason,c.userId());}catch(DuplicateKeyException e){throw new ResponseStatusException(CONFLICT,"Duplicate inventory operation",e);}return after;}
 Snapshot allocate(long storeId,long skuId,long quantity,long allocationId,String reason){requireTenantAllocation();positive(quantity);return mutate(storeId,skuId,quantity,quantity,0,"TENANT_ALLOCATION","ALLOCATION",allocationId,"ALLOCATION:"+allocationId+":"+storeId+":"+skuId,reason);}
 @Transactional public void threshold(long storeId,long skuId,long threshold){requireTenantAllocation();access.requireAccess(storeId);if(threshold<0)throw new ResponseStatusException(BAD_REQUEST,"预警线不能为负数");ensureInventory(storeId,skuId);jdbc.update("UPDATE inventory SET low_stock_threshold=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND store_id=? AND sku_id=?",threshold,tenant(),storeId,skuId);}
 private static void requireTenantAllocation(){var c=TenantContextHolder.require();if(c.platform()||!"TENANT_ALL".equals(c.dataScope()))throw new ResponseStatusException(FORBIDDEN,"门店入库数量由租户统一分配");}
 Snapshot undoOrderDeduction(long storeId,long skuId,long quantity,long orderId,long transferId){
  var rows=jdbc.queryForList("SELECT quantity_delta FROM inventory_ledger WHERE tenant_id=? AND store_id=? AND sku_id=? AND business_id=? AND operation_type='DEDUCT_RESERVED' AND idempotency_key=?",tenant(),storeId,skuId,orderId,"ORDER:DEDUCT:"+orderId+":"+skuId);
  if(rows.size()!=1||number(rows.getFirst(),"QUANTITY_DELTA")!=-quantity)throw new ResponseStatusException(CONFLICT,"原订单库存扣减记录不匹配，不能重复出库");
  return mutate(storeId,skuId,quantity,quantity,0,"ORDER_FULFILLMENT_UNDO","TRANSFER",transferId,"ORDER:DIRECT-UNDO:"+orderId+":"+skuId,"订单改由同租户门店直寄，撤回原销售库存扣减");
 }
 Snapshot transferOut(long storeId,long skuId,long quantity,long transferId){return mutate(storeId,skuId,-quantity,-quantity,0,"TRANSFER_OUT","TRANSFER",transferId,"TRANSFER:OUT:"+transferId+":"+skuId,null);}
 Snapshot transferIn(long storeId,long skuId,long quantity,long transferId){return mutate(storeId,skuId,quantity,quantity,0,"TRANSFER_IN","TRANSFER",transferId,"TRANSFER:IN:"+transferId+":"+skuId,null);}
 private void ensureInventory(long storeId,long skuId){if(jdbc.queryForObject("SELECT COUNT(*) FROM product_sku WHERE tenant_id=? AND id=?",Long.class,tenant(),skuId)!=1)throw new ResponseStatusException(NOT_FOUND,"SKU not found");if(jdbc.queryForObject("SELECT COUNT(*) FROM inventory WHERE tenant_id=? AND store_id=? AND sku_id=?",Long.class,tenant(),storeId,skuId)==0)jdbc.update("INSERT INTO inventory(id,tenant_id,store_id,sku_id) VALUES (?,?,?,?)",Ids.next(),tenant(),storeId,skuId);}
 private Snapshot snapshot(long store,long sku){var row=one("SELECT actual_quantity,available_quantity,reserved_quantity FROM inventory WHERE tenant_id=? AND store_id=? AND sku_id=?",tenant(),store,sku);return new Snapshot(number(row,"ACTUAL_QUANTITY"),number(row,"AVAILABLE_QUANTITY"),number(row,"RESERVED_QUANTITY"));}
 private static List<CountLine> uniqueCountLines(List<CountLine> lines){var ids=new HashSet<Long>();for(var l:lines){if(l.countedQuantity()<0||!ids.add(l.skuId()))throw new ResponseStatusException(BAD_REQUEST,"Invalid or duplicate stock-count item");}return lines;}
 private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);if(rows.isEmpty())throw new ResponseStatusException(NOT_FOUND,"Record not found");return new LinkedHashMap<>(rows.getFirst());}
 private static long number(Map<String,Object> row,String key){Object value=row.get(key);if(value==null)value=row.get(key.toLowerCase());return ((Number)value).longValue();}private static long read(Map<String,Object>r,String k){return number(r,k);}private static String value(Map<String,Object>r,String k){Object v=r.get(k);if(v==null)v=r.get(k.toLowerCase());return String.valueOf(v);}private static void positive(long q){if(q<=0)throw new ResponseStatusException(BAD_REQUEST,"Quantity must be positive");}private static long tenant(){return TenantContextHolder.requireTenantId();}
 public record Snapshot(long actualQuantity,long availableQuantity,long reservedQuantity){}public record CountLine(long skuId,long countedQuantity){}
}
