<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import Icon from './Icon.vue'
import DrinkArt from './DrinkArt.vue'
import { drinks, categories, stores, initialCoupons, read, write, price, type Drink, type CartLine, type DemoOrder, type Address, type Coupon } from './data'
import './prototype.css'

type Screen = 'home' | 'shop' | 'orders' | 'me' | 'stores' | 'checkout' | 'order-detail' | 'coupons' | 'points' | 'balance' | 'favorites' | 'addresses' | 'help' | 'settings' | 'member' | 'messages' | 'gift'
const screens: Screen[] = ['home','shop','orders','me','stores','checkout','order-detail','coupons','points','balance','favorites','addresses','help','settings','member','messages','gift']
const initialScreen = location.hash.slice(1) as Screen
const screen = ref<Screen>(screens.includes(initialScreen) ? initialScreen : 'home')
const sheet = ref(''), toast = ref(''), search = ref(''), category = ref('全部'), orderTab = ref('进行中'), couponTab = ref('可使用')
const storeId = ref(read('store', 'lakeside')), mode = ref<'pickup'|'delivery'>(read('mode', 'pickup'))
const cart = ref<CartLine[]>(read(`cart.${storeId.value}`, [])), favorites = ref<string[]>(read('favorites', [])), orders = ref<DemoOrder[]>(read('orders', []))
const coupons = ref<Coupon[]>(read('coupons', initialCoupons)), points = ref(read('points',128)), balance = ref(read('balance',58))
const member = ref(read('member',false)), nickname = ref(read('nickname','小叶')), notification = ref(read('notification',true))
const addresses = ref<Address[]>(read('addresses', [{ id:'home',name:'小叶',phone:'13800138000',address:'杭州市上城区湖滨路 28 号 1 幢 101 室',label:'家' }]))
const addressId = ref(read('addressId','home')), addressDraft = ref<Address>({id:'',name:'',phone:'',address:'',label:'家'})
const drink = ref<Drink | null>(null), size = ref('标准杯'), temp = ref('正常冰'), sugar = ref('推荐甜'), toppings = ref<string[]>([]), quantity = ref(1)
const selectedCoupon = ref(''), pickupTime = ref('尽快取餐'), note = ref(''), noteDraft = ref(''), payment = ref('wechat'), selectedOrderId = ref('')
const storeReturn = ref<Screen>('home'), couponReturn = ref<Screen>('me'), addressReturn = ref<Screen>('me'), pendingStore = ref(''), submitting = ref(false), helpOpen = ref(-1)
const giftAmount = ref(50), giftRecipient = ref(''), giftMessage = ref('愿你的每一天，都有一杯好心情。'), giftSent = ref(false)
const currentStore = computed(() => stores.find(s=>s.id===storeId.value) || stores[0])
const currentAddress = computed(() => addresses.value.find(a=>a.id===addressId.value))
const count = computed(() => cart.value.reduce((sum,line)=>sum+line.quantity,0))
const subtotal = computed(() => cart.value.reduce((sum,line)=>sum+line.unit*line.quantity,0))
const usableCoupons = computed(()=>coupons.value.filter(c=>!c.used))
const chosenCoupon = computed(()=>usableCoupons.value.find(c=>c.id===selectedCoupon.value&&subtotal.value>=c.min))
const discount = computed(()=>Math.min(chosenCoupon.value?.discount||0,subtotal.value))
const deliveryFee = computed(()=>mode.value==='delivery'&&subtotal.value<35?6:0)
const total = computed(()=>Math.max(0,subtotal.value-discount.value+deliveryFee.value))
const visibleDrinks = computed(()=>drinks.filter(d=>(category.value==='全部'||d.category===category.value)&&(d.name+d.en).toLowerCase().includes(search.value.toLowerCase().trim())))
const unit = computed(()=>(drink.value?.price||0)+(size.value==='超大杯'?4:0)+toppings.value.reduce((sum,x)=>sum+(x==='轻芝士奶盖'?3:2),0))
const activeOrder = computed(()=>orders.value.find(o=>o.id===selectedOrderId.value))
const visibleOrders = computed(()=>orders.value.filter(o=>orderTab.value==='进行中'?['ready','refunding'].includes(o.status):!['ready','refunding'].includes(o.status)))
const titles: Partial<Record<Screen,string>> = { stores:'选择门店',checkout:'确认订单','order-detail':'订单详情',coupons:'我的优惠券',points:'我的叶子',balance:'我的钱包',favorites:'我的收藏',addresses:'收货地址',help:'帮助与客服',settings:'设置',member:'叶集会员',messages:'消息中心',gift:'送一杯心意' }
const tabs = [{id:'home',name:'首页',icon:'home'},{id:'shop',name:'点单',icon:'cup'},{id:'orders',name:'订单',icon:'order'},{id:'me',name:'我的',icon:'user'}] as const
const topLevel = computed(()=>tabs.some(t=>t.id===screen.value))
const faqs = [{q:'下单后如何取餐？',a:'选择到店自取后，订单详情会展示取餐门店和取餐码。到店向店员出示取餐码即可。当前界面体验中的订单不会发送给真实门店。'},{q:'如何使用优惠券？',a:'在确认订单页点击优惠券，选择满足门槛的券即可抵扣。每笔订单可使用一张，优惠券不能叠加。'},{q:'可以修改冰量、甜度或加料吗？',a:'点开喜欢的饮品，在规格弹层选择杯型、温度、甜度与加料，再加入购物袋。'},{q:'外送如何收费？',a:'界面体验中外送费为 6 元，商品金额满 35 元免配送费。实际营业规则将在正式上线前确认。'},{q:'订单怎么申请退款？',a:'进入订单详情，点击售后申请并填写原因。当前预览只演示申请和处理进度，不会产生实际退款。'}]
let toastTimer: ReturnType<typeof setTimeout>
function notify(message:string){toast.value=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',2800)}
function go(next:Screen){screen.value=next;location.hash=next;sheet.value='';window.scrollTo({top:0,behavior:'instant'})}
function back(){if(screen.value==='stores')go(storeReturn.value);else if(screen.value==='checkout')go('shop');else if(screen.value==='order-detail')go('orders');else if(screen.value==='coupons')go(couponReturn.value);else if(screen.value==='addresses')go(addressReturn.value);else go('me')}
function route(){const next=location.hash.slice(1) as Screen;screen.value=screens.includes(next)?next:'home';sheet.value=''}
function keydown(e:KeyboardEvent){if(e.key==='Escape')sheet.value=''}
function findDrink(id:string){return drinks.find(d=>d.id===id)||drinks[0]}
function description(line:CartLine){return [line.size,line.temp,line.sugar,...line.toppings].join(' / ')}
function openDrink(d:Drink){drink.value=d;size.value='标准杯';temp.value='正常冰';sugar.value='推荐甜';toppings.value=[];quantity.value=1;sheet.value='drink'}
function favorite(id:string){favorites.value=favorites.value.includes(id)?favorites.value.filter(x=>x!==id):[...favorites.value,id];notify(favorites.value.includes(id)?'已加入收藏，下次更快找到':'已取消收藏')}
function toggleTopping(value:string){toppings.value=toppings.value.includes(value)?toppings.value.filter(x=>x!==value):[...toppings.value,value]}
function addDrink(){if(!drink.value)return;const key=JSON.stringify([drink.value.id,size.value,temp.value,sugar.value,[...toppings.value].sort()]);const found=cart.value.find(x=>x.key===key);if(found)found.quantity=Math.min(99,found.quantity+quantity.value);else cart.value.push({key,drinkId:drink.value.id,size:size.value,temp:temp.value,sugar:sugar.value,toppings:[...toppings.value],unit:unit.value,quantity:quantity.value});sheet.value='';notify('已加入购物袋');if(screen.value==='favorites')go('shop')}
function adjust(line:CartLine,delta:number){line.quantity=Math.min(99,line.quantity+delta);if(line.quantity<=0)cart.value=cart.value.filter(x=>x.key!==line.key)}
function selectStore(id:string){if(!stores.find(s=>s.id===id)?.open){notify('门店已打烊，请选择其他门店');return}if(id!==storeId.value&&count.value){pendingStore.value=id;sheet.value='switch-store';return}switchStore(id)}
function switchStore(id:string){write(`cart.${storeId.value}`,cart.value);storeId.value=id;cart.value=read(`cart.${id}`,[]);selectedCoupon.value='';go(storeReturn.value);notify('已切换门店，购物袋按门店独立保存')}
function openStores(){search.value='';storeReturn.value=screen.value;go('stores')}
function startOrder(type:'pickup'|'delivery'){mode.value=type;go('shop')}
function checkout(){if(!count.value){notify('先选一杯喜欢的饮品吧');return}selectedCoupon.value=[...usableCoupons.value].filter(c=>subtotal.value>=c.min).sort((a,b)=>b.discount-a.discount)[0]?.id||'';go('checkout')}
function openCoupons(){couponReturn.value=screen.value;couponTab.value='可使用';go('coupons')}
function chooseCoupon(id:string){selectedCoupon.value=id;go('checkout')}
function claim(){if(coupons.value.some(c=>c.id==='new-leaf')){notify('这份福利已经领取过啦');return}coupons.value.push({id:'new-leaf',name:'春日尝鲜礼',discount:5,min:25,end:'2026.12.31'});notify('5 元尝鲜券已到账')}
function openAddresses(){addressReturn.value=screen.value;go('addresses')}
function editAddress(a?:Address){addressDraft.value=a?{...a}:{id:'',name:'',phone:'',address:'',label:'家'};sheet.value='address'}
function saveAddress(){const a=addressDraft.value;if(!a.name.trim()||!/^1\d{10}$/.test(a.phone)||a.address.trim().length<5){notify('请填写联系人、11 位手机号和详细地址');return}if(a.id)addresses.value=addresses.value.map(x=>x.id===a.id?{...a}:x);else{a.id=crypto.randomUUID();addresses.value.push({...a})}addressId.value=a.id;sheet.value='';notify('地址已保存到本机')}
function removeAddress(id:string){addresses.value=addresses.value.filter(a=>a.id!==id);if(addressId.value===id)addressId.value=addresses.value[0]?.id||'';notify('地址已删除')}
function requestPayment(){if(!count.value){go('shop');notify('购物袋为空，请重新选购');return}if(mode.value==='delivery'&&!currentAddress.value){openAddresses();notify('请先添加收货地址');return}sheet.value='payment'}
function placeOrder(){if(submitting.value)return;if(payment.value==='balance'&&balance.value<total.value){notify('余额不足，请选择其他支付方式');return}submitting.value=true;const id=crypto.randomUUID();const code='Y'+String(orders.value.length+101);const order:DemoOrder={id,code,date:new Date().toLocaleString('zh-CN',{hour12:false}),status:'ready',storeId:storeId.value,mode:mode.value,lines:JSON.parse(JSON.stringify(cart.value)),subtotal:subtotal.value,discount:discount.value,deliveryFee:deliveryFee.value,total:total.value,couponId:chosenCoupon.value?.id||'',note:note.value,time:pickupTime.value,address:mode.value==='delivery'?currentAddress.value?.address||'':''};if(payment.value==='balance')balance.value=Math.round((balance.value-total.value)*100)/100;if(chosenCoupon.value)chosenCoupon.value.used=true;points.value+=Math.floor(total.value);orders.value.unshift(order);cart.value=[];note.value='';selectedOrderId.value=id;submitting.value=false;go('order-detail');notify('体验订单已生成，不会实际扣款')}
function openOrder(o:DemoOrder){selectedOrderId.value=o.id;go('order-detail')}
function again(o:DemoOrder){if(o.storeId!==storeId.value){write(`cart.${storeId.value}`,cart.value);storeId.value=o.storeId;cart.value=read(`cart.${o.storeId}`,[])}for(const line of o.lines){const old=cart.value.find(c=>c.key===line.key);if(old)old.quantity=Math.min(99,old.quantity+line.quantity);else cart.value.push({...line,toppings:[...line.toppings]})}go('shop');notify('熟悉的味道，已放入购物袋')}
function finishOrder(){if(activeOrder.value){activeOrder.value.status='done';notify('感谢喜欢，期待下一杯相见')}}
function submitRefund(){if(!noteDraft.value.trim()){notify('请描述一下遇到的问题');return}if(activeOrder.value){activeOrder.value.status='refunding';sheet.value='';notify('售后申请已提交（仅本机演示）')}}
function orderStatus(o:DemoOrder){return ({ready:o.mode==='pickup'?'饮品已就绪，来取吧':'饮品已备好，等待配送',done:'这一杯，刚刚好',cancelled:'订单已取消',refunding:'售后申请处理中',refunded:'退款已完成'})[o.status]}
function memberLogin(){member.value=true;sheet.value='';notify('已开启会员体验，权益仅用于界面演示')}
function selectAddress(a:Address){addressId.value=a.id;if(addressReturn.value==='checkout')go('checkout');else notify('已设为默认地址')}
const redeemItems=[{name:'清饮抵扣券',cost:80,discount:3},{name:'饮品 5 元券',cost:120,discount:5},{name:'饮品 8 元券',cost:200,discount:8}]
function redeem(item:typeof redeemItems[number]){if(points.value<item.cost){notify('叶子还不够，再攒一攒吧');return}points.value-=item.cost;coupons.value.push({id:crypto.randomUUID(),name:item.name,discount:item.discount,min:15,end:'2026.12.31'});notify('兑换成功，可在优惠券中查看')}
function sendGift(){if(!giftRecipient.value.trim()){notify('写下收礼人的称呼吧');return}giftSent.value=true;notify('心意卡已生成，未产生真实付款')}
watch(cart,()=>write(`cart.${storeId.value}`,cart.value),{deep:true,flush:'sync'})
watch(storeId,v=>write('store',v));watch(mode,v=>write('mode',v));watch(favorites,v=>write('favorites',v),{deep:true});watch(orders,v=>write('orders',v),{deep:true});watch(coupons,v=>write('coupons',v),{deep:true});watch(points,v=>write('points',v));watch(balance,v=>write('balance',v));watch(member,v=>write('member',v));watch(nickname,v=>write('nickname',v));watch(addresses,v=>write('addresses',v),{deep:true});watch(addressId,v=>write('addressId',v));watch(notification,v=>write('notification',v))
watch(sheet,v=>{document.body.style.overflow=v?'hidden':''})
onMounted(()=>{document.title='叶集 YEJI · 好茶，常相见';window.addEventListener('hashchange',route);window.addEventListener('keydown',keydown)})
onUnmounted(()=>{window.removeEventListener('hashchange',route);window.removeEventListener('keydown',keydown);clearTimeout(toastTimer);document.body.style.overflow=''})
</script>

<template>
<div class="yeji-app">
  <header v-if="topLevel" class="brand-header"><button class="brand" @click="go('home')"><span class="brand-seal"><Icon name="leaf" :size="25"/></span><span>叶集 <b>YEJI</b></span></button><div class="header-actions"><button class="preview-pill" @click="sheet='preview'">界面体验</button><button aria-label="消息中心" class="icon-button notification-dot" @click="go('messages')"><Icon name="bell"/></button></div></header>
  <header v-else class="page-header"><button aria-label="返回" class="icon-button" @click="back"><Icon name="back"/></button><h1>{{ titles[screen] }}</h1><button aria-label="体验说明" class="icon-button" @click="sheet='preview'"><Icon name="info" :size="19"/></button></header>

  <main v-if="screen==='home'" class="home-screen">
    <section class="campaign"><div class="campaign-image"></div><div class="campaign-copy"><span class="overline">THE MATCHA SEASON</span><h1>把春天<br>喝进日常。</h1><p>一抹新绿，一口轻盈。<br>云顶抹茶系列 · 清新上市</p><button @click="openDrink(drinks[0])">尝一口春天 <Icon name="arrow" :size="15"/></button></div><div class="campaign-foot"><span>叶集 · 四季有茶</span><span>当季新品 · MATCHA</span></div></section>
    <section class="order-entry"><button @click="startOrder('pickup')"><div class="entry-illustration"><Icon name="bag" :size="38"/><i></i></div><div><h2>到店自取</h2><p>提前点，不用等</p></div><Icon name="arrow" :size="18"/></button><span class="entry-divider"></span><button @click="startOrder('delivery')"><div class="entry-illustration delivery"><Icon name="bike" :size="41"/><i></i></div><div><h2>外送到家</h2><p>好茶送到你身边</p></div><Icon name="arrow" :size="18"/></button></section>
    <section class="home-member"><button class="member-intro" @click="member?go('member'):sheet='login'"><span class="tiny-avatar"><Icon name="leaf" :size="20"/></span><div><strong>{{ member?`${nickname}，今天也要好好喝茶`:'成为叶集好友' }}</strong><small>{{ member?'每一杯喜欢，都值得被记住':'新朋友，送你一份见面礼' }}</small></div><Icon name="arrow" :size="16"/></button><div class="member-shortcuts"><button @click="openCoupons"><Icon name="ticket"/><span>{{ usableCoupons.length }} 张好礼</span></button><button @click="go('points')"><Icon name="leaf"/><span>{{ points }} 片叶子</span></button><button @click="go('gift')"><Icon name="gift"/><span>送一杯心意</span></button></div></section>
    <section class="home-section"><div class="section-heading"><div><span class="overline">FIND YOUR FAVORITE</span><h2>今天，想喝点什么？</h2></div><button class="text-link" @click="go('shop')">全部饮品 <Icon name="arrow" :size="13"/></button></div><div class="drink-carousel"><button v-for="d in drinks.slice(0,4)" :key="d.id" class="recommend-card" @click="openDrink(d)"><div class="recommend-art" :style="{'--drink-bg':d.milk}"><span>{{ d.label }}</span><DrinkArt :color="d.color" :milk="d.milk"/></div><h3>{{ d.name }}</h3><p>{{ d.flavor.split(' · ')[0] }}</p><div><strong><small>¥</small>{{ d.price }}</strong><span class="mini-add"><Icon name="plus" :size="14"/></span></div></button></div></section>
    <section class="editorial" @click="go('member')"><div><span class="overline">A LITTLE RITUAL, EVERY DAY</span><h2>好茶，常相见。</h2><p>从一片叶子开始，认真对待每一杯。</p><button class="text-link">认识叶集 <Icon name="arrow" :size="14"/></button></div><div class="editorial-leaf"><Icon name="leaf" :size="95"/></div></section><p class="home-bottom">一杯好茶，一段属于自己的时光。<span>YEJI · TEA FOR EVERYDAY</span></p>
  </main>

  <main v-else-if="screen==='shop'" class="shop-screen"><div class="shop-store"><button @click="openStores"><h2>{{ currentStore.name }} <Icon name="chevron" :size="16"/></h2><p><span class="open-dot"></span>营业中 · 距你 {{ currentStore.distance }} · 约 {{ currentStore.time }} 分钟可取</p></button><div class="mode-toggle"><button :class="{active:mode==='pickup'}" @click="mode='pickup'">自取</button><button :class="{active:mode==='delivery'}" @click="mode='delivery'">外送</button></div></div><div v-if="mode==='delivery'" class="delivery-address" @click="openAddresses"><Icon name="pin" :size="15"/><span>{{ currentAddress?.address||'添加收货地址，让好茶送到家' }}</span><Icon name="arrow" :size="13"/></div><div class="shop-search"><Icon name="search" :size="18"/><input v-model="search" aria-label="搜索饮品" placeholder="想喝什么？搜搜看"><button v-if="search" aria-label="清空搜索" @click="search=''"><Icon name="close" :size="15"/></button></div><button class="shop-offer" @click="openCoupons"><Icon name="ticket" :size="17"/><span>新朋友见面礼 · 满 20 元减 6 元</span><span>去看看 <Icon name="arrow" :size="12"/></span></button><div class="catalog"><aside class="category-rail"><button v-for="c in categories" :key="c" :class="{active:category===c}" @click="category=c"><Icon v-if="c==='当季新品'" name="leaf" :size="14"/>{{ c }}</button><button class="favorite-category" @click="go('favorites')"><Icon name="heart" :size="17"/>我的收藏</button></aside><section class="catalog-products"><div class="catalog-heading"><h3>{{ search?'搜索结果':category==='全部'?'人气好茶':category }}</h3><span>{{ visibleDrinks.length }} 款</span></div><div v-if="!visibleDrinks.length" class="empty-state"><Icon name="search" :size="40"/><h3>还没找到这杯茶</h3><p>换个关键词，或看看全部饮品</p><button class="outline-button" @click="search='';category='全部'">查看全部</button></div><article v-for="d in visibleDrinks" :key="d.id" class="catalog-card"><button class="catalog-art" :style="{background:d.milk+'70'}" :aria-label="`查看${d.name}`" @click="openDrink(d)"><DrinkArt :color="d.color" :milk="d.milk"/></button><div class="catalog-info"><span v-if="d.label" class="product-tag">{{ d.label }}</span><button class="drink-name" @click="openDrink(d)">{{ d.name }}</button><p>{{ d.flavor }}</p><small>{{ d.en }}</small><div class="catalog-price"><strong><small>¥</small>{{ d.price }}<em>起</em></strong><button class="add-circle" :aria-label="`选规格 ${d.name}`" @click="openDrink(d)"><Icon name="plus" :size="17"/></button></div></div></article><div class="catalog-end"><Icon name="leaf" :size="15"/> 好茶现做，值得片刻等待</div></section></div><div class="shopping-dock"><button class="bag-summary" @click="sheet='cart'"><span class="bag-icon"><Icon name="bag" :size="25"/><b v-if="count">{{ count }}</b></span><div><strong>{{ count?'¥'+price(subtotal):'选一杯喜欢的吧' }}</strong><small>{{ count?`共 ${count} 件 · ${mode==='pickup'?'到店自取':'满 35 元免配送费'}`:'好茶现做，为你而来' }}</small></div></button><button class="checkout-cta" :disabled="!count" @click="checkout">去结算</button></div></main>

  <main v-else-if="screen==='orders'" class="orders-screen"><div class="screen-intro"><span class="overline">YOUR LITTLE MOMENTS</span><h1>每一杯，都记得。</h1></div><div class="underline-tabs"><button v-for="t in ['进行中','历史订单']" :key="t" :class="{active:orderTab===t}" @click="orderTab=t">{{ t }}<span v-if="t==='进行中'&&orders.filter(o=>o.status==='ready').length">{{ orders.filter(o=>o.status==='ready').length }}</span></button></div><div v-if="!visibleOrders.length" class="empty-state order-empty"><div class="empty-art"><DrinkArt color="#8b9c63" milk="#ece6ce"/></div><h2>{{ orderTab==='进行中'?'此刻，少一杯好茶':'你的好茶日常，从这里开始' }}</h2><p>{{ orderTab==='进行中'?'去挑一杯喜欢的，我们为你现做。':'喝过的每一杯，都会好好记在这里。' }}</p><button class="solid-button" @click="go('shop')">去点一杯</button></div><article v-for="o in visibleOrders" :key="o.id" class="order-preview"><button class="order-preview-head" @click="openOrder(o)"><strong>{{ stores.find(s=>s.id===o.storeId)?.name }} <Icon name="arrow" :size="13"/></strong><span>{{ ({ready:'待取餐',done:'已完成',cancelled:'已取消',refunding:'售后中',refunded:'已退款'})[o.status] }}</span></button><p class="micro-copy">{{ o.date }} · {{ o.mode==='pickup'?'到店自取':'外送到家' }} · 体验订单</p><button class="order-preview-content" @click="openOrder(o)"><div class="order-mini-art"><DrinkArt :color="findDrink(o.lines[0].drinkId).color" :milk="findDrink(o.lines[0].drinkId).milk"/></div><div><h3>{{ o.lines.map(l=>findDrink(l.drinkId).name).join('、') }}</h3><p>共 {{ o.lines.reduce((s,l)=>s+l.quantity,0) }} 件 <strong>¥{{ price(o.total) }}</strong></p></div></button><footer><button class="outline-button small" @click="again(o)">再来一单</button><button class="solid-button small" @click="openOrder(o)">{{ o.status==='ready'?'查看取餐码':'查看详情' }}</button></footer></article></main>

  <main v-else-if="screen==='me'" class="me-screen"><section class="profile-row"><button class="profile-avatar" @click="member?go('settings'):sheet='login'"><Icon name="leaf" :size="32"/></button><button class="profile-name" @click="member?go('member'):sheet='login'"><h1>{{ member?nickname:'你好，新朋友' }} <Icon name="arrow" :size="17"/></h1><p>{{ member?'叶集银叶会员 · 今天也要有好心情':'登录 / 注册，开启你的好茶日常' }}</p></button><button class="icon-button" aria-label="设置" @click="go('settings')"><Icon name="settings"/></button></section><button class="membership-card" @click="go('member')"><div><span>YEJI CLUB</span><Icon name="leaf" :size="25"/></div><h2>每一片叶子，都有回响。</h2><p>再积攒 72 片叶子，解锁金叶会员</p><div class="membership-progress"><i></i></div><footer><span>银叶会员</span><span>会员权益 <Icon name="arrow" :size="13"/></span></footer></button><div class="assets-row"><button @click="go('points')"><strong>{{ points }}</strong><span>我的叶子</span></button><button @click="openCoupons"><strong>{{ usableCoupons.length }}</strong><span>优惠券</span></button><button @click="go('balance')"><strong>{{ price(balance) }}</strong><span>钱包余额</span></button><button @click="go('favorites')"><strong>{{ favorites.length }}</strong><span>我的收藏</span></button></div><section class="my-order-link"><button @click="go('orders')"><strong>我的订单</strong><span>查看全部 <Icon name="arrow" :size="14"/></span></button><div><button @click="orderTab='进行中';go('orders')"><Icon name="cup"/><span>进行中</span></button><button @click="orderTab='历史订单';go('orders')"><Icon name="check"/><span>已完成</span></button><button @click="orderTab='进行中';go('orders')"><Icon name="help"/><span>退款 / 售后</span></button></div></section><section class="service-grid"><button v-for="item in [{screen:'gift',icon:'gift',name:'送一杯心意'},{screen:'addresses',icon:'pin',name:'收货地址'},{screen:'help',icon:'help',name:'帮助与客服'},{screen:'messages',icon:'bell',name:'消息中心'},{screen:'stores',icon:'search',name:'寻找门店'},{screen:'settings',icon:'settings',name:'账户设置'}]" :key="item.name" @click="item.screen==='stores'?openStores():item.screen==='addresses'?openAddresses():go(item.screen as Screen)"><Icon :name="item.icon" :size="25"/><span>{{ item.name }}</span></button></section><div class="brand-signoff"><Icon name="leaf" :size="20"/>好茶，常相见。<span>YEJI · TEA FOR EVERYDAY</span></div></main>

  <main v-else-if="screen==='stores'" class="stores-screen"><div class="store-search"><span>杭州 <Icon name="chevron" :size="13"/></span><Icon name="search" :size="17"/><input v-model="search" placeholder="搜索门店名称或地址" aria-label="搜索门店"></div><div class="map-art" aria-label="门店位置示意图"><div class="map-river"></div><i class="map-road road-one"></i><i class="map-road road-two"></i><span class="map-park">湖滨公园</span><div class="map-pin"><Icon name="leaf" :size="20"/><span>叶集 · 湖滨银泰店</span></div><div class="map-you"></div><span class="map-caption">杭州 · 门店位置示意</span></div><div class="nearby-title"><h2>附近门店</h2><span>共 {{ stores.length }} 家</span></div><article v-for="s in stores.filter(s=>(s.name+s.address).includes(search))" :key="s.id" class="store-choice" :class="{selected:s.id===storeId,closed:!s.open}"><div class="store-choice-main"><span class="store-icon"><Icon name="home" :size="26"/></span><div><h3>{{ s.name }}</h3><span class="store-tag">{{ s.tag }}</span><p>{{ s.address }}</p><small>{{ s.hours }} · {{ s.distance }}</small></div></div><footer><span>{{ s.open?`预计 ${s.time} 分钟可取`:'明日 10:00 开始营业' }}</span><button class="solid-button small" :disabled="!s.open" @click="selectStore(s.id)">{{ s.id===storeId?'当前门店':'选择门店' }}</button></footer></article><div v-if="!stores.some(s=>(s.name+s.address).includes(search))" class="empty-state"><h3>没有找到门店</h3><button class="outline-button" @click="search=''">清空搜索</button></div></main>

  <main v-else-if="screen==='checkout'" class="checkout-screen"><div class="fulfillment-tabs"><button :class="{active:mode==='pickup'}" @click="mode='pickup'"><Icon name="bag" :size="20"/>到店自取</button><button :class="{active:mode==='delivery'}" @click="mode='delivery'"><Icon name="bike" :size="23"/>外送到家</button></div><section class="checkout-location"><span class="overline">{{ mode==='pickup'?'PICK UP YOUR LITTLE JOY':'A LITTLE JOY, TO YOUR DOOR' }}</span><button @click="mode==='pickup'?openStores():openAddresses()"><h2>{{ mode==='pickup'?currentStore.name:currentAddress?.address||'请添加收货地址' }}</h2><Icon name="arrow" :size="18"/></button><p>{{ mode==='pickup'?currentStore.address:`${currentAddress?.name||''} ${currentAddress?.phone||''}` }}</p><button class="schedule-row" @click="sheet='time'"><Icon name="clock" :size="16"/><span>{{ mode==='pickup'?'取餐时间':'送达时间' }}</span><strong>{{ pickupTime==='尽快取餐'?(mode==='pickup'?`尽快取餐 · 约 ${currentStore.time} 分钟`:'尽快送达 · 约 35 分钟'):pickupTime }}</strong><Icon name="arrow" :size="13"/></button></section><section class="white-panel checkout-items"><h3>喜欢的，都在这里 <span>{{ count }} 件</span></h3><div v-for="line in cart" :key="line.key" class="checkout-item"><div class="checkout-drink"><DrinkArt :color="findDrink(line.drinkId).color" :milk="findDrink(line.drinkId).milk"/></div><div><h4>{{ findDrink(line.drinkId).name }}</h4><p>{{ description(line) }}</p><small>× {{ line.quantity }}</small></div><strong>¥{{ price(line.unit*line.quantity) }}</strong></div><button class="menu-row" @click="openCoupons"><span><Icon name="ticket" :size="18"/>优惠券</span><span :class="{discount:discount>0}">{{ discount?`已优惠 ¥${price(discount)}`:`${usableCoupons.length} 张可选` }}<Icon name="arrow" :size="14"/></span></button><div class="receipt-row"><span>商品金额</span><span>¥{{ price(subtotal) }}</span></div><div v-if="mode==='delivery'" class="receipt-row"><span>配送费 <small>满 35 元免配送</small></span><span>{{ deliveryFee?'¥'+deliveryFee:'免配送费' }}</span></div><div class="receipt-total"><span>已优惠 <b>¥{{ price(discount) }}</b></span><strong>小计 <em>¥{{ price(total) }}</em></strong></div></section><section class="white-panel"><button class="menu-row" @click="noteDraft=note;sheet='note'"><span>订单备注</span><span class="truncated">{{ note||'口味偏好、其他要求' }}<Icon name="arrow" :size="14"/></span></button><button class="menu-row" @click="sheet='contact'"><span>取餐联系人</span><span>{{ nickname }} · 138****8000<Icon name="arrow" :size="14"/></span></button></section><p class="checkout-note"><Icon name="info" :size="14"/>当前为界面体验，下单不会扣款或通知门店。</p><div class="checkout-bottom"><div><small>共 {{ count }} 件，已优惠 ¥{{ price(discount) }}</small><strong>合计 <b>¥{{ price(total) }}</b></strong></div><button class="solid-button" :disabled="!count" @click="requestPayment">确认下单</button></div></main>

  <main v-else-if="screen==='order-detail'" class="detail-screen"><template v-if="activeOrder"><section class="order-status"><span class="status-round"><Icon :name="activeOrder.status==='ready'?'cup':activeOrder.status==='refunding'?'clock':'check'" :size="30"/></span><h1>{{ orderStatus(activeOrder) }}</h1><p>{{ activeOrder.status==='ready'?'把这一刻，留给一杯好茶。':'感谢你让叶集成为日常的一部分。' }}</p><span class="experience-tag">体验订单 · 无实际扣款</span></section><section v-if="activeOrder.status==='ready'" class="pickup-card"><div class="order-steps"><span class="done"><i></i>已下单</span><b></b><span class="done"><i></i>制作完成</span><b></b><span class="done"><i></i>{{ activeOrder.mode==='pickup'?'待取餐':'待配送' }}</span></div><p>{{ activeOrder.mode==='pickup'?'你的取餐码':'配送取件码' }}</p><strong>{{ activeOrder.code }}</strong><small>{{ activeOrder.mode==='pickup'?'到店后向店员出示取餐码':'这是外送状态的界面演示' }}</small><button class="outline-button" @click="finishOrder">{{ activeOrder.mode==='pickup'?'确认已取餐':'确认已收到' }}</button></section><section class="white-panel detail-store"><h3><Icon name="pin" :size="18"/>{{ stores.find(s=>s.id===activeOrder?.storeId)?.name }}</h3><p>{{ activeOrder.address||stores.find(s=>s.id===activeOrder?.storeId)?.address }}</p><div><button @click="go('help')"><Icon name="phone" :size="16"/>联系门店</button><button @click="openStores"><Icon name="pin" :size="16"/>查看位置</button></div></section><section class="white-panel"><div v-for="line in activeOrder.lines" :key="line.key" class="checkout-item"><div class="checkout-drink"><DrinkArt :color="findDrink(line.drinkId).color" :milk="findDrink(line.drinkId).milk"/></div><div><h4>{{ findDrink(line.drinkId).name }}</h4><p>{{ description(line) }}</p><small>× {{ line.quantity }}</small></div><strong>¥{{ price(line.unit*line.quantity) }}</strong></div><div class="receipt-row"><span>优惠抵扣</span><span>−¥{{ price(activeOrder.discount) }}</span></div><div v-if="activeOrder.deliveryFee" class="receipt-row"><span>配送费</span><span>¥{{ activeOrder.deliveryFee }}</span></div><div class="receipt-total"><span>合计</span><strong>¥{{ price(activeOrder.total) }}</strong></div></section><section class="white-panel order-meta"><p><span>订单时间</span>{{ activeOrder.date }}</p><p><span>订单备注</span>{{ activeOrder.note||'无' }}</p><p><span>取餐方式</span>{{ activeOrder.mode==='pickup'?'到店自取':'外送到家' }}</p></section><div class="detail-actions"><button class="outline-button" @click="noteDraft='';sheet='refund'">{{ activeOrder.status==='refunding'?'查看售后':'申请售后' }}</button><button class="solid-button" @click="again(activeOrder)">再来一单</button></div></template><div v-else class="empty-state"><Icon name="order" :size="45"/><h2>还没有选择订单</h2><button class="solid-button" @click="go('orders')">查看我的订单</button></div></main>

  <main v-else-if="screen==='coupons'" class="coupon-screen"><div class="coupon-heading"><h2>让喜欢，多一点惊喜。</h2><p>{{ couponReturn==='checkout'?'选择本单优惠，享受一杯好茶':'你的每一份好礼，都在这里。' }}</p></div><div class="underline-tabs"><button v-for="t in ['可使用','已使用']" :key="t" :class="{active:couponTab===t}" @click="couponTab=t">{{ t }}</button></div><article v-for="c in coupons.filter(c=>couponTab==='可使用'?!c.used:c.used)" :key="c.id" class="coupon-ticket" :class="{unavailable:c.used||(couponReturn==='checkout'&&subtotal<c.min)}"><div class="coupon-value"><strong><small>¥</small>{{ c.discount }}</strong><span>满 {{ c.min }} 元可用</span></div><div class="coupon-description"><h3>{{ c.name }}</h3><p>适用全部现制饮品</p><small>有效期至 {{ c.end }}</small><span v-if="couponReturn==='checkout'&&subtotal<c.min" class="coupon-shortfall">还差 ¥{{ price(c.min-subtotal) }} 可使用</span></div><button v-if="!c.used" :disabled="couponReturn==='checkout'&&subtotal<c.min" @click="couponReturn==='checkout'?chooseCoupon(c.id):go('shop')">{{ couponReturn==='checkout'&&selectedCoupon===c.id?'已选择':'去使用' }}</button><span v-else>已使用</span></article><div v-if="!coupons.some(c=>couponTab==='可使用'?!c.used:c.used)" class="empty-state"><Icon name="ticket" :size="45"/><h3>这里还没有优惠券</h3><p>看看下方的尝鲜福利吧</p></div><button v-if="couponReturn==='checkout'" class="outline-button wide" @click="chooseCoupon('')">本单不使用优惠券</button><section class="claim-banner"><div><span class="overline">A GIFT FOR YOU</span><h3>春日尝鲜，送你 5 元好礼</h3><p>满 25 元可用 · 每人限领一次</p></div><button class="solid-button small" :disabled="coupons.some(c=>c.id==='new-leaf')" @click="claim">{{ coupons.some(c=>c.id==='new-leaf')?'已领取':'领取' }}</button></section></main>

  <main v-else-if="screen==='points'" class="points-screen"><section class="points-hero"><Icon name="leaf" :size="38"/><p>我的叶子</p><strong>{{ points }}</strong><span>每一杯喜欢，都在慢慢生长。</span></section><div class="section-heading padded"><div><span class="overline">LEAVES INTO LITTLE JOYS</span><h2>叶子兑换</h2></div></div><div class="redeem-grid"><article v-for="item in redeemItems" :key="item.name"><div class="redeem-icon"><Icon name="ticket" :size="38"/><b>¥{{ item.discount }}</b></div><h3>{{ item.name }}</h3><p>{{ item.cost }} 片叶子</p><button class="outline-button" :disabled="points<item.cost" @click="redeem(item)">{{ points<item.cost?'叶子不足':'立即兑换' }}</button></article></div><section class="white-panel rules"><h3>叶子如何生长？</h3><p>体验下单每消费 1 元可获得 1 片叶子，可用于兑换饮品优惠券。所有积分和兑换仅保存在本机。</p></section></main>

  <main v-else-if="screen==='balance'" class="wallet-screen"><section class="wallet-hero"><span>YEJI WALLET</span><p>可用余额（元）</p><strong>{{ balance.toFixed(2) }}</strong><small>界面演示余额，不代表真实资金</small></section><section class="white-panel"><button class="menu-row" @click="sheet='topup'"><span><Icon name="wallet" :size="20"/>充值体验</span><Icon name="arrow" :size="16"/></button><button class="menu-row" @click="sheet='balance-history'"><span><Icon name="order" :size="20"/>余额明细</span><Icon name="arrow" :size="16"/></button><button class="menu-row" @click="go('gift')"><span><Icon name="gift" :size="20"/>送一张心意卡</span><Icon name="arrow" :size="16"/></button></section><p class="fine-print">钱包页面用于体验交互，不接入充值或支付渠道。</p></main>

  <main v-else-if="screen==='favorites'" class="favorites-screen"><p class="page-description">收藏的每一杯，都是下次见面的理由。</p><div v-if="!favorites.length" class="empty-state"><Icon name="heart" :size="50"/><h2>把喜欢，留在这里。</h2><p>在饮品详情点击爱心，收藏你的专属口味。</p><button class="solid-button" @click="go('shop')">发现好茶</button></div><article v-for="d in drinks.filter(d=>favorites.includes(d.id))" :key="d.id" class="favorite-card"><div @click="openDrink(d)"><DrinkArt :color="d.color" :milk="d.milk"/></div><section><h3>{{ d.name }}</h3><p>{{ d.flavor }}</p><strong>¥{{ d.price }}</strong></section><button aria-label="取消收藏" class="liked icon-button" @click="favorite(d.id)"><Icon name="heart"/></button><button class="add-circle" :aria-label="`选规格 ${d.name}`" @click="openDrink(d)"><Icon name="plus" :size="18"/></button></article></main>

  <main v-else-if="screen==='addresses'" class="addresses-screen"><p class="page-description">好茶送到，熟悉的地方。</p><div v-if="!addresses.length" class="empty-state"><Icon name="pin" :size="44"/><h2>还没有收货地址</h2><p>添加地址，体验外送点单</p></div><article v-for="a in addresses" :key="a.id" class="address-card"><button class="address-select" @click="selectAddress(a)"><div><span class="address-label">{{ a.label }}</span><span v-if="addressId===a.id" class="default-label">默认</span></div><h3>{{ a.address }}</h3><p>{{ a.name }} <span>{{ a.phone }}</span></p></button><div class="address-tools"><button :aria-label="`编辑${a.name}的地址`" @click="editAddress(a)"><Icon name="edit" :size="18"/></button><button :aria-label="`删除${a.name}的地址`" @click="removeAddress(a.id)"><Icon name="trash" :size="18"/></button></div></article><button class="solid-button wide" @click="editAddress()"><Icon name="plus" :size="18"/>新增收货地址</button></main>

  <main v-else-if="screen==='help'" class="help-screen"><div class="help-hero"><Icon name="help" :size="45"/><h2>有什么可以帮你？</h2><p>关于这一杯，我们都认真倾听。</p></div><section class="white-panel"><h3>常见问题</h3><div v-for="(faq,index) in faqs" :key="faq.q" class="faq"><button :aria-expanded="helpOpen===index" @click="helpOpen=helpOpen===index?-1:index">{{ faq.q }}<Icon :name="helpOpen===index?'minus':'plus'" :size="17"/></button><p v-if="helpOpen===index">{{ faq.a }}</p></div></section><button class="solid-button wide" @click="sheet='support'"><Icon name="mail" :size="18"/>联系在线客服</button><p class="fine-print">服务时间 09:00–22:00 · 当前为客服界面演示</p></main>

  <main v-else-if="screen==='settings'" class="settings-screen"><section class="white-panel"><button class="menu-row" @click="sheet='nickname'"><span>昵称</span><span>{{ nickname }}<Icon name="arrow" :size="15"/></span></button><button class="menu-row" @click="sheet='contact'"><span>手机号</span><span>138****8000<Icon name="arrow" :size="15"/></span></button><div class="menu-row"><span>订单消息提醒</span><button class="switch" role="switch" aria-label="订单消息提醒" :aria-checked="notification" :class="{on:notification}" @click="notification=!notification"><i></i></button></div></section><section class="white-panel"><button class="menu-row" @click="sheet='privacy'"><span>隐私与本机数据</span><Icon name="arrow" :size="16"/></button><button class="menu-row" @click="sheet='preview'"><span>关于叶集</span><span>界面体验版<Icon name="arrow" :size="16"/></span></button></section><button class="outline-button wide" @click="member=false;go('me');notify('已退出会员体验')">退出会员体验</button></main>

  <main v-else-if="screen==='member'" class="member-screen"><section class="member-cover"><span class="overline">WELCOME TO YEJI CLUB</span><Icon name="leaf" :size="70"/><h1>把每一杯喜欢，<br>变成一份回馈。</h1><p>叶集会员 · 和好茶一起慢慢生长</p><button class="light-button" @click="member?go('points'):sheet='login'">{{ member?'查看我的叶子':'开启会员体验' }}<Icon name="arrow" :size="16"/></button></section><h2 class="center-title">属于你的日常小确幸</h2><div class="benefits-grid"><button @click="openCoupons"><Icon name="ticket" :size="30"/><h3>新朋友见面礼</h3><p>专属饮品优惠券</p></button><button @click="go('points')"><Icon name="leaf" :size="30"/><h3>每一杯攒叶子</h3><p>叶子兑换更多好礼</p></button><button @click="go('gift')"><Icon name="gift" :size="30"/><h3>心意随时送</h3><p>分享一杯好心情</p></button><button @click="go('shop')"><Icon name="star" :size="30"/><h3>新品尝鲜</h3><p>发现当季好味道</p></button></div></main>

  <main v-else-if="screen==='messages'" class="messages-screen"><button class="message-card" @click="openCoupons"><span class="message-icon"><Icon name="gift" :size="23"/></span><div><h3>一份见面礼，请查收<span>今天</span></h3><p>你的新朋友饮品券已放入账户，去挑一杯喜欢的吧。</p><small>查看好礼 <Icon name="arrow" :size="12"/></small></div></button><button v-for="o in orders.slice(0,5)" :key="o.id" class="message-card" @click="openOrder(o)"><span class="message-icon"><Icon name="cup" :size="23"/></span><div><h3>{{ orderStatus(o) }}<span>{{ o.code }}</span></h3><p>{{ stores.find(s=>s.id===o.storeId)?.name }} · {{ o.date }}</p><small>查看订单 <Icon name="arrow" :size="12"/></small></div></button><p class="fine-print">已展示全部消息 · 本机体验数据</p></main>

  <main v-else-if="screen==='gift'" class="gift-screen"><div class="gift-card"><span>YEJI · A GIFT OF TEA</span><Icon name="gift" :size="60"/><h1>想把一杯好心情，<br>送给你。</h1><p>{{ giftMessage }}</p><strong>¥{{ giftAmount }}</strong></div><template v-if="!giftSent"><section class="white-panel"><h3>选择心意</h3><div class="option-row"><button v-for="v in [30,50,100]" :key="v" :class="{selected:giftAmount===v}" @click="giftAmount=v">¥{{ v }}</button></div><label>送给谁<input v-model="giftRecipient" maxlength="20" placeholder="写下 TA 的称呼"></label><label>想说的话<textarea v-model="giftMessage" maxlength="80" rows="2"/></label></section><button class="solid-button wide" @click="sendGift">生成心意卡</button><p class="fine-print">仅预览心意卡，不发送消息，不产生付款。</p></template><section v-else class="gift-result"><Icon name="check" :size="35"/><h2>给 {{ giftRecipient }} 的心意，准备好了。</h2><p>这是一张界面预览卡，尚未购买或发送。</p><button class="outline-button" @click="giftSent=false">修改心意卡</button></section></main>

  <nav v-if="topLevel" class="bottom-tabs" aria-label="主导航"><button v-for="t in tabs" :key="t.id" :class="{active:screen===t.id}" @click="go(t.id)"><Icon :name="t.icon" :size="24"/><span>{{ t.name }}</span><i v-if="t.id==='orders'&&orders.some(o=>o.status==='ready')"></i></button></nav>
  <Transition name="toast"><div v-if="toast" class="toast-message" role="status"><Icon name="check" :size="17"/>{{ toast }}</div></Transition>

  <div v-if="sheet" class="sheet-overlay" @click.self="sheet=''"><section class="bottom-sheet" :class="{'product-sheet':sheet==='drink'}" role="dialog" aria-modal="true" :aria-label="sheet==='drink'?drink?.name:'操作面板'"><button class="sheet-close icon-button" aria-label="关闭弹层" @click="sheet=''"><Icon name="close" :size="21"/></button>
    <template v-if="sheet==='drink'&&drink"><div class="detail-art" :style="{background:drink.milk+'80'}"><span class="detail-overline">{{ drink.en }}</span><DrinkArt :color="drink.color" :milk="drink.milk" large/><span class="detail-art-caption">GOOD TEA, GOOD DAY.</span><button class="favorite-button" :class="{liked:favorites.includes(drink.id)}" aria-label="收藏饮品" @click="favorite(drink.id)"><Icon name="heart" :size="23"/></button></div><div class="product-sheet-body"><div class="product-title-row"><div><span class="product-tag">{{ drink.label||'每日好茶' }}</span><h2>{{ drink.name }}</h2></div><strong>¥{{ price(unit) }}</strong></div><p class="product-description">{{ drink.description }}</p><div class="nutrition"><span>约 {{ drink.kcal }} kcal / 标准杯</span><span>现点现做</span><span>甄选原叶茶</span></div><div class="options-group"><h3>杯型</h3><div class="option-row"><button v-for="v in ['标准杯','超大杯']" :key="v" :class="{selected:size===v}" @click="size=v">{{ v }}<small>{{ v==='标准杯'?'约 500ml':'约 650ml · +¥4' }}</small></button></div></div><div class="options-group"><h3>温度</h3><div class="option-row"><button v-for="v in ['正常冰','少冰','去冰','热']" :key="v" :class="{selected:temp===v}" @click="temp=v">{{ v }}</button></div></div><div class="options-group"><h3>甜度 <span>推荐甜，更能品味茶香</span></h3><div class="option-row"><button v-for="v in ['推荐甜','半糖','微糖','不另外加糖']" :key="v" :class="{selected:sugar===v}" @click="sugar=v">{{ v }}</button></div></div><div class="options-group"><h3>加点喜欢的 <span>可多选</span></h3><div class="option-row"><button v-for="v in ['白玉珍珠','椰果','轻芝士奶盖']" :key="v" :class="{selected:toppings.includes(v)}" @click="toggleTopping(v)">{{ v }}<small>+¥{{ v==='轻芝士奶盖'?3:2 }}</small></button></div></div></div><div class="product-action"><div class="quantity-control"><button aria-label="减少数量" :disabled="quantity<=1" @click="quantity--"><Icon name="minus" :size="16"/></button><strong>{{ quantity }}</strong><button aria-label="增加数量" :disabled="quantity>=99" @click="quantity++"><Icon name="plus" :size="16"/></button></div><button class="solid-button" @click="addDrink">加入购物袋 · ¥{{ price(unit*quantity) }}</button></div></template>
    <template v-else-if="sheet==='cart'"><h2>你的购物袋 <span class="subtle">{{ count }} 件</span></h2><p class="sheet-subtitle">{{ currentStore.name }}</p><div v-if="!count" class="empty-state"><Icon name="bag" :size="45"/><h3>装一杯喜欢的吧</h3><p>好茶现做，为你而来</p></div><div v-for="line in cart" :key="line.key" class="cart-line"><div class="cart-drink"><DrinkArt :color="findDrink(line.drinkId).color" :milk="findDrink(line.drinkId).milk"/></div><div class="cart-line-info"><h3>{{ findDrink(line.drinkId).name }}</h3><p>{{ description(line) }}</p><strong>¥{{ price(line.unit) }}</strong></div><div class="quantity-control"><button :aria-label="`减少${findDrink(line.drinkId).name}`" @click="adjust(line,-1)"><Icon name="minus" :size="13"/></button><span>{{ line.quantity }}</span><button :aria-label="`增加${findDrink(line.drinkId).name}`" @click="adjust(line,1)"><Icon name="plus" :size="13"/></button></div></div><button v-if="count" class="solid-button wide" @click="checkout">去结算 · ¥{{ price(subtotal) }}</button></template>
    <template v-else-if="sheet==='time'"><h2>{{ mode==='pickup'?'什么时候来取？':'什么时候送达？' }}</h2><p class="sheet-subtitle">为你留出刚刚好的时间</p><button v-for="v in ['尽快取餐','30 分钟后','60 分钟后','90 分钟后']" :key="v" class="selection-row" @click="pickupTime=v;sheet=''">{{ v==='尽快取餐'&&mode==='delivery'?'尽快送达':v }}<Icon v-if="pickupTime===v" name="check" :size="20"/></button></template>
    <template v-else-if="sheet==='note'"><h2>有什么想告诉我们？</h2><p class="sheet-subtitle">备注仅作为补充，口味请选择饮品规格</p><textarea v-model="noteDraft" maxlength="120" rows="4" placeholder="例如：分开打包、需要杯套…"/><div class="note-suggestions"><button v-for="v in ['需要杯套','分开打包','不需要吸管']" :key="v" @click="noteDraft=noteDraft?noteDraft+'，'+v:v">{{ v }}</button></div><button class="solid-button wide" @click="note=noteDraft;sheet=''">保存备注</button></template>
    <template v-else-if="sheet==='payment'"><h2>确认这份好心情</h2><p class="payment-amount"><small>¥</small>{{ price(total) }}</p><p class="sheet-subtitle centered">界面体验 · 不会产生实际扣款</p><button class="selection-row" @click="payment='wechat'"><span><span class="pay-icon">微</span>微信支付体验</span><span class="radio" :class="{checked:payment==='wechat'}"></span></button><button class="selection-row" @click="payment='balance'"><span><Icon name="wallet" :size="23"/>钱包余额 <small>¥{{ price(balance) }}</small></span><span class="radio" :class="{checked:payment==='balance'}"></span></button><button class="solid-button wide" :disabled="submitting" @click="placeOrder">确认体验下单</button></template>
    <template v-else-if="sheet==='address'"><h2>{{ addressDraft.id?'编辑地址':'新增收货地址' }}</h2><form @submit.prevent="saveAddress"><label>联系人<input v-model="addressDraft.name" maxlength="20" required placeholder="怎么称呼你"></label><label>手机号<input v-model="addressDraft.phone" type="tel" maxlength="11" required placeholder="11 位手机号码"></label><label>详细地址<textarea v-model="addressDraft.address" rows="2" maxlength="120" required placeholder="城市、街道、门牌号"></textarea></label><div class="option-row"><button v-for="v in ['家','公司','其他']" :key="v" type="button" :class="{selected:addressDraft.label===v}" @click="addressDraft.label=v">{{ v }}</button></div><button class="solid-button wide" type="submit">保存地址</button></form></template>
    <template v-else-if="sheet==='login'"><div class="login-leaf"><Icon name="leaf" :size="45"/></div><h2 class="centered">你好，叶集新朋友。</h2><p class="sheet-subtitle centered">以一杯好茶，开启我们的日常。</p><div class="welcome-benefit"><Icon name="ticket" :size="32"/><div><strong>¥6 新朋友见面礼</strong><small>满 20 元可用，体验账户已备好</small></div></div><label>你的称呼<input v-model="nickname" maxlength="20" placeholder="怎么称呼你"></label><button class="solid-button wide" @click="memberLogin">开启会员体验</button><p class="fine-print">使用本机演示身份，无需手机号验证，不创建真实账号。</p></template>
    <template v-else-if="sheet==='switch-store'"><h2>换一家门店逛逛？</h2><p class="sheet-subtitle">当前购物袋会保留在 {{ currentStore.name }}。切换后展示新门店的购物袋，商品不会混在一起。</p><button class="solid-button wide" @click="switchStore(pendingStore)">确认切换门店</button><button class="outline-button wide" @click="sheet=''">留在当前门店</button></template>
    <template v-else-if="sheet==='refund'"><h2>{{ activeOrder?.status==='refunding'?'售后进度':'我们认真对待每一杯' }}</h2><template v-if="activeOrder?.status==='refunding'"><div class="empty-state"><Icon name="clock" :size="40"/><h3>申请已收到，等待门店处理</h3><p>当前为本机演示，申请不会发送至实际门店。</p></div></template><template v-else><p class="sheet-subtitle">告诉我们遇到的问题，帮助我们做得更好。</p><textarea v-model="noteDraft" rows="4" maxlength="200" placeholder="请描述问题，例如饮品口味、包装…"/><button class="solid-button wide" @click="submitRefund">提交售后申请</button></template></template>
    <template v-else-if="sheet==='topup'"><h2>为下一杯，存一点期待。</h2><p class="sheet-subtitle">选择金额体验充值效果，不会收取真实费用。</p><div class="topup-grid"><button v-for="v in [30,50,100,200]" :key="v" @click="balance+=v;sheet='';notify('演示余额已增加 ¥'+v)"><strong>¥{{ v }}</strong><small>体验充值</small></button></div></template>
    <template v-else-if="sheet==='balance-history'"><h2>钱包明细</h2><p class="sheet-subtitle">当前余额 ¥{{ balance.toFixed(2) }}</p><div class="selection-row"><span>界面体验余额</span><strong>¥{{ balance.toFixed(2) }}</strong></div><p class="fine-print">此处仅展示本机余额状态，正式交易流水暂未接入。</p></template>
    <template v-else-if="sheet==='nickname'||sheet==='contact'"><h2>{{ sheet==='nickname'?'给自己一个好听的称呼':'取餐联系人' }}</h2><label>称呼<input v-model="nickname" maxlength="20" placeholder="怎么称呼你"></label><p v-if="sheet==='contact'" class="sheet-subtitle">演示手机号：138****8000。当前不采集或验证真实手机号。</p><button class="solid-button wide" @click="sheet='';notify('称呼已保存')">保存</button></template>
    <template v-else-if="sheet==='support'"><h2>叶集小助手</h2><div class="chat-bubble">你好呀，有什么可以帮你？你可以先看看常见问题，或写下想反馈的内容。</div><textarea v-model="noteDraft" rows="3" maxlength="200" placeholder="写下你的问题…"/><button class="solid-button wide" @click="noteDraft='';notify('已收到体验反馈，未向真实客服发送')">提交体验反馈</button><p class="fine-print">当前是客服交互演示，不会发送消息。</p></template>
    <template v-else-if="sheet==='privacy'"><h2>隐私与本机数据</h2><p class="sheet-subtitle">当前页面不请求业务后端。购物袋、地址、收藏和体验订单只保存在当前浏览器，可由浏览器清除网站数据。请不要在演示中填写敏感信息。</p><button class="solid-button wide" @click="sheet=''">我知道了</button></template>
    <template v-else><div class="login-leaf"><Icon name="leaf" :size="45"/></div><h2 class="centered">叶集 · 好茶，常相见。</h2><p class="sheet-subtitle">这是消费者端的独立界面体验版。商品、门店、会员权益与订单均为演示数据，下单、充值、送礼和售后不会产生真实交易，也不会通知门店。</p><p class="sheet-subtitle">你可以完整体验点单流程，所有操作仅保留在本机。正式业务接口将在界面确认后接入。</p><button class="solid-button wide" @click="sheet=''">开始逛逛</button></template>
  </section></div>
</div>
</template>
