package com.smartmerchant.saas.merchant.analytics.application;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.smartmerchant.saas.security.TenantContextHolder;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.sql.Timestamp;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import static org.springframework.http.HttpStatus.FORBIDDEN;

/** M5 read model. Events are immutable; aggregates are disposable accelerators rebuilt from facts. */
@Service
public class AnalyticsService {
  private final JdbcTemplate jdbc; private final ObjectMapper json;
  public AnalyticsService(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
  @Transactional public boolean ingest(AnalyticsEvent event){
    validate(event); String payload=write(event.payload());
    try { jdbc.update("INSERT INTO analytics_inbox(event_id,tenant_id,event_type,event_version,aggregate_id,occurred_at,payload_json) VALUES (?,?,?,?,?,?,?)",event.eventId(),event.tenantId(),event.eventType(),event.eventVersion(),event.aggregateId(),Timestamp.from(event.occurredAt()),payload); }
    catch(DuplicateKeyException duplicate){ return false; }
    switch(event.eventType()) { case "ORDER_PAID" -> paid(event); case "ORDER_REFUNDED" -> refunded(event); case "MEMBER_REGISTERED", "POINTS_CHANGED", "STORED_VALUE_CHANGED", "COUPON_CLAIMED", "COUPON_REDEEMED" -> member(event); default -> throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Unsupported analytics event type"); }
    return true;
  }
  private void paid(AnalyticsEvent e){
    Map<String,Object> p=e.payload(); long order=id(p,"orderId"), store=id(p,"storeId"), member=number(p,"memberId",0), amount=id(p,"paidAmountCents"), coupon=number(p,"couponDiscountCents",0);
    if(jdbc.queryForObject("SELECT COUNT(*) FROM analytics_order_fact WHERE tenant_id=? AND order_id=?",Long.class,e.tenantId(),order)>0) return;
    jdbc.update("INSERT INTO analytics_order_fact(tenant_id,order_id,store_id,member_id,paid_at,paid_amount_cents,coupon_discount_cents) VALUES (?,?,?,?,?,?,?)",e.tenantId(),order,store,member==0?null:member,Timestamp.from(e.occurredAt()),amount,coupon);
    for(Object raw: list(p,"items")){ Map<String,Object> item=map(raw); jdbc.update("INSERT INTO analytics_order_item_fact(tenant_id,order_id,line_no,store_id,sku_id,product_name,category_name,quantity,amount_cents,paid_at) VALUES (?,?,?,?,?,?,?,?,?,?)",e.tenantId(),order,(int)id(item,"lineNo"),store,id(item,"skuId"),text(item,"productName","未知商品"),text(item,"categoryName",null),id(item,"quantity"),id(item,"amountCents"),Timestamp.from(e.occurredAt())); }
    increment(e.tenantId(),store,e.occurredAt(),1,amount,0);
  }
  private void refunded(AnalyticsEvent e){ Map<String,Object> p=e.payload(); long order=id(p,"orderId"), amount=id(p,"refundAmountCents"); var row=jdbc.query("SELECT store_id,paid_at,refund_amount_cents FROM analytics_order_fact WHERE tenant_id=? AND order_id=?",rs->rs.next()?Map.of("store",rs.getLong(1),"time",rs.getTimestamp(2).toInstant(),"refund",rs.getLong(3)):null,e.tenantId(),order); if(row==null) throw new ResponseStatusException(HttpStatus.CONFLICT,"Refund arrived before its paid order"); long delta=Math.max(0,amount-(long)row.get("refund")); if(delta==0)return; jdbc.update("UPDATE analytics_order_fact SET refund_amount_cents=refund_amount_cents+? WHERE tenant_id=? AND order_id=?",delta,e.tenantId(),order); increment(e.tenantId(),(long)row.get("store"),e.occurredAt(),0,0,delta); }
  private void member(AnalyticsEvent e){Map<String,Object> p=e.payload();jdbc.update("INSERT INTO analytics_member_event_fact(event_id,tenant_id,member_id,event_type,points_delta,stored_value_delta_cents,occurred_at) VALUES (?,?,?,?,?,?,?)",e.eventId(),e.tenantId(),number(p,"memberId",0)==0?null:number(p,"memberId",0),e.eventType(),number(p,"pointsDelta",0),number(p,"storedValueDeltaCents",0),Timestamp.from(e.occurredAt()));}
  private void increment(long tenant,long store,Instant at,long orders,long gross,long refund){Instant minute=at.truncatedTo(ChronoUnit.MINUTES); LocalDate date=minute.atZone(ZoneOffset.UTC).toLocalDate(); upsert("analytics_metric_minute","metric_minute",Timestamp.from(minute),tenant,store,orders,gross,refund); upsert("analytics_metric_daily","metric_date",java.sql.Date.valueOf(date),tenant,store,orders,gross,refund);}
  private void upsert(String table,String timeCol,Object time,long tenant,long store,long orders,long gross,long refund){int updated=jdbc.update("UPDATE "+table+" SET paid_order_count=paid_order_count+?,gross_revenue_cents=gross_revenue_cents+?,refund_cents=refund_cents+? WHERE tenant_id=? AND store_id=? AND "+timeCol+"=?",orders,gross,refund,tenant,store,time);if(updated==0)jdbc.update("INSERT INTO "+table+"(tenant_id,store_id,"+timeCol+",paid_order_count,gross_revenue_cents,refund_cents) VALUES (?,?,?,?,?,?)",tenant,store,time,orders,gross,refund);}
  public Dashboard dashboard(LocalDate from,LocalDate to,Set<Long> stores){ long t=tenant(); if(from.isAfter(to))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"from must be before to"); if(stores==null||stores.isEmpty())stores=Set.of(-1L); String in=placeholders(stores); Object[] args=arguments(t,stores,Timestamp.valueOf(from.atStartOfDay()),Timestamp.valueOf(to.plusDays(1).atStartOfDay()));
    var summary=jdbc.queryForMap("SELECT COUNT(*) orders,COALESCE(SUM(paid_amount_cents),0) gross,COALESCE(SUM(LEAST(refund_amount_cents,paid_amount_cents)),0) refunds FROM analytics_order_fact WHERE tenant_id=? AND store_id IN ("+in+") AND paid_at>=? AND paid_at<?",args);
    long orders=num(summary,"orders"),gross=num(summary,"gross"),refund=num(summary,"refunds");
    var trend=jdbc.query("SELECT CAST(paid_at AS DATE) d,COUNT(*) orders,COALESCE(SUM(paid_amount_cents-LEAST(refund_amount_cents,paid_amount_cents)),0) net FROM analytics_order_fact WHERE tenant_id=? AND store_id IN ("+in+") AND paid_at>=? AND paid_at<? GROUP BY CAST(paid_at AS DATE) ORDER BY d",(rs,n)->new Trend(rs.getDate("d").toLocalDate(),rs.getLong("orders"),rs.getLong("net")),args);
    var ranking=jdbc.query("SELECT f.product_name name,COALESCE(c.category_name,f.category_name,'未分类') category,SUM(f.quantity) quantity,SUM(f.amount_cents) amount FROM analytics_order_item_fact f LEFT JOIN product_sku sku ON sku.tenant_id=f.tenant_id AND sku.id=f.sku_id LEFT JOIN product_spu spu ON spu.tenant_id=sku.tenant_id AND spu.id=sku.spu_id LEFT JOIN category c ON c.tenant_id=spu.tenant_id AND c.id=spu.category_id WHERE f.tenant_id=? AND f.store_id IN ("+in+") AND paid_at>=? AND paid_at<? GROUP BY f.product_name,COALESCE(c.category_name,f.category_name,'未分类') ORDER BY amount DESC LIMIT 10",(rs,n)->new ProductRank(rs.getString("name"),rs.getString("category"),rs.getLong("quantity"),rs.getLong("amount")),args);
    var comparisons=jdbc.query("SELECT store_id,COUNT(*) orders,COALESCE(SUM(paid_amount_cents-LEAST(refund_amount_cents,paid_amount_cents)),0) net FROM analytics_order_fact WHERE tenant_id=? AND store_id IN ("+in+") AND paid_at>=? AND paid_at<? GROUP BY store_id ORDER BY net DESC",(rs,n)->new StoreRank(rs.getLong("store_id"),rs.getLong("orders"),rs.getLong("net")),args);
    boolean tenantWide="TENANT_ALL".equals(TenantContextHolder.require().dataScope());
    long newMembers=tenantWide?jdbc.queryForObject("SELECT COUNT(*) FROM analytics_member_event_fact WHERE tenant_id=? AND event_type='MEMBER_REGISTERED' AND occurred_at>=? AND occurred_at<?",Long.class,t,Timestamp.valueOf(from.atStartOfDay()),Timestamp.valueOf(to.plusDays(1).atStartOfDay())):0;
    long repeats=jdbc.queryForObject("SELECT COUNT(*) FROM (SELECT member_id FROM analytics_order_fact WHERE tenant_id=? AND store_id IN ("+in+") AND member_id IS NOT NULL AND paid_at>=? AND paid_at<? GROUP BY member_id HAVING COUNT(*)>1) x",Long.class,args);
    long claimed=tenantWide?countMember(t,"COUPON_CLAIMED",from,to):0, redeemed=tenantWide?countMember(t,"COUPON_REDEEMED",from,to):0;
    return new Dashboard(new Summary(orders,gross,refund,gross-refund,orders==0?0:(gross-refund)/orders),trend,ranking,comparisons,new MemberMetrics(newMembers,repeats,claimed,redeemed,claimed==0?0:redeemed*10000/claimed)); }
  @Transactional public int reconcile(LocalDate date){long t=tenant(); var rows=jdbc.query("SELECT store_id,COUNT(*) orders,COALESCE(SUM(paid_amount_cents),0) gross,COALESCE(SUM(LEAST(refund_amount_cents,paid_amount_cents)),0) refunds FROM analytics_order_fact WHERE tenant_id=? AND paid_at>=? AND paid_at<? GROUP BY store_id",(rs,n)->new long[]{rs.getLong(1),rs.getLong(2),rs.getLong(3),rs.getLong(4)},t,Timestamp.valueOf(date.atStartOfDay()),Timestamp.valueOf(date.plusDays(1).atStartOfDay())); for(var r:rows){jdbc.update("DELETE FROM analytics_metric_daily WHERE tenant_id=? AND store_id=? AND metric_date=?",t,r[0],java.sql.Date.valueOf(date));jdbc.update("INSERT INTO analytics_metric_daily(tenant_id,store_id,metric_date,paid_order_count,gross_revenue_cents,refund_cents,reconciled_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP)",t,r[0],java.sql.Date.valueOf(date),r[1],r[2],r[3]);}return rows.size();}
  public PlatformSummary platformSummary(LocalDate from,LocalDate to){var c=TenantContextHolder.require();if(!c.platform())throw new ResponseStatusException(FORBIDDEN,"Merchant identity cannot read platform analytics");var r=jdbc.queryForMap("SELECT COUNT(DISTINCT tenant_id) tenants,COUNT(*) orders,COALESCE(SUM(paid_amount_cents),0) gross,COALESCE(SUM(LEAST(refund_amount_cents,paid_amount_cents)),0) refunds FROM analytics_order_fact WHERE paid_at>=? AND paid_at<?",Timestamp.valueOf(from.atStartOfDay()),Timestamp.valueOf(to.plusDays(1).atStartOfDay()));long gross=num(r,"gross"),refund=num(r,"refunds");return new PlatformSummary(num(r,"tenants"),num(r,"orders"),gross,refund,gross-refund);}
  private long countMember(long t,String type,LocalDate from,LocalDate to){return jdbc.queryForObject("SELECT COUNT(*) FROM analytics_member_event_fact WHERE tenant_id=? AND event_type=? AND occurred_at>=? AND occurred_at<?",Long.class,t,type,Timestamp.valueOf(from.atStartOfDay()),Timestamp.valueOf(to.plusDays(1).atStartOfDay()));}
  private static Dashboard empty(){return new Dashboard(new Summary(0,0,0,0,0),List.of(),List.of(),List.of(),new MemberMetrics(0,0,0,0,0));}
  private long tenant(){var c=TenantContextHolder.require();if(c.platform())throw new ResponseStatusException(FORBIDDEN,"Platform identity cannot read merchant analytics");return c.tenantId();}
  private static String placeholders(Set<Long>s){return String.join(",",Collections.nCopies(s.size(),"?"));} private static Object[] arguments(long t,Set<Long>s,Object... rest){var a=new ArrayList<Object>();a.add(t);a.addAll(s);a.addAll(Arrays.asList(rest));return a.toArray();}
  private static long id(Map<String,Object>m,String k){long v=number(m,k,-1);if(v<0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Missing event payload field: "+k);return v;} private static long number(Map<String,Object>m,String k,long d){Object v=m.get(k);return v instanceof Number n?n.longValue():v==null?d:Long.parseLong(v.toString());} private static String text(Map<String,Object>m,String k,String d){return m.get(k)==null?d:String.valueOf(m.get(k));} @SuppressWarnings("unchecked") private static Map<String,Object>map(Object v){return (Map<String,Object>)v;} @SuppressWarnings("unchecked") private static List<Object> list(Map<String,Object>m,String k){return (List<Object>)m.getOrDefault(k,List.of());} private static long num(Map<String,Object>m,String k){return ((Number)m.get(k)).longValue();} private String write(Map<String,Object>p){try{return json.writeValueAsString(p);}catch(JsonProcessingException e){throw new IllegalArgumentException(e);}} private static void validate(AnalyticsEvent e){if(e.eventId()==null||e.eventId().isBlank()||e.tenantId()<=0||e.eventVersion()<1||e.occurredAt()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid event envelope");}
  public record AnalyticsEvent(String eventId,String eventType,int eventVersion,long tenantId,String aggregateId,Instant occurredAt,Map<String,Object> payload){} public record Summary(long paidOrders,long grossRevenueCents,long refundCents,long netRevenueCents,long averageOrderCents){} public record Trend(LocalDate date,long orders,long netRevenueCents){} public record ProductRank(String productName,String categoryName,long quantity,long amountCents){} public record StoreRank(long storeId,long orders,long netRevenueCents){} public record MemberMetrics(long newMembers,long repeatMembers,long couponsClaimed,long couponsRedeemed,long couponRedemptionRateBasisPoints){} public record Dashboard(Summary summary,List<Trend> trend,List<ProductRank> products,List<StoreRank> stores,MemberMetrics members){}
  public record PlatformSummary(long activeTenants,long paidOrders,long grossRevenueCents,long refundCents,long netRevenueCents){}
}
