package com.smartmerchant.saas.iam.application;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.smartmerchant.saas.iam.domain.*; import com.smartmerchant.saas.iam.infrastructure.*; import com.smartmerchant.saas.security.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
import org.springframework.web.server.ResponseStatusException; import static org.springframework.http.HttpStatus.*;
@Service public class IamManagementService {
 private final StoreCredentialVault vault;private final UserAccountMapper users;private final TenantUserMapper members;private final RoleMapper roles;private final PermissionMapper permissions;private final PasswordEncoder encoder;private final JdbcTemplate jdbc;
 public IamManagementService(UserAccountMapper u,TenantUserMapper m,RoleMapper r,PermissionMapper p,PasswordEncoder e,JdbcTemplate j,StoreCredentialVault vault){this.vault=vault;users=u;members=m;roles=r;permissions=p;encoder=e;jdbc=j;}
 public Object platformMe(){if(!TenantContextHolder.require().platform())throw new ResponseStatusException(FORBIDDEN,"Platform identity is required");return me();}
 public Object me(){var c=TenantContextHolder.require();return Map.of("tenantId",Long.toString(c.tenantId()),"userId",Long.toString(c.userId()),"platform",c.platform(),"dataScope",c.dataScope(),"permissions",c.permissions());}
 public boolean usernameAvailable(String username){return users.selectCount(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username.trim()))==0;}
 public List<UserAccount> users(){return users.findByTenant(TenantContextHolder.requireTenantId());}
 public List<Role> roles(){return roles.selectList(Wrappers.<Role>lambdaQuery().eq(Role::getTenantId,TenantContextHolder.requireTenantId()).orderByAsc(Role::getRoleName));}
 public List<Permission> permissions(){return permissions.selectList(Wrappers.<Permission>lambdaQuery().eq(Permission::getAudience,TenantContextHolder.require().platform()?"PLATFORM":"MERCHANT"));}
 public List<Long> userRoleIds(long userId){long tenant=TenantContextHolder.requireTenantId();return jdbc.queryForList("SELECT role_id FROM user_role WHERE tenant_id=? AND user_id=?",Long.class,tenant,userId);}
 public List<Long> rolePermissionIds(long roleId){long tenant=TenantContextHolder.requireTenantId();return jdbc.queryForList("SELECT permission_id FROM role_permission WHERE tenant_id=? AND role_id=?",Long.class,tenant,roleId);}
 @Transactional public UserAccount createUser(String username,String password,String displayName,String mobile,String dataScope){return createForTenant(TenantContextHolder.requireTenantId(),username,password,displayName,mobile,"EMPLOYEE",dataScope);}
 @Transactional public UserAccount provisionOwner(long tenantId,String username,String password,String displayName,String mobile){var existing=users.selectOne(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username));if(existing!=null){var membership=members.selectOne(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenantId).eq(TenantUser::getUserId,existing.getId()));if(membership!=null)return existing;throw new IllegalStateException("Username already belongs to another account");}var user=createForTenant(tenantId,username,password,displayName,mobile,"OWNER","TENANT_ALL");var role=new Role();role.setId(Ids.next());role.setTenantId(tenantId);role.setRoleCode("OWNER");role.setRoleName("商户老板");role.setPlatformRole(false);role.setStatus("ACTIVE");role.setCreatedAt(LocalDateTime.now());role.setUpdatedAt(LocalDateTime.now());roles.insert(role);jdbc.update("INSERT INTO user_role(tenant_id,user_id,role_id) VALUES (?,?,?)",tenantId,user.getId(),role.getId());var merchantPermissions=permissions.selectList(Wrappers.<Permission>lambdaQuery().eq(Permission::getAudience,"MERCHANT"));for(var p:merchantPermissions)jdbc.update("INSERT INTO role_permission(tenant_id,role_id,permission_id) VALUES (?,?,?)",tenantId,role.getId(),p.getId());return user;}
 @Transactional public UserAccount provisionOwnerHash(long tenantId,String username,String passwordHash,String displayName,String mobile){var existing=users.selectOne(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username));if(existing!=null){var membership=members.selectOne(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenantId).eq(TenantUser::getUserId,existing.getId()));if(membership!=null)return existing;throw new ResponseStatusException(CONFLICT,"该手机号已是其他租户的登录账号，请更换负责人手机号");}var now=LocalDateTime.now();var user=new UserAccount();user.setId(Ids.next());user.setUsername(username);user.setPasswordHash(passwordHash);user.setDisplayName(displayName);user.setMobile(mobile);user.setStatus("ACTIVE");user.setTokenVersion(0);user.setCreatedAt(now);user.setUpdatedAt(now);users.insert(user);var member=new TenantUser();member.setId(Ids.next());member.setTenantId(tenantId);member.setUserId(user.getId());member.setMemberType("OWNER");member.setDataScope("TENANT_ALL");member.setStatus("ACTIVE");member.setCreatedAt(now);member.setUpdatedAt(now);members.insert(member);var role=new Role();role.setId(Ids.next());role.setTenantId(tenantId);role.setRoleCode("OWNER");role.setRoleName("商户老板");role.setPlatformRole(false);role.setStatus("ACTIVE");role.setCreatedAt(now);role.setUpdatedAt(now);roles.insert(role);jdbc.update("INSERT INTO user_role(tenant_id,user_id,role_id) VALUES (?,?,?)",tenantId,user.getId(),role.getId());for(var p:permissions.selectList(Wrappers.<Permission>lambdaQuery().eq(Permission::getAudience,"MERCHANT")))jdbc.update("INSERT INTO role_permission(tenant_id,role_id,permission_id) VALUES (?,?,?)",tenantId,role.getId(),p.getId());return user;}
 @Transactional public Role createRole(String code,String name){long tenant=TenantContextHolder.requireTenantId();var role=new Role();role.setId(Ids.next());role.setTenantId(tenant);role.setRoleCode(code);role.setRoleName(name);role.setPlatformRole(false);role.setStatus("ACTIVE");role.setCreatedAt(LocalDateTime.now());role.setUpdatedAt(LocalDateTime.now());roles.insert(role);return role;}
 @Transactional public void assignRoles(long userId,List<Long> roleIds){long tenant=TenantContextHolder.requireTenantId();jdbc.update("DELETE FROM user_role WHERE tenant_id=? AND user_id=?",tenant,userId);for(long roleId:roleIds){if(roles.selectCount(Wrappers.<Role>lambdaQuery().eq(Role::getTenantId,tenant).eq(Role::getId,roleId))!=1)throw new IllegalArgumentException("Role outside tenant");jdbc.update("INSERT INTO user_role(tenant_id,user_id,role_id) VALUES (?,?,?)",tenant,userId,roleId);}}
 @Transactional public void assignPermissions(long roleId,List<Long> permissionIds){long tenant=TenantContextHolder.requireTenantId();if(roles.selectCount(Wrappers.<Role>lambdaQuery().eq(Role::getTenantId,tenant).eq(Role::getId,roleId))!=1)throw new IllegalArgumentException("Role outside tenant");jdbc.update("DELETE FROM role_permission WHERE tenant_id=? AND role_id=?",tenant,roleId);for(long permissionId:permissionIds){if(permissions.selectById(permissionId)==null)throw new IllegalArgumentException("Unknown permission");jdbc.update("INSERT INTO role_permission(tenant_id,role_id,permission_id) VALUES (?,?,?)",tenant,roleId,permissionId);}}
 @Transactional public UserAccount provisionStoreAccount(long tenant,String username,String password,String displayName){return provisionStoreAccount(tenant,username,password,displayName,STORE_PERMISSIONS);}
 @Transactional public UserAccount provisionStoreAccount(long tenant,String username,String password,String displayName,List<String> requested){var user=users.selectOne(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username));if(user==null)user=createForTenant(tenant,username,password,displayName,null,"STORE_ACCOUNT","STORE_SELF");else{var membership=members.selectOne(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenant).eq(TenantUser::getUserId,user.getId()));if(membership==null)throw new ResponseStatusException(CONFLICT,"Username belongs to another tenant");if(!"STORE_ACCOUNT".equals(membership.getMemberType()))throw new ResponseStatusException(CONFLICT,"Username already belongs to another tenant account");membership.setDataScope("STORE_SELF");membership.setStatus("ACTIVE");membership.setUpdatedAt(LocalDateTime.now());members.updateById(membership);user.setPasswordHash(encoder.encode(password));user.setDisplayName(displayName);user.setStatus("ACTIVE");user.setTokenVersion(user.getTokenVersion()+1);user.setUpdatedAt(LocalDateTime.now());users.updateById(user);}updateStorePermissions(tenant,user.getId(),requested==null?STORE_PERMISSIONS:requested);vault.save(tenant,user.getId(),password);return user;}
 @Transactional public void resetStorePassword(long tenant,long userId,String password){var membership=members.selectOne(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenant).eq(TenantUser::getUserId,userId).eq(TenantUser::getMemberType,"STORE_ACCOUNT"));if(membership==null)throw new ResponseStatusException(NOT_FOUND,"Store account not found");var user=users.selectById(userId);user.setPasswordHash(encoder.encode(password));user.setTokenVersion(user.getTokenVersion()+1);user.setUpdatedAt(LocalDateTime.now());users.updateById(user);vault.save(tenant,userId,password);}

 @Transactional public UserAccount editStoreAccount(long tenant,long userId,String username,String displayName,String password,long operator){
  requireStoreMember(tenant,userId);
  var user=users.selectById(userId);
  if(users.selectCount(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username).ne(UserAccount::getId,userId))>0)throw new ResponseStatusException(CONFLICT,"登录账号已被使用");
  user.setUsername(username);user.setDisplayName(displayName);
  if(password!=null){if(password.length()<8||password.length()>64)throw new ResponseStatusException(BAD_REQUEST,"密码需为8至64位");user.setPasswordHash(encoder.encode(password));vault.save(tenant,userId,password);}
  user.setTokenVersion(user.getTokenVersion()+1);user.setUpdatedAt(LocalDateTime.now());users.updateById(user);vault.audit(tenant,userId,operator,"EDIT");return user;
 }
 private void requireStoreMember(long tenant,long userId){if(members.selectCount(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenant).eq(TenantUser::getUserId,userId).eq(TenantUser::getMemberType,"STORE_ACCOUNT"))!=1)throw new ResponseStatusException(NOT_FOUND,"门店账号不存在");}
 @Transactional public Map<String,Object> revealStorePassword(long tenant,long userId,long operator){requireStoreMember(tenant,userId);var password=vault.read(tenant,userId);if(password==null||!encoder.matches(password,users.selectById(userId).getPasswordHash()))return Map.of("available",false,"message","旧密码无法还原，请先重新设置一次密码");vault.audit(tenant,userId,operator,"REVEAL");return Map.of("available",true,"password",password);}
 public static final List<String> STORE_PERMISSIONS=List.of("merchant:store:view","merchant:product:view","merchant:inventory:view","merchant:inventory:manage","merchant:transfer:manage","merchant:order:view","merchant:order:verify","merchant:finance:view");
 public record StoreAccessAccount(long userId,String username,String displayName,List<String> permissions){}
 public List<StoreAccessAccount> storeAccessAccounts(long tenant,List<Long> userIds){
  if(userIds.isEmpty())return List.of();
  return members.selectList(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenant).eq(TenantUser::getDataScope,"STORE_SELF").eq(TenantUser::getStatus,"ACTIVE").in(TenantUser::getUserId,userIds)).stream().map(m->{var u=users.selectById(m.getUserId());return new StoreAccessAccount(u.getId(),u.getUsername(),u.getDisplayName(),permissions.findCodes(tenant,u.getId()).stream().distinct().sorted().toList());}).toList();
 }
 @Transactional public void updateStorePermissions(long tenant,long userId,List<String> requested){
  var member=members.selectOne(Wrappers.<TenantUser>lambdaQuery().eq(TenantUser::getTenantId,tenant).eq(TenantUser::getUserId,userId).eq(TenantUser::getDataScope,"STORE_SELF").eq(TenantUser::getStatus,"ACTIVE"));
  if(member==null)throw new ResponseStatusException(NOT_FOUND,"未找到该租户的本店账号");
  if(requested==null||!STORE_PERMISSIONS.containsAll(requested))throw new ResponseStatusException(BAD_REQUEST,"只能授予门店 ERP 功能权限");
  var codes=new LinkedHashSet<>(requested);codes.add("merchant:store:view");
  if(codes.contains("merchant:inventory:manage")||codes.contains("merchant:transfer:manage"))codes.add("merchant:inventory:view");
  if(codes.contains("merchant:inventory:view"))codes.add("merchant:product:view");
  if(codes.contains("merchant:order:verify"))codes.add("merchant:order:view");
  var available=permissions.selectList(Wrappers.<Permission>lambdaQuery().eq(Permission::getAudience,"MERCHANT").in(Permission::getPermissionCode,codes));
  if(available.size()!=codes.size())throw new ResponseStatusException(CONFLICT,"门店权限目录不完整，请联系系统管理员");
  var role=roles.selectOne(Wrappers.<Role>lambdaQuery().eq(Role::getTenantId,tenant).eq(Role::getRoleCode,"STORE_USER_"+userId));
  if(role==null){role=new Role();role.setId(Ids.next());role.setTenantId(tenant);role.setRoleCode("STORE_USER_"+userId);role.setRoleName("门店账号权限 · "+userId);role.setPlatformRole(false);role.setStatus("ACTIVE");role.setCreatedAt(LocalDateTime.now());role.setUpdatedAt(LocalDateTime.now());roles.insert(role);}
  jdbc.update("DELETE FROM role_permission WHERE tenant_id=? AND role_id=?",tenant,role.getId());
  for(var p:available)jdbc.update("INSERT INTO role_permission(tenant_id,role_id,permission_id) VALUES (?,?,?)",tenant,role.getId(),p.getId());
  jdbc.update("DELETE FROM user_role WHERE tenant_id=? AND user_id=?",tenant,userId);
  jdbc.update("INSERT INTO user_role(tenant_id,user_id,role_id) VALUES (?,?,?)",tenant,userId,role.getId());
 }
 private UserAccount createForTenant(long tenant,String username,String password,String name,String mobile,String type,String scope){if(users.selectCount(Wrappers.<UserAccount>lambdaQuery().eq(UserAccount::getUsername,username))>0)throw new IllegalArgumentException("Username already exists");var now=LocalDateTime.now();var u=new UserAccount();u.setId(Ids.next());u.setUsername(username);u.setPasswordHash(encoder.encode(password));u.setDisplayName(name);u.setMobile(mobile);u.setStatus("ACTIVE");u.setTokenVersion(0);u.setCreatedAt(now);u.setUpdatedAt(now);users.insert(u);var m=new TenantUser();m.setId(Ids.next());m.setTenantId(tenant);m.setUserId(u.getId());m.setMemberType(type);m.setDataScope(scope);m.setStatus("ACTIVE");m.setCreatedAt(now);m.setUpdatedAt(now);members.insert(m);return u;}
}

