<script setup lang="ts">
import LoginScreen from '../../../packages/ui/src/LoginScreen.vue'
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {api,auth,login,refresh} from '@smart-merchant/api'
import {ElMessage,ElMessageBox} from 'element-plus'
import OrdersRevenue from './components/OrdersRevenue.vue'
import SalesTrend from './components/SalesTrend.vue'
import StockTransfers from './components/StockTransfers.vue'
import LowStockNotice from '../../merchant-web/src/components/LowStockNotice.vue'
import {useStockAlerts} from '../../merchant-web/src/useStockAlerts'
import {type Order,type Store,money,dateText,localDate,exportCsv} from './model'
import '../../merchant-web/src/shell.css'
import '../../merchant-web/src/erp.css'
import './store.css'
type Sku={id:number;skuCode:string;skuName:string;barcode:string;status:string;basePriceCents:number}
type Product={spu:{productName:string;status:string};skus:{sku:Sku;sellable:boolean;effectivePriceCents:number}[]}
type Stock={lowStockThreshold:number;skuId:number;skuCode:string;skuName:string;productName:string;actualQuantity:number;availableQuantity:number;reservedQuantity:number}
type Ledger={id:number;skuId:number;skuCode:string;skuName:string;productName:string;operationType:string;quantityDelta:number;availableDelta:number;reservedDelta:number;quantityAfter:number;availableAfter:number;reservedAfter:number;businessId:number;reason:string;createdAt:string}
type Transfer={id:number;transferNo:string;sourceStoreId:number;targetStoreId:number;status:string;createdAt:string;remark:string;items?:{skuId:number;skuName:string;skuCode:string;quantity:number}[]}
type Count={positiveDifferenceQuantity:number;id:number;countNo:string;status:string;itemCount:number;differenceQuantity:number;createdAt:string;completedAt:string;remark:string}
const signedIn=ref(Boolean(auth.accessToken)),loading=ref(false),saving=ref(false),me=ref<any>(),store=ref<Store|null>(null),page=ref('overview'),revision=ref(0),updated=ref('')
const products=ref<Product[]>([]),stocks=ref<Stock[]>([]),orders=ref<Order[]>([]),ledgers=ref<Ledger[]>([]),transfers=ref<Transfer[]>([]),counts=ref<Count[]>([])
const errors=ref<string[]>([]),loaded=reactive({orders:false,products:false,inventory:false,ledger:false,transfers:false,counts:false})
const credentials=reactive({username:'',password:''})
const menus=[{id:'overview',icon:'◈',label:'经营总览',permission:''},{id:'inventory',icon:'▦',label:'商品与库存',permission:'merchant:inventory:view'},{id:'orders',icon:'▤',label:'销售订单',permission:'merchant:order:view'},{id:'ledger',icon:'⇄',label:'库存流水',permission:'merchant:inventory:view'},{id:'counts',icon:'▧',label:'库存盘点',permission:'merchant:inventory:view'},{id:'transfers',icon:'⇆',label:'调拨收发',permission:'merchant:inventory:view'},{id:'finance',icon:'¥',label:'财务流水',permission:'merchant:finance:view'}]
const can=(code:string)=>Boolean(me.value?.permissions?.includes(code))
const {alerts,alertError,alertUpdated,refreshAlerts}=useStockAlerts(()=>signedIn.value&&can('merchant:inventory:view')&&!!store.value)
const currentMenu=computed(()=>menus.find(x=>x.id===page.value)!)
const allowed=computed(()=>!currentMenu.value.permission||can(currentMenu.value.permission))
const missing=computed(()=>menus.filter(m=>m.permission&&!can(m.permission)).map(m=>m.label))
async function signIn(){if(loading.value||!credentials.username.trim()||!credentials.password)return;try{loading.value=true;await login(credentials.username,credentials.password);signedIn.value=true;await reload()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function syncPermissions(){try{loading.value=true;await refresh();await reload();if(signedIn.value)ElMessage.success("权限已同步")}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function reload(){loading.value=true;errors.value=[];try{me.value=await api('/api/merchant/v1/me');if(me.value.dataScope!=='STORE_SELF')throw new Error('请使用总部为门店配置的独立账号登录');const stores=await api<Store[]>('/api/merchant/v1/stores');if(stores.length!==1)throw new Error('当前账号未唯一绑定门店，请联系总部检查门店账号配置');store.value=stores[0];await reloadData()}catch(e){errors.value=[(e as Error).message];store.value=null;auth.clear();signedIn.value=false;ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function reloadData(){if(!store.value)return;loading.value=true;errors.value=[];const id=store.value.id
 const jobs=[{key:'orders',permission:'merchant:order:view',path:'/api/merchant/v1/orders',assign:(v:any)=>orders.value=v.filter((o:Order)=>o.storeId===id)},{key:'products',permission:'merchant:product:view',path:`/api/merchant/v1/products?storeId=${id}`,assign:(v:any)=>products.value=v},{key:'inventory',permission:'merchant:inventory:view',path:`/api/merchant/v1/inventory?storeId=${id}`,assign:(v:any)=>stocks.value=v},{key:'ledger',permission:'merchant:inventory:view',path:`/api/merchant/v1/inventory/ledger?storeId=${id}`,assign:(v:any)=>ledgers.value=v},{key:'counts',permission:'merchant:inventory:view',path:`/api/merchant/v1/stock-counts?storeId=${id}`,assign:(v:any)=>counts.value=v},{key:'transfers',permission:'merchant:inventory:view',path:'/api/merchant/v1/transfers',assign:(v:any)=>transfers.value=v.filter((t:Transfer)=>t.sourceStoreId===id||t.targetStoreId===id)}] as const
 await Promise.all(jobs.map(async j=>{loaded[j.key]=false;j.assign([]);if(!can(j.permission))return;try{j.assign(await api(j.path));loaded[j.key]=true}catch(e){errors.value.push(`${({orders:'订单',products:'商品',inventory:'库存',ledger:'库存流水',counts:'盘点',transfers:'调拨'})[j.key]}加载失败：${(e as Error).message}`)}}));updated.value=new Date().toLocaleString('zh-CN',{hour12:false});revision.value++;loading.value=false;void refreshAlerts()
}
function orderChanged(order:Order){orders.value=orders.value.map(o=>o.id===order.id?order:o);revision.value++}
function logout(){auth.clear();signedIn.value=false;store.value=null;orders.value=[];stocks.value=[];products.value=[];ledgers.value=[];transfers.value=[];counts.value=[]}
const query=ref(''),stockFilter=ref(''),current=ref(1),ledgerQuery=ref(''),operation=ref(''),ledgerDates=ref<[string,string]|null>(null)
watch([query,stockFilter,page],()=>current.value=1)
const catalog=computed(()=>products.value.flatMap(p=>p.skus.map(s=>({skuId:s.sku.id,skuCode:s.sku.skuCode,skuName:s.sku.skuName,productName:p.spu.productName,barcode:s.sku.barcode,price:s.effectivePriceCents,sellable:s.sellable&&p.spu.status==='ACTIVE'&&s.sku.status==='ACTIVE'}))))
const inventory=computed(()=>{const rows=catalog.value.filter(c=>c.sellable||stocks.value.some(s=>s.skuId===c.skuId)).map(c=>({...c,...(stocks.value.find(s=>s.skuId===c.skuId)??{actualQuantity:0,availableQuantity:0,reservedQuantity:0,lowStockThreshold:5})}));for(const s of stocks.value)if(!rows.some(r=>r.skuId===s.skuId))rows.push({...s,barcode:'',price:0,sellable:false});return rows})
const filteredStock=computed(()=>inventory.value.filter(s=>`${s.productName} ${s.skuName} ${s.skuCode} ${s.barcode??''}`.toLowerCase().includes(query.value.trim().toLowerCase())&&(!stockFilter.value||(stockFilter.value==='low'&&s.availableQuantity<=(s.lowStockThreshold??5))||(stockFilter.value==='out'&&s.availableQuantity===0)||(stockFilter.value==='healthy'&&s.availableQuantity>(s.lowStockThreshold??5)))))
const stockTotals=computed(()=>inventory.value.reduce((n,s)=>({actual:n.actual+s.actualQuantity,available:n.available+s.availableQuantity,reserved:n.reserved+s.reservedQuantity}),{actual:0,available:0,reserved:0}))
const lowStock=computed(()=>alerts.value)
const pending=computed(()=>orders.value.filter(o=>o.status==='PICKUP_READY'&&!o.directTransferId))
const period=ref('7'),end=new Date(),start=new Date();start.setDate(end.getDate()-6)
const dates=ref<[string,string]>([localDate(start),localDate(end)])
function setPeriod(v:string){period.value=v;const end=new Date(),start=new Date();start.setDate(end.getDate()-Number(v)+1);dates.value=[localDate(start),localDate(end)]}
const paid=computed(()=>orders.value.filter(o=>o.paidAt&&o.paidAt.slice(0,10)>=dates.value[0]&&o.paidAt.slice(0,10)<=dates.value[1]))
const paidAmount=computed(()=>paid.value.reduce((n,o)=>n+o.payableAmountCents,0)),refundAmount=computed(()=>paid.value.filter(o=>o.status==='REFUNDED').reduce((n,o)=>n+o.payableAmountCents,0))
const trend=computed(()=>{if(dates.value[0]===dates.value[1])return Array.from({length:24},(_,hour)=>{const rows=paid.value.filter(o=>Number(o.paidAt!.slice(11,13))===hour);return{label:`${hour}:00`,amount:rows.reduce((n,o)=>n+o.payableAmountCents,0),orders:rows.length}});const result=[];const d=new Date(dates.value[0]+'T00:00:00'),end=new Date(dates.value[1]+'T00:00:00');while(d<=end){const key=localDate(d),rows=paid.value.filter(o=>o.paidAt!.startsWith(key));result.push({label:key.slice(5),amount:rows.reduce((n,o)=>n+o.payableAmountCents,0),orders:rows.length});d.setDate(d.getDate()+1)}return result})
const topProducts=computed(()=>{const map=new Map<string,{name:string;quantity:number;amount:number}>();for(const o of paid.value.filter(o=>o.status!=='REFUNDED'))for(const item of o.items){const key=`${item.productName} ${item.skuName}`,p=map.get(key)??{name:key,quantity:0,amount:0};p.quantity+=item.quantity;p.amount+=item.lineAmountCents;map.set(key,p)}return [...map.values()].sort((a,b)=>b.amount-a.amount).slice(0,5)})
const opLabels:Record<string,string>={TENANT_ALLOCATION:'租户分配入库',ADJUSTMENT:'库存调整',RESERVE:'订单预占',RELEASE:'释放预占',DEDUCT_RESERVED:'销售出库',REFUND_RESTORE:'退款回补',ORDER_FULFILLMENT_UNDO:'直寄撤回原订单扣减',STOCK_COUNT:'盘点差异',TRANSFER_OUT:'调拨出库',TRANSFER_IN:'调拨入库'}
const filteredLedger=computed(()=>ledgers.value.filter(l=>(!operation.value||l.operationType===operation.value)&&`${l.productName} ${l.skuName} ${l.skuCode} ${l.businessId??''}`.includes(ledgerQuery.value.trim())&&(!ledgerDates.value||(l.createdAt.slice(0,10)>=ledgerDates.value[0]&&l.createdAt.slice(0,10)<=ledgerDates.value[1]))))
const ledgerPage=ref(1);watch([ledgerQuery,operation,ledgerDates],()=>ledgerPage.value=1,{deep:true})
function openLedger(skuCode:string){ledgerQuery.value=skuCode;operation.value='';ledgerDates.value=null;page.value='ledger'}
function exportStock(){exportCsv(`${store.value?.storeName}-库存.csv`,[['商品','规格','SKU','本店售价(元)','实际库存','可用库存','预占库存'],...filteredStock.value.map(s=>[s.productName,s.skuName,s.skuCode,(s.price/100).toFixed(2),s.actualQuantity,s.availableQuantity,s.reservedQuantity])])}
function exportLedger(){exportCsv(`${store.value?.storeName}-库存流水.csv`,[['时间','商品','规格','SKU','业务','实际变动','可用变动','预占变动','实际结余','业务单号','原因'],...filteredLedger.value.map(l=>[dateText(l.createdAt),l.productName,l.skuName,l.skuCode,opLabels[l.operationType]??l.operationType,l.quantityDelta,l.availableDelta,l.reservedDelta,l.quantityAfter,l.businessId??'',l.reason??''])])}
const adjustVisible=ref(false),adjustment=reactive({skuId:0,quantityDelta:-1,reason:'',key:''})
function openAdjust(skuId=0){Object.assign(adjustment,{skuId,quantityDelta:-1,reason:'',key:crypto.randomUUID()});adjustVisible.value=true}
async function adjust(){if(!store.value||!adjustment.skuId||!Number.isSafeInteger(adjustment.quantityDelta)||adjustment.quantityDelta>=0||!adjustment.reason.trim()){ElMessage.warning('请选择商品，填写负整数损耗数量和原因；补货由租户分配');return}try{await ElMessageBox.confirm(`确认${adjustment.quantityDelta>0?'增加':'扣减'} ${Math.abs(adjustment.quantityDelta)} 件库存？操作将保留流水。`,'确认库存调整',{confirmButtonText:'确认提交',cancelButtonText:'取消'});saving.value=true;await api(`/api/merchant/v1/inventory/${adjustment.skuId}/adjust`,{method:'POST',body:JSON.stringify({storeId:store.value.id,quantityDelta:adjustment.quantityDelta,reason:adjustment.reason.trim(),idempotencyKey:adjustment.key})});adjustVisible.value=false;await reloadData();ElMessage.success('库存已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
const countVisible=ref(false),countForm=reactive({countNo:'',skuId:0,countedQuantity:0,remark:''})
function openCount(){Object.assign(countForm,{countNo:`PC-${Date.now()}`,skuId:0,countedQuantity:0,remark:''});countVisible.value=true}
async function saveCount(){if(!store.value||!countForm.skuId||!countForm.countNo.trim()||!Number.isSafeInteger(countForm.countedQuantity)||countForm.countedQuantity<0){ElMessage.warning('请填写盘点单号、商品和非负整数实盘数量');return}try{saving.value=true;await api('/api/merchant/v1/stock-counts',{method:'POST',body:JSON.stringify({storeId:store.value.id,countNo:countForm.countNo.trim(),remark:countForm.remark,items:[{skuId:countForm.skuId,countedQuantity:countForm.countedQuantity}]})});countVisible.value=false;await reloadData();ElMessage.success('盘点单已保存，确认完成后更新库存')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function completeCount(row:Count){try{await ElMessageBox.confirm(`完成盘点单 ${row.countNo}，将按实盘差异更新本店库存。`,'确认完成盘点',{confirmButtonText:'完成盘点',cancelButtonText:'取消'});saving.value=true;await api(`/api/merchant/v1/stock-counts/${row.id}/complete`,{method:'POST'});await reloadData();ElMessage.success('盘点已完成')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
const countDetail=ref<any>(null)
async function showCount(row:Count){try{countDetail.value=await api(`/api/merchant/v1/stock-counts/${row.id}`)}catch(e){ElMessage.error((e as Error).message)}}
const verifyVisible=ref(false),verification=reactive({orderId:0,pickupCode:''})
async function verifyPickup(){if(!verification.orderId||!verification.pickupCode.trim()){ElMessage.warning('请选择订单并输入顾客自提码');return}try{saving.value=true;await api(`/api/merchant/v1/orders/${verification.orderId}/verify`,{method:'POST',body:JSON.stringify({pickupCode:verification.pickupCode.trim().toUpperCase()})});verifyVisible.value=false;Object.assign(verification,{orderId:0,pickupCode:''});await reloadData();ElMessage.success('核销成功，已记入本店流水')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
onMounted(()=>{if(signedIn.value)reload()})
</script>
<template>
<LoginScreen v-if="!signedIn" kind="store" v-model:username="credentials.username" v-model:password="credentials.password" :loading="loading" @submit="signIn"/>
<div v-else class="erp-shell store-erp"><aside class="sidebar"><div class="brand"><span class="brand-mark">S</span><div><strong>门店经营台</strong><small>STORE ERP WORKSPACE</small></div></div><div class="store-identity"><span>当前门店</span><b>{{store?.storeName??'正在加载'}}</b><small>{{store?.storeCode}}</small></div><section class="nav-group"><label>门店工作空间</label><button v-for="item in menus" :key="item.id" :class="{active:page===item.id}" @click="page=item.id"><i>{{item.icon}}</i>{{item.label}}<em v-if="item.permission&&!can(item.permission)">未授权</em></button></section><div class="account"><span>{{me?.displayName?.slice(0,1)??'店'}}</span><div><strong>{{me?.displayName??'门店账号'}}</strong><small>仅本店数据</small></div><button @click="logout">退出</button></div></aside>
<section class="workspace"><header class="topbar"><div class="store-breadcrumb">门店 ERP <span>/</span> {{currentMenu.label}}</div><div class="top-meta"><span class="scope-pill">● 本店专属</span><span class="refresh-note">更新于 {{updated||'—'}}</span><el-button :loading="loading" @click="syncPermissions">同步权限</el-button><el-button :loading="loading" @click="reloadData">刷新数据</el-button></div></header><div class="content" v-loading="loading"><LowStockNotice :scope-key="`store-web:${me?.tenantId}:${me?.userId}`" :alerts="alerts" :error="alertError" :updated="alertUpdated" @inventory="page='inventory';stockFilter='low';reloadData()" @refresh="refreshAlerts"/>
<el-alert v-if="errors.length" :title="errors.join('；')" type="error" show-icon :closable="false" class="load-alert"/>
<template v-if="!allowed"><div class="page-heading"><div><h1>{{currentMenu.label}}</h1><p>当前账号尚未开通此功能。</p></div></div><div class="panel"><el-empty description="请使用总部在「门店管理」配置的独立门店账号，或联系总部核对岗位权限。"/></div></template>
<template v-else-if="page==='overview'"><div class="page-heading"><div><div class="eyebrow">STORE PERFORMANCE</div><h1>经营总览 <span class="heading-badge">{{store?.storeName}}</span></h1><p>销售、库存与待办，掌握本店每一天的经营。</p></div><el-button v-if="can('merchant:order:verify')" type="primary" @click="verifyVisible=true">自提核销</el-button></div><el-alert v-if="missing.length" :title="`当前账号未开通：${missing.join('、')}。请在租户后台「门店管理 → 账号权限」授权，保存后点击「同步权限」。`" type="warning" :closable="false" show-icon/>
<div class="filter-bar"><div class="segmented"><button v-for="p in [['1','今日'],['7','近7天'],['30','近30天']]" :key="p[0]" :class="{selected:period===p[0]}" @click="setPeriod(p[0])">{{p[1]}}</button></div><span class="subtle">{{dates[0]}} 至 {{dates[1]}} · 按支付日期统计</span></div>
<section class="metric-grid"><article class="metric primary"><div>销售实收 <span>¥</span></div><strong>{{loaded.orders?money(paidAmount):'—'}}</strong><p>期间已支付订单现金金额</p></article><article class="metric"><div>支付订单 <span class="blue">▤</span></div><strong>{{loaded.orders?paid.length:'—'}} <small>笔</small></strong><p>实收客单价 {{loaded.orders?money(paid.length?paidAmount/paid.length:0):'—'}}</p></article><article class="metric"><div>退款 / 净实收 <span class="amber">↶</span></div><strong>{{loaded.orders?money(paidAmount-refundAmount):'—'}}</strong><p>关联已退款订单 {{loaded.orders?money(refundAmount):'—'}}</p></article><article class="metric"><div>可用库存 <span class="teal">▦</span></div><strong>{{loaded.inventory?stockTotals.available:'—'}} <small>件</small></strong><p>{{loaded.inventory?inventory.length:'—'}} 种 SKU · 预占 {{loaded.inventory?stockTotals.reserved:'—'}} 件</p></article></section>
<section class="chart-grid"><article class="panel"><div class="panel-heading"><div><h2>销售趋势</h2><p>{{period==='1'?'按小时':'按日'}}查看本店现金实收</p></div><span class="heading-badge">实收 / 元</span></div><SalesTrend v-if="loaded.orders" :rows="trend"/><el-empty v-else description="暂无可用订单数据"/><p v-if="loaded.orders&&!paid.length" class="chart-note">所选期间暂无已支付订单，曲线按零值展示</p></article><article class="panel"><div class="panel-heading"><div><h2>热销商品</h2><p>按商品原价排序 · 不含已退款订单</p></div></div><div v-for="(p,i) in topProducts" :key="p.name" class="rank-row"><span class="rank-number top">{{i+1}}</span><div><b>{{p.name}}</b><small>{{p.quantity}} 件</small></div><strong>{{money(p.amount)}}</strong></div><el-empty v-if="!topProducts.length" description="暂无商品销售数据" :image-size="75"/></article></section>
<section class="store-todos"><button @click="page='orders'"><span class="blue">▤</span><div><b>{{loaded.orders?pending.length:'—'}} 笔待自提</b><small>查看订单与核销 →</small></div></button><button @click="page='inventory';stockFilter='low'"><span class="amber">!</span><div><b>{{loaded.inventory?lowStock.length:'—'}} 项库存预警</b><small>查看低库存与缺货 →</small></div></button><button @click="page='transfers'"><span class="teal">⇆</span><div><b>{{loaded.transfers?transfers.filter(t=>(t.targetStoreId===store?.id&&t.status==='IN_TRANSIT')||(t.sourceStoreId===store?.id&&['REQUESTED','APPROVED'].includes(t.status))).length:'—'}} 笔调拨待处理</b><small>查看调拨收发 →</small></div></button></section>
<section class="chart-grid equal"><article class="panel"><div class="panel-heading"><h2>库存预警清单</h2><el-button link type="primary" @click="page='inventory'">全部库存 →</el-button></div><el-table :data="lowStock.slice(0,5)" :empty-text="loaded.inventory?'暂无库存预警':'库存数据尚不可用'"><el-table-column prop="productName" label="商品"/><el-table-column prop="skuName" label="规格"/><el-table-column label="可用库存"><template #default="s"><el-tag :type="s.row.availableQuantity===0?'danger':'warning'">{{s.row.availableQuantity}} 件</el-tag></template></el-table-column></el-table></article><article class="panel"><div class="panel-heading"><h2>本店档案</h2><el-tag :type="store?.status==='ACTIVE'?'success':'info'">{{store?.status==='ACTIVE'?'营业中':'已停用'}}</el-tag></div><dl class="store-profile"><div><dt>门店名称</dt><dd>{{store?.storeName}}</dd></div><div><dt>门店编码</dt><dd>{{store?.storeCode}}</dd></div><div><dt>详细地址</dt><dd>{{store?.address||'待总部完善'}}</dd></div><div><dt>营业时间</dt><dd>{{store?.businessHours||'待总部设置'}}</dd></div><div><dt>数据范围</dt><dd>仅当前门店，无跨店切换</dd></div></dl></article></section>
</template>
<template v-else-if="page==='inventory'"><div class="page-heading"><div><div class="eyebrow">PRODUCTS & STOCK</div><h1>商品与库存</h1><p>逐商品查看规格、售价、实际库存、可用库存与订单预占。</p></div><div class="heading-actions"><el-button :disabled="!loaded.inventory" @click="exportStock">导出库存</el-button><el-button v-if="can('merchant:inventory:manage')" type="primary" @click="openAdjust()">库存调整</el-button></div></div><section class="metric-grid"><article class="metric"><div>本店商品规格</div><strong>{{loaded.inventory?inventory.length:'—'}}</strong><p>可售商品及已有库存档案</p></article><article class="metric"><div>实际库存</div><strong>{{loaded.inventory?stockTotals.actual:'—'}}</strong></article><article class="metric"><div>订单预占</div><strong>{{loaded.inventory?stockTotals.reserved:'—'}}</strong></article><article class="metric"><div>缺货商品</div><strong>{{loaded.inventory?inventory.filter(s=>s.availableQuantity===0).length:'—'}}</strong></article></section><div class="panel"><div class="filter-bar compact"><el-input v-model="query" placeholder="商品名称 / 规格 / SKU / 条码" clearable/><el-select v-model="stockFilter" placeholder="全部库存状态" clearable><el-option label="低库存（含缺货）" value="low"/><el-option label="已缺货" value="out"/><el-option label="库存充足" value="healthy"/></el-select><span class="subtle">实际 = 可用 + 预占</span></div><el-table :data="filteredStock.slice((current-1)*10,current*10)" empty-text="本店暂无商品库存记录"><el-table-column label="商品 / SKU" min-width="200"><template #default="s"><div class="cell-stack"><b>{{s.row.productName}}</b><small>{{s.row.skuCode}} · {{s.row.barcode||'未设置条码'}}</small></div></template></el-table-column><el-table-column prop="skuName" label="规格" min-width="110"/><el-table-column label="本店售价" min-width="100"><template #default="s">{{loaded.products?money(s.row.price):'—'}}</template></el-table-column><el-table-column prop="actualQuantity" label="实际"/><el-table-column prop="availableQuantity" label="可用"/><el-table-column prop="reservedQuantity" label="预占"/><el-table-column label="库存状态" width="105"><template #default="s"><el-tag :type="s.row.availableQuantity===0?'danger':s.row.availableQuantity<=(s.row.lowStockThreshold??5)?'warning':'success'">{{s.row.availableQuantity===0?'已缺货':s.row.availableQuantity<=(s.row.lowStockThreshold??5)?'低库存':'充足'}}</el-tag></template></el-table-column><el-table-column label="销售状态" width="95"><template #default="s">{{s.row.sellable?'可售':'不可售'}}</template></el-table-column><el-table-column label="操作" width="120" fixed="right"><template #default="s"><el-button link type="primary" @click="openLedger(s.row.skuCode)">流水</el-button><el-button v-if="can('merchant:inventory:manage')" link type="primary" @click="openAdjust(s.row.skuId)">调整</el-button></template></el-table-column></el-table><div class="pagination"><span>共 {{filteredStock.length}} 种规格</span><el-pagination v-model:current-page="current" :page-size="10" :total="filteredStock.length" layout="prev,pager,next"/></div></div></template>
<template v-else-if="page==='orders'||page==='finance'"><div v-if="page==='orders'&&can('merchant:order:verify')" class="verify-strip"><div><b>自提核销</b><span>{{pending.length}} 笔订单等待顾客到店，请核对顾客出示的自提码。</span></div><el-button type="primary" @click="verifyVisible=true">打开核销台</el-button></div><OrdersRevenue v-if="store&&(page==='finance'||loaded.orders)" :key="page" :store-id="store.id" :stores="[store]" :orders="orders" :revision="revision" :finance-allowed="can('merchant:finance:view')" :refund-allowed="can('merchant:order:refund')" :ship-allowed="can('merchant:order:verify')" @changed="orderChanged" :view="page==='finance'?'finance':'orders'"/><el-empty v-else description="订单数据尚未加载成功，请刷新重试"/></template>
<template v-else-if="page==='ledger'"><div class="page-heading"><div><div class="eyebrow">INVENTORY MOVEMENTS</div><h1>库存流水</h1><p>追踪入库、销售出库、预占释放、退款回补与盘点差异。</p></div><el-button :disabled="!loaded.ledger" @click="exportLedger">导出流水</el-button></div><div class="panel"><div class="filter-bar compact"><el-input v-model="ledgerQuery" placeholder="商品 / SKU / 业务单号" clearable/><el-select v-model="operation" placeholder="全部业务类型" clearable><el-option v-for="(label,key) in opLabels" :key="key" :value="key" :label="label"/></el-select><el-date-picker v-model="ledgerDates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/></div><el-table :data="filteredLedger.slice((ledgerPage-1)*15,ledgerPage*15)" empty-text="暂无匹配的库存流水"><el-table-column label="发生时间" min-width="165"><template #default="s">{{dateText(s.row.createdAt)}}</template></el-table-column><el-table-column label="商品 / 规格" min-width="180"><template #default="s"><div class="cell-stack"><b>{{s.row.productName}}</b><small>{{s.row.skuName}} · {{s.row.skuCode}}</small></div></template></el-table-column><el-table-column label="业务类型" width="110"><template #default="s">{{opLabels[s.row.operationType]??s.row.operationType}}</template></el-table-column><el-table-column label="实际变动" width="95"><template #default="s"><b :class="s.row.quantityDelta>0?'positive':'negative'">{{s.row.quantityDelta>0?'+':''}}{{s.row.quantityDelta}}</b></template></el-table-column><el-table-column prop="availableDelta" label="可用变动" width="95"/><el-table-column prop="reservedDelta" label="预占变动" width="95"/><el-table-column prop="quantityAfter" label="实际结余" width="95"/><el-table-column prop="reason" label="原因 / 备注" min-width="140"/><el-table-column prop="businessId" label="业务单号" min-width="170"/></el-table><div class="pagination"><span>共 {{filteredLedger.length}} 条流水</span><el-pagination v-model:current-page="ledgerPage" :page-size="15" :total="filteredLedger.length" layout="prev,pager,next"/></div></div></template>
<template v-else-if="page==='counts'"><div class="page-heading"><div><div class="eyebrow">STOCKTAKING</div><h1>库存盘点</h1><p>登记实盘数量，核对差异后确认入账，保留盘点记录。</p></div><el-button v-if="can('merchant:inventory:manage')" type="primary" @click="openCount">新建盘点单</el-button></div><div class="panel"><el-table :data="counts" empty-text="暂无盘点记录"><el-table-column prop="countNo" label="盘点单号" min-width="190"/><el-table-column prop="itemCount" label="商品规格数"/><el-table-column prop="differenceQuantity" label="差异绝对数量"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.status==='COMPLETED'?'success':'warning'">{{s.row.status==='COMPLETED'?'已完成':s.row.positiveDifferenceQuantity?'盘盈待租户确认':'待确认'}}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="165"><template #default="s">{{dateText(s.row.createdAt)}}</template></el-table-column><el-table-column label="操作" min-width="170"><template #default="s"><el-button link type="primary" @click="showCount(s.row)">详情</el-button><el-button v-if="s.row.status==='DRAFT'&&!s.row.positiveDifferenceQuantity&&can('merchant:inventory:manage')" link type="primary" :disabled="saving" @click="completeCount(s.row)">完成盘点</el-button></template></el-table-column></el-table></div></template>
<StockTransfers v-else-if="page==='transfers'&&store" :store="store" :transfers="transfers" :can-manage="can('merchant:transfer:manage')" :can-orders="can('merchant:order:view')" @changed="reloadData"/>
</div></section>
<el-drawer v-model="adjustVisible" title="库存调整" size="min(480px,100vw)"><el-form label-position="top"><el-form-item label="商品规格"><el-select v-model="adjustment.skuId" filterable><el-option v-for="s in inventory" :key="s.skuId" :label="`${s.productName} / ${s.skuName} (${s.skuCode})`" :value="s.skuId"/></el-select></el-form-item><el-form-item label="损耗数量（填写负数）"><el-input-number v-model="adjustment.quantityDelta" :max="-1" :precision="0"/></el-form-item><el-form-item label="调整原因"><el-input v-model="adjustment.reason" type="textarea" :rows="3" placeholder="填写报损等原因；新增入库由租户分配"/></el-form-item></el-form><p class="subtle">补货入库由租户统一分配。损耗仅影响当前门店，已被订单预占的库存不能扣减。</p><template #footer><el-button @click="adjustVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="adjust">提交调整</el-button></template></el-drawer>
<el-drawer v-model="countVisible" title="新建盘点单" size="min(480px,100vw)"><el-form label-position="top"><el-form-item label="盘点单号"><el-input v-model="countForm.countNo"/></el-form-item><el-form-item label="商品规格"><el-select v-model="countForm.skuId" filterable><el-option v-for="s in inventory" :key="s.skuId" :label="`${s.productName} / ${s.skuName}`" :value="s.skuId"/></el-select></el-form-item><el-form-item label="实盘数量"><el-input-number v-model="countForm.countedQuantity" :min="0" :precision="0"/></el-form-item><el-form-item label="盘点备注"><el-input v-model="countForm.remark" type="textarea"/></el-form-item></el-form><template #footer><el-button type="primary" :loading="saving" @click="saveCount">保存待确认盘点单</el-button></template></el-drawer>
<el-drawer v-model="verifyVisible" title="自提订单核销" size="min(480px,100vw)" @closed="verification.pickupCode=''"><el-form label-position="top"><el-form-item label="待核销订单"><el-select v-model="verification.orderId" filterable><el-option v-for="o in pending" :key="o.id" :label="`${o.orderNo} · ${o.customerName} · ${money(o.payableAmountCents)}`" :value="o.id"/></el-select></el-form-item><el-form-item label="顾客自提码"><el-input v-model="verification.pickupCode" maxlength="10" placeholder="输入顾客出示的自提码" @keyup.enter="verifyPickup"/></el-form-item></el-form><el-alert title="核对商品及顾客自提码后再确认；核销成功会记入本店经营流水。" type="info" :closable="false"/><template #footer><el-button type="primary" :loading="saving" @click="verifyPickup">确认核销</el-button></template></el-drawer>
<el-drawer :model-value="Boolean(countDetail)" title="盘点明细" size="min(640px,100vw)" @close="countDetail=null"><template v-if="countDetail"><h3>{{countDetail.countNo}}</h3><el-table :data="countDetail.items"><el-table-column prop="skuName" label="商品规格"/><el-table-column prop="expectedQuantity" label="账面数量"/><el-table-column prop="countedQuantity" label="实盘数量"/><el-table-column prop="differenceQuantity" label="差异"/></el-table><p class="subtle">{{countDetail.remark||'无备注'}}</p></template></el-drawer>
</div>
</template>
