package com.smartmerchant.saas.member.interfaces;
import com.smartmerchant.saas.security.ConsumerIdentity;import com.smartmerchant.saas.member.application.MemberBenefitService;import com.smartmerchant.saas.security.TenantContextHolder;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.LocalDateTime;
@RestController public class MemberController {private final MemberBenefitService service;public MemberController(MemberBenefitService service){this.service=service;}
 @GetMapping("/api/merchant/v1/members") @PreAuthorize("hasAuthority('merchant:member:view')") public Object members(){return service.members();}
 @PostMapping("/api/merchant/v1/members/{id}/points") @PreAuthorize("hasAuthority('merchant:member:manage')") public Object points(@PathVariable long id,@Valid @RequestBody Adjust r){return service.adjustPoints(id,r.delta(),r.requestId());}
 @PostMapping("/api/merchant/v1/members/{id}/stored-value") @PreAuthorize("hasAuthority('merchant:member:manage')") public Object stored(@PathVariable long id,@Valid @RequestBody Adjust r){return service.adjustStoredValue(id,r.delta(),r.requestId());}
 @GetMapping("/api/merchant/v1/coupon-templates") @PreAuthorize("hasAuthority('merchant:coupon:view')") public Object templates(){return service.templates();}
 @PostMapping("/api/merchant/v1/coupon-templates") @PreAuthorize("hasAuthority('merchant:coupon:manage')") public Object template(@Valid @RequestBody Template r){return service.createTemplate(r.templateCode(),r.templateName(),r.discountCents(),r.minSpendCents(),r.totalQuantity(),r.validFrom(),r.validTo());}
 @PutMapping("/api/merchant/v1/coupon-templates/{id}/status") @PreAuthorize("hasAuthority('merchant:coupon:manage')") public Object status(@PathVariable long id,@Valid @RequestBody Status r){return service.changeTemplateStatus(id,r.status(),r.version());}
 @PutMapping("/api/merchant/v1/coupon-templates/{id}") @PreAuthorize("hasAuthority('merchant:coupon:manage')") public Object edit(@PathVariable long id,@Valid @RequestBody EditTemplate r){return service.editTemplate(id,r.templateName(),r.discountCents(),r.minSpendCents(),r.totalQuantity(),r.validFrom(),r.validTo(),r.version());}
 public record Status(@Pattern(regexp="ACTIVE|PAUSED") @NotNull String status,@PositiveOrZero long version){}
 public record EditTemplate(@NotBlank String templateName,@Positive long discountCents,@PositiveOrZero long minSpendCents,@Positive long totalQuantity,@NotNull LocalDateTime validFrom,@NotNull LocalDateTime validTo,@PositiveOrZero long version){}
 @PostMapping("/api/consumer/v1/members") public Object consumerRegister(@Valid @RequestBody ConsumerRegister r){ConsumerIdentity.require().check(r.tenantId(),r.mobile());return service.get(r.tenantId(),r.mobile());}
 @GetMapping("/api/consumer/v1/members") public Object consumerGet(@RequestParam long tenantId,@RequestParam String mobile){ConsumerIdentity.require().check(tenantId,mobile);return service.get(tenantId,mobile);}
 @PostMapping("/api/consumer/v1/coupons/{templateId}/claim") public Object claim(@PathVariable long templateId,@Valid @RequestBody Claim r){ConsumerIdentity.require().check(r.tenantId(),r.mobile());return service.claim(r.tenantId(),templateId,r.mobile(),r.requestId());}
 public record Register(@NotBlank String mobile,@NotBlank String memberName){}public record ConsumerRegister(@Positive long tenantId,@NotBlank String mobile,@NotBlank String memberName){}public record Adjust(long delta,@NotBlank String requestId){}public record Template(@NotBlank String templateCode,@NotBlank String templateName,@Positive long discountCents,@PositiveOrZero long minSpendCents,@Positive long totalQuantity,@NotNull LocalDateTime validFrom,@NotNull LocalDateTime validTo){}public record Claim(@Positive long tenantId,@NotBlank String mobile,@NotBlank String requestId){}
}