<script setup lang="ts">
defineEmits<{changed:[]}>()
import { onMounted, ref } from 'vue'
import StorefrontSettings from './StorefrontSettings.vue'
import { api } from '@smart-merchant/api'
import { ElMessage } from 'element-plus'
type Settings = { tenantId: string; displayName: string; logoUrl: string; themeColor: string; headline: string; contactPhone: string; version: number }
const settings = ref<Settings | null>(null), busy = ref(false), error = ref('')
type Feedback = { id:string;name:string;content:string;status:string;createdAt:string }
const feedback=ref<Feedback[]>([]), feedbackPage=ref(0), feedbackMore=ref(false), feedbackBusy=ref(false), feedbackError=ref('')
async function loadFeedback(more=false){feedbackBusy.value=true;feedbackError.value='';try{const page=more?feedbackPage.value+1:0;const rows=await api<Feedback[]>(`/api/merchant/v1/consumer-feedback?page=${page}`);feedback.value=more?[...feedback.value,...rows]:rows;feedbackPage.value=page;feedbackMore.value=rows.length===20}catch(e){feedbackError.value=(e as Error).message}finally{feedbackBusy.value=false}}
async function resolveFeedback(row:Feedback){feedbackBusy.value=true;try{await api(`/api/merchant/v1/consumer-feedback/${row.id}/resolve`,{method:'POST',body:'{}'});row.status='RESOLVED';ElMessage.success('反馈已标记处理')}catch(e){feedbackError.value=(e as Error).message}finally{feedbackBusy.value=false}}
async function load() { busy.value = true; try { settings.value = await api('/api/merchant/v1/consumer-settings'); error.value = '' } catch (e) { error.value = (e as Error).message } finally { busy.value = false } }
async function submit() { if (!settings.value || busy.value) return; busy.value = true; try { settings.value = await api('/api/merchant/v1/consumer-settings', { method: 'PUT', body: JSON.stringify(settings.value) }); ElMessage.success('消费者商城配置已保存') } catch (e) { error.value = (e as Error).message } finally { busy.value = false } }
onMounted(load)
</script>
<template><div class="page-heading"><div><div class="eyebrow">CONSUMER STOREFRONT</div><h1>消费者商城</h1><p>配置品牌 H5 的展示信息，保存后对消费者生效。</p></div><el-button @click="load">刷新</el-button></div><section class="panel" v-loading="busy"><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form v-if="settings" label-position="top" style="max-width:640px" @submit.prevent="submit"><el-form-item label="品牌展示名称"><el-input v-model="settings.displayName" maxlength="128"/></el-form-item><el-form-item label="Logo 图片地址"><el-input v-model="settings.logoUrl" placeholder="https://…（留空使用文字标识）"/></el-form-item><el-form-item label="品牌主题色"><el-color-picker v-model="settings.themeColor"/></el-form-item><el-form-item label="首页标题"><el-input v-model="settings.headline" maxlength="80"/></el-form-item><el-form-item label="客服电话"><el-input v-model="settings.contactPhone" maxlength="32"/></el-form-item><el-form-item label="消费者入口参数"><el-input :model-value="`/?tenantId=${settings.tenantId}`" readonly/><p>这是 H5 链接的参数，tenantId 是当前商家的唯一编号，用于识别品牌，并非门店地址。每家门店的地址、营业时间和配送方式，请在下方选择对应门店后独立配置。</p></el-form-item><el-button type="primary" native-type="submit" :loading="busy">保存配置</el-button></el-form></section><StorefrontSettings @changed="$emit('changed')"/><section class="panel" style="margin-top:20px" v-loading="feedbackBusy"><div class="page-heading"><div><h2>消费者反馈</h2><p>来自 H5 的会员反馈；订单退款在订单详情处理。</p></div><el-button :disabled="feedbackBusy" @click="loadFeedback(false)">加载 / 刷新反馈</el-button></div><el-alert v-if="feedbackError" :title="feedbackError" type="error" :closable="false"/><el-table :data="feedback"><el-table-column prop="name" label="会员" width="120"/><el-table-column prop="content" label="反馈内容"/><el-table-column prop="createdAt" label="提交时间" width="180"/><el-table-column label="处理" width="120"><template #default="{row}"><el-button v-if="row.status==='PENDING'" :disabled="feedbackBusy" @click="resolveFeedback(row)">标记已处理</el-button><span v-else>已处理</span></template></el-table-column></el-table><el-button v-if="feedbackMore" :disabled="feedbackBusy" @click="loadFeedback(true)">加载更多</el-button></section></template>
