<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { api } from '@smart-merchant/api'
import { ElMessage, ElMessageBox } from 'element-plus'
import { money, dateText } from '../model'
const props=defineProps<{permissions:string[]}>()
const can=(code:string)=>props.permissions.includes(code)
type Member={id:number;mobile:string;memberName:string;levelCode:string;status:string;availablePoints:number;storedValueCents:number;createdAt:string}
type Coupon={id:number;templateCode:string;templateName:string;discountCents:number;minSpendCents:number;totalQuantity:number;claimedQuantity:number;redeemedQuantity:number;status:string;validFrom:string;validTo:string;version:number}
const members=ref<Member[]>([]),coupons=ref<Coupon[]>([]),tab=ref(can('merchant:member:view')?'members':'coupons'),keyword=ref(''),couponFilter=ref(''),current=ref(1),busy=ref(false),saving=ref(false),error=ref(''),visible=ref(false),editing=ref<Coupon|null>(null)
const form=reactive({templateCode:'',templateName:'',discount:10,minSpend:100,totalQuantity:100,validFrom:'',validTo:''})
async function reload(){busy.value=true;error.value='';try{const [m,c]=await Promise.all([can('merchant:member:view')?api<Member[]>('/api/merchant/v1/members'):Promise.resolve([]),can('merchant:coupon:view')?api<Coupon[]>('/api/merchant/v1/coupon-templates'):Promise.resolve([])]);members.value=m;coupons.value=c}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
const filteredMembers=computed(()=>members.value.filter(m=>`${m.memberName} ${m.mobile}`.includes(keyword.value.trim())))
const memberRows=computed(()=>filteredMembers.value.slice((current.value-1)*10,current.value*10))
watch([keyword,tab],()=>current.value=1)
function couponState(c:Coupon){if(c.status==='DRAFT')return '草稿';if(new Date(c.validTo)<=new Date())return '已过期';if(c.claimedQuantity>=c.totalQuantity)return '已领完';if(c.status==='PAUSED')return '已暂停';if(new Date(c.validFrom)>new Date())return '待生效';return '领取中'}
const filteredCoupons=computed(()=>coupons.value.filter(c=>(!couponFilter.value||couponState(c)===couponFilter.value)&&`${c.templateCode} ${c.templateName}`.includes(keyword.value.trim())))
function open(c?:Coupon){editing.value=c??null;Object.assign(form,c?{templateCode:c.templateCode,templateName:c.templateName,discount:c.discountCents/100,minSpend:c.minSpendCents/100,totalQuantity:c.totalQuantity,validFrom:c.validFrom,validTo:c.validTo}:{templateCode:'',templateName:'',discount:10,minSpend:100,totalQuantity:100,validFrom:'',validTo:''});visible.value=true}
async function save(){
  if(!form.templateCode.trim()||!form.templateName.trim()){ElMessage.warning('请填写优惠券编码和名称');return}
  if(!form.validFrom||!form.validTo||new Date(form.validTo)<=new Date(form.validFrom)||new Date(form.validTo)<=new Date()){ElMessage.warning('结束时间须晚于开始时间和当前时间');return}
  if(!Number.isFinite(form.discount)||form.discount<=0||!Number.isFinite(form.minSpend)||form.minSpend<0||!Number.isSafeInteger(form.totalQuantity)||form.totalQuantity<1||(form.minSpend>0&&form.discount>form.minSpend)){ElMessage.warning('请检查面额、使用门槛和发行数量；满减券面额不能超过门槛');return}
  saving.value=true
  try{await api(editing.value?`/api/merchant/v1/coupon-templates/${editing.value.id}`:'/api/merchant/v1/coupon-templates',{method:editing.value?'PUT':'POST',body:JSON.stringify({templateCode:form.templateCode.trim(),templateName:form.templateName.trim(),discountCents:Math.round(form.discount*100),minSpendCents:Math.round(form.minSpend*100),totalQuantity:form.totalQuantity,validFrom:form.validFrom,validTo:form.validTo,version:editing.value?.version})});visible.value=false;ElMessage.success('草稿已保存，发布后消费者才能领取');await reload()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}
}
async function changeStatus(c:Coupon){
  const pause=c.status==='ACTIVE'
  try{await ElMessageBox.confirm(pause?`暂停「${c.templateName}」的新领取？已领取的优惠券仍可在有效期内使用。`:`发布「${c.templateName}」？${formDescription(c)}，共 ${c.totalQuantity} 张，每位会员限领 1 张；有效期 ${dateText(c.validFrom)} 至 ${dateText(c.validTo)}。发布后规则不可修改。`,pause?'暂停领取':'确认发布',{type:pause?'warning':'info',confirmButtonText:pause?'暂停领取':'确认发布',cancelButtonText:'返回检查'});saving.value=true;await api(`/api/merchant/v1/coupon-templates/${c.id}/status`,{method:'PUT',body:JSON.stringify({status:pause?'PAUSED':'ACTIVE',version:c.version})});ElMessage.success(pause?'已暂停新领取':'优惠券已发布');await reload()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}
}
function formDescription(c:Coupon){return c.minSpendCents?`满 ${money(c.minSpendCents)} 减 ${money(c.discountCents)}`:`无门槛减 ${money(c.discountCents)}`}
async function adjust(m:Member,kind:'points'|'stored-value'){
  const points=kind==='points'
  try{const {value}=await ElMessageBox.prompt(`输入${points?'积分整数':'金额（元，最多两位小数）'}，正数增加、负数扣减。当前余额：${points?m.availablePoints:money(m.storedValueCents)}。调整将保留流水。`,`调整 ${m.memberName} 的${points?'积分':'储值'}`,{inputPattern:points?/^-?\d+$/:/^-?\d+(\.\d{1,2})?$/,inputErrorMessage:'请输入正确的调整值',confirmButtonText:'下一步',cancelButtonText:'取消'});const delta=points?Number(value):Math.round(Number(value)*100);if(!Number.isSafeInteger(delta)||!delta){ElMessage.warning('请输入非零有效数值');return}await ElMessageBox.confirm(`确认${delta>0?'增加':'扣减'} ${m.memberName} 的${points?Math.abs(delta)+' 积分':money(Math.abs(delta))+' 储值'}？`,'确认账户调整',{confirmButtonText:'确认调整',cancelButtonText:'取消',type:'warning'});await api(`/api/merchant/v1/members/${m.id}/${kind}`,{method:'POST',body:JSON.stringify({delta,requestId:crypto.randomUUID()})});await reload();ElMessage.success('账户调整成功')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}
}
onMounted(reload)
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">MEMBERSHIP & MARKETING</div><h1>会员与营销</h1><p>管理消费者会员与品牌权益，让每一次到店成为下一次回购。</p></div><div class="heading-actions"><el-button @click="reload">刷新</el-button><el-button v-if="can('merchant:coupon:manage')" type="primary" @click="tab='coupons';open()">＋ 新建优惠券</el-button></div></div>
  <section class="metric-grid"><article class="metric"><div>品牌会员</div><strong>{{members.length}} <small>人</small></strong><p>消费者自主注册，品牌门店通用</p></article><article class="metric"><div>会员储值余额</div><strong>{{money(members.reduce((n,m)=>n+m.storedValueCents,0))}}</strong><p>当前可用储值合计</p></article><article class="metric"><div>可领取优惠券</div><strong>{{coupons.filter(c=>couponState(c)==='领取中').length}} <small>种</small></strong><p>已发布且在有效期内</p></article><article class="metric"><div>累计领取 / 已使用</div><strong>{{coupons.reduce((n,c)=>n+c.claimedQuantity,0)}} <small>/ {{coupons.reduce((n,c)=>n+(c.redeemedQuantity??0),0)}} 张</small></strong><p>当前优惠券模板合计</p></article></section>
  <el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <el-tabs v-model="tab" class="page-tabs"><el-tab-pane v-if="can('merchant:member:view')" label="会员档案" name="members"/><el-tab-pane v-if="can('merchant:coupon:view')" label="优惠券管理" name="coupons"/></el-tabs>
  <div v-loading="busy" class="panel"><template v-if="tab==='members'"><el-alert title="会员由消费者在消费端自主注册。总部可查询会员档案及维护积分、储值权益。" type="info" show-icon :closable="false"/><div class="filter-bar compact"><el-input v-model="keyword" placeholder="搜索会员姓名、手机号" clearable/><span class="subtle">会员数据为品牌范围，不随顶部门店筛选变化</span></div><el-table :data="memberRows" empty-text="暂无消费者注册会员"><el-table-column label="会员" min-width="160"><template #default="s"><div class="cell-stack"><b>{{s.row.memberName}}</b><small>{{s.row.mobile}}</small></div></template></el-table-column><el-table-column label="会员等级"><template #default="s"><el-tag>{{s.row.levelCode==='STANDARD'?'普通会员':s.row.levelCode}}</el-tag></template></el-table-column><el-table-column prop="availablePoints" label="可用积分"/><el-table-column label="储值余额"><template #default="s">{{money(s.row.storedValueCents)}}</template></el-table-column><el-table-column label="注册时间" min-width="175"><template #default="s">{{dateText(s.row.createdAt)}}</template></el-table-column><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.status==='ACTIVE'?'success':'info'">{{s.row.status==='ACTIVE'?'正常':'已停用'}}</el-tag></template></el-table-column><el-table-column v-if="can('merchant:member:manage')" label="权益调整" min-width="130"><template #default="s"><el-button link type="primary" @click="adjust(s.row,'points')">积分</el-button><el-button link type="primary" @click="adjust(s.row,'stored-value')">储值</el-button></template></el-table-column></el-table><div class="pagination"><span>共 {{filteredMembers.length}} 位会员</span><el-pagination v-model:current-page="current" :page-size="10" :total="filteredMembers.length" layout="prev, pager, next"/></div></template>
  <template v-else><div class="filter-bar compact"><el-input v-model="keyword" placeholder="搜索优惠券名称、编码" clearable/><el-select v-model="couponFilter" placeholder="全部状态" clearable><el-option v-for="s in ['草稿','待生效','领取中','已暂停','已领完','已过期']" :key="s" :label="s" :value="s"/></el-select></div><p class="subtle">草稿可编辑 → 发布后按有效期开放领取 → 可随时暂停或恢复领取。已领券权益保持不变，每位会员限领 1 张。</p><el-table :data="filteredCoupons" empty-text="暂无优惠券，可先新建草稿"><el-table-column label="优惠券" min-width="170"><template #default="s"><div class="cell-stack"><b>{{s.row.templateName}}</b><small>{{s.row.templateCode}}</small></div></template></el-table-column><el-table-column label="优惠规则" min-width="165"><template #default="s"><b class="blue-text">{{formDescription(s.row)}}</b></template></el-table-column><el-table-column label="有效期" min-width="180"><template #default="s"><div class="cell-stack"><span>{{dateText(s.row.validFrom)}}</span><small>至 {{dateText(s.row.validTo)}}</small></div></template></el-table-column><el-table-column label="发行 / 领取 / 使用" min-width="150"><template #default="s"><div class="cell-stack"><b>{{s.row.totalQuantity}} / {{s.row.claimedQuantity}} / {{s.row.redeemedQuantity??0}}</b><el-progress :percentage="Math.round(s.row.claimedQuantity/s.row.totalQuantity*100)" :show-text="false" :stroke-width="4"/></div></template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="couponState(s.row)==='领取中'?'success':couponState(s.row)==='已暂停'?'warning':'info'">{{couponState(s.row)}}</el-tag></template></el-table-column><el-table-column v-if="can('merchant:coupon:manage')" label="操作" min-width="160" fixed="right"><template #default="s"><el-button v-if="s.row.status==='DRAFT'" link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="!['已过期','已领完'].includes(couponState(s.row))" link :type="s.row.status==='ACTIVE'?'warning':'primary'" :disabled="saving" @click="changeStatus(s.row)">{{s.row.status==='DRAFT'?'发布':s.row.status==='ACTIVE'?'暂停领取':'恢复领取'}}</el-button><span v-else class="subtle">已结束</span></template></el-table-column></el-table></template></div>
  <el-drawer v-model="visible" :title="editing?'编辑优惠券草稿':'新建优惠券'" size="min(520px, 100vw)"><div class="coupon-preview"><small>品牌通用 · 每人限领 1 张</small><h2>¥ {{form.discount??0}} <span>{{form.minSpend?'满 '+form.minSpend+' 元可用':'无门槛'}}</span></h2><b>{{form.templateName||'优惠券名称'}}</b></div><el-form label-position="top"><el-form-item label="优惠券名称 *"><el-input v-model="form.templateName" maxlength="128" placeholder="例如：秋季到店满减券"/></el-form-item><el-form-item label="优惠券编码 *"><el-input v-model="form.templateCode" maxlength="64" :disabled="Boolean(editing)" placeholder="同品牌内唯一，例如 AUTUMN10"/></el-form-item><div class="form-grid"><el-form-item label="优惠金额（元） *"><el-input-number v-model="form.discount" :precision="2" :min="0.01" :max="1000000"/></el-form-item><el-form-item label="使用门槛（元） *"><el-input-number v-model="form.minSpend" :precision="2" :min="0" :max="1000000"/></el-form-item></div><el-form-item label="发行总量（张） *"><el-input-number v-model="form.totalQuantity" :min="1" :max="10000000" :precision="0"/></el-form-item><el-form-item label="生效时间 *"><el-date-picker v-model="form.validFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="选择开始时间"/></el-form-item><el-form-item label="失效时间 *"><el-date-picker v-model="form.validTo" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" placeholder="选择结束时间"/></el-form-item><el-alert title="保存后为草稿，不会立即发放。请在列表确认规则后发布。" type="info" :closable="false"/></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存草稿</el-button></template></el-drawer>
</template>
