<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api } from '@smart-merchant/api'
import { ElMessage } from 'element-plus'
const props=defineProps<{initialStoreId?:string}>()
const emit=defineEmits<{changed:[]}>()
type StoreRecord={id:string;storeName:string;address:string;businessHours:string;status:string;version:number}
const storeRecord=ref<StoreRecord|null>(null)
type Settings={marketplaceListed:boolean;latitude:number|null;longitude:number|null;city:string;district:string;coverUrl:string;pickupEnabled:boolean;shippingEnabled:boolean;firstShippingCents:number;extraShippingCents:number;excludedProvinces:string[];pickupOnlySkus:string[];version:number}
const stores=ref<{id:string;storeName:string}[]>([]),id=ref(''),form=ref<Settings|null>(null),busy=ref(false),error=ref(''),products=ref<{skuId:string;productName:string;skuName:string}[]>([])
const provinces='北京市 天津市 河北省 山西省 内蒙古自治区 辽宁省 吉林省 黑龙江省 上海市 江苏省 浙江省 安徽省 福建省 江西省 山东省 河南省 湖北省 湖南省 广东省 广西壮族自治区 海南省 重庆市 四川省 贵州省 云南省 西藏自治区 陕西省 甘肃省 青海省 宁夏回族自治区 新疆维吾尔自治区 香港特别行政区 澳门特别行政区 台湾省'.split(' ')
async function load(){form.value=null;storeRecord.value=null;products.value=[];if(!id.value)return;busy.value=true;error.value='';try{const records=await api<StoreRecord[]>('/api/merchant/v1/stores');storeRecord.value=records.find(s=>String(s.id)===id.value)||null;form.value=await api(`/api/merchant/v1/stores/${id.value}/storefront`);const rows=await api<{spu:{productName:string};skus:{sku:{id:number;skuName:string};sellable:boolean|null}[]}[]>(`/api/merchant/v1/products?storeId=${id.value}`);products.value=rows.flatMap(p=>p.skus.filter(s=>s.sellable!==null).map(s=>({skuId:String(s.sku.id),productName:p.spu.productName,skuName:s.sku.skuName})))}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function save(){if(!form.value||!storeRecord.value)return;if(!storeRecord.value.address?.trim()||!storeRecord.value.businessHours?.trim()){error.value='请填写详细地址和营业时间';return}busy.value=true;error.value='';try{const result=await api<{store:StoreRecord;storefront:Settings}>(`/api/merchant/v1/stores/${id.value}/configuration`,{method:'PUT',body:JSON.stringify({store:storeRecord.value,storefront:form.value})});storeRecord.value=result.store;form.value=result.storefront;emit('changed');ElMessage.success('门店展示和配送配置已保存')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function locate(){if(!form.value||!navigator.geolocation){error.value='浏览器不支持定位，请填写 WGS84 经纬度';return}const activeStore=id.value;navigator.geolocation.getCurrentPosition(p=>{if(form.value&&id.value===activeStore){form.value.latitude=p.coords.latitude;form.value.longitude=p.coords.longitude}},()=>error.value='无法定位，请在 HTTPS 下授权定位，或手动填写经纬度',{timeout:10000})}
onMounted(async()=>{try{stores.value=(await api<{id:number;storeName:string}[]>('/api/merchant/v1/stores')).map(s=>({...s,id:String(s.id)}));id.value=props.initialStoreId||stores.value[0]?.id||'';await load()}catch(e){error.value=(e as Error).message}})
</script>
<template><section class="panel" style="margin-top:20px" v-loading="busy"><h2>门店档案与配送配置</h2><p>仅修改当前选中的门店；详细地址与营业时间同步用于门店管理和消费者 H5。</p><p>消费者首页按门店展示。邮费按商品总件数计算：首件运费 +（总件数 − 1）× 续件运费。</p><el-select v-model="id" placeholder="选择门店" :disabled="busy" @change="load"><el-option v-for="s in stores" :key="s.id" :label="s.storeName" :value="s.id"/></el-select><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form v-if="form" label-position="top" style="max-width:680px;margin-top:20px" @submit.prevent="save"><template v-if="storeRecord"><el-form-item label="详细地址" required><el-input v-model="storeRecord.address" maxlength="512" type="textarea" placeholder="城市、区县、街道、门牌号"/></el-form-item><el-form-item label="营业时间" required><el-input v-model="storeRecord.businessHours" maxlength="128" placeholder="09:00–22:00"/></el-form-item></template><el-form-item label="在平台首页展示"><el-switch v-model="form.marketplaceListed"/></el-form-item><el-form-item label="城市"><el-input v-model="form.city" maxlength="80" placeholder="如：杭州市"/></el-form-item><el-form-item label="区县"><el-input v-model="form.district" maxlength="80" placeholder="如：西湖区"/></el-form-item><el-form-item label="门店位置（WGS84 经纬度）"><el-input-number v-model="form.latitude" :min="-90" :max="90" :precision="6" placeholder="纬度"/><el-input-number v-model="form.longitude" :min="-180" :max="180" :precision="6" placeholder="经度"/><el-button @click="locate">使用当前位置</el-button><p>请在门店现场获取位置。未填写坐标的门店可按地区搜索，不显示距离。</p></el-form-item><el-form-item label="门店封面图片地址"><el-input v-model="form.coverUrl" placeholder="https://…"/></el-form-item><el-form-item label="履约方式"><el-checkbox v-model="form.pickupEnabled">到店自提</el-checkbox><el-checkbox v-model="form.shippingEnabled">快递邮寄（消费者付运费）</el-checkbox></el-form-item><template v-if="form.shippingEnabled"><el-form-item label="首件运费（元）"><el-input-number :model-value="form.firstShippingCents/100" @update:model-value="(v:number|undefined)=>form&&(form.firstShippingCents=Math.round((v||0)*100))" :min="0" :max="10000" :precision="2"/></el-form-item><el-form-item label="每续件运费（元）"><el-input-number :model-value="form.extraShippingCents/100" @update:model-value="(v:number|undefined)=>form&&(form.extraShippingCents=Math.round((v||0)*100))" :min="0" :max="10000" :precision="2"/></el-form-item><el-form-item label="不配送省份 / 地区"><el-select v-model="form.excludedProvinces" multiple filterable><el-option v-for="p in provinces" :key="p" :label="p" :value="p"/></el-select></el-form-item><el-form-item label="仅自提商品规格"><el-select v-model="form.pickupOnlySkus" multiple filterable><el-option v-for="p in products" :key="p.skuId" :label="`${p.productName} · ${p.skuName}`" :value="p.skuId"/></el-select></el-form-item></template><el-button type="primary" native-type="submit" :disabled="busy">保存门店配置</el-button></el-form></section></template>
