<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {api} from '@smart-merchant/api'
import {ElMessage,ElMessageBox} from 'element-plus'
import ProductPhoto from './ProductPhoto.vue'
import {money} from '../model'
type Store={id:number;storeName:string;status:string}
type Sku={id:number;skuCode:string;skuName:string;barcode:string;specJson:string;basePriceCents:number;allowStorePrice:boolean;status:string;version:number}
type Product={spu:{id:number;productName:string;status:string;categoryId:number;imageUrl:string;description:string;version:number};skus:{sku:Sku}[]}
type Stock={storeId:number;storeName:string;skuId:number;skuCode:string;skuName:string;productName:string;actualQuantity:number;availableQuantity:number;reservedQuantity:number;lowStockThreshold:number}
type Allocation={id:number;storeId:number;storeName:string;productName:string;skuName:string;quantity:number;reason:string;createdAt:string}
const props=defineProps<{stores:Store[];storeId:number;canManage:boolean;canProductManage:boolean;canProductView:boolean}>()
const emit=defineEmits<{changed:[]}>()
const counts=ref<any[]>([]),countDetail=ref<any>(null)
const tab=ref('stock'),busy=ref(false),saving=ref(false),error=ref(''),query=ref(''),lowOnly=ref(false),stock=ref<Stock[]>([]),products=ref<Product[]>([]),categories=ref<{id:number;categoryName:string}[]>([]),allocations=ref<Allocation[]>([])
const skus=computed(()=>products.value.flatMap(p=>p.skus.map(s=>({...s.sku,spu:p.spu,productName:p.spu.productName,productStatus:p.spu.status}))))
const catalogRows=computed(()=>skus.value.filter(s=>`${s.productName} ${s.skuName} ${s.skuCode}`.includes(query.value.trim())))
const filtered=computed(()=>stock.value.filter(s=>(!props.storeId||s.storeId===props.storeId)&&(!lowOnly.value||s.availableQuantity<=s.lowStockThreshold)&&`${s.storeName} ${s.productName} ${s.skuName} ${s.skuCode}`.includes(query.value.trim())))
const totals=computed(()=>filtered.value.reduce((n,s)=>({actual:n.actual+s.actualQuantity,available:n.available+s.availableQuantity,reserved:n.reserved+s.reservedQuantity}),{actual:0,available:0,reserved:0}))
const activeSkus=computed(()=>skus.value.filter(s=>s.status==='ACTIVE'&&s.productStatus==='ACTIVE'))
let serial=0
async function load(){const id=++serial;busy.value=true;error.value='';try{const result=await Promise.all([api<Stock[]>('/api/merchant/v1/inventory/tenant-stock'),api<Allocation[]>('/api/merchant/v1/inventory/allocations'),props.canProductView?api<Product[]>('/api/merchant/v1/products'):Promise.resolve([]),props.canProductView?api<{id:number;categoryName:string}[]>('/api/merchant/v1/categories'):Promise.resolve([])]);if(id===serial){[stock.value,allocations.value,products.value,categories.value]=result;const reports=await Promise.all(props.stores.map(async store=>(await api<any[]>(`/api/merchant/v1/stock-counts?storeId=${store.id}`)).map(c=>({...c,storeName:store.storeName}))));if(id===serial)counts.value=reports.flat()}}catch(e){if(id===serial)error.value=(e as Error).message}finally{if(id===serial)busy.value=false}}
async function changed(){await load();emit('changed')}
async function showCount(row:any){try{countDetail.value={...await api<any>(`/api/merchant/v1/stock-counts/${row.id}`),storeName:row.storeName}}catch(e){ElMessage.error((e as Error).message)}}
async function completeCount(){if(!countDetail.value)return;try{await ElMessageBox.confirm('确认实盘数据属实？将按差异更新门店库存并保留盘点流水。','租户确认盘点',{confirmButtonText:'确认盘点',cancelButtonText:'取消'});saving.value=true;await api(`/api/merchant/v1/stock-counts/${countDetail.value.id}/complete`,{method:'POST'});countDetail.value=null;await changed();ElMessage.success('盘点已确认，库存和提醒已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
const allocationVisible=ref(false),allocation=reactive({skuId:0,reason:'',requestId:'',items:[] as {storeId:number;storeName:string;quantity:number}[]})
function openAllocation(row?:Stock){Object.assign(allocation,{skuId:row?.skuId??0,reason:'',requestId:crypto.randomUUID(),items:props.stores.filter(s=>s.status==='ACTIVE'&&(!row||s.id===row.storeId)).map(s=>({storeId:s.id,storeName:s.storeName,quantity:0}))});allocationVisible.value=true}
async function allocate(){const items=allocation.items.filter(i=>i.quantity>0).map(i=>({storeId:i.storeId,skuId:allocation.skuId,quantity:i.quantity}));if(!allocation.skuId||!items.length||items.some(i=>!Number.isSafeInteger(i.quantity))||!allocation.reason.trim()){ElMessage.warning('请选择商品，填写分配原因，并给至少一家门店填写正整数入库量');return}try{await ElMessageBox.confirm(`向 ${items.length} 家门店分配共 ${items.reduce((n,i)=>n+i.quantity,0)} 件商品，确认后立即入库并留下流水。`,'确认租户分配',{confirmButtonText:'确认入库',cancelButtonText:'返回修改'});saving.value=true;await api('/api/merchant/v1/inventory/allocations',{method:'POST',body:JSON.stringify({requestId:allocation.requestId,reason:allocation.reason.trim(),items})});allocationVisible.value=false;await changed();ElMessage.success('已按各店数量分配入库，低库存提醒已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
const thresholdVisible=ref(false),threshold=reactive({storeId:0,skuId:0,lowStockThreshold:5,label:''})
function openThreshold(row:Stock){Object.assign(threshold,{storeId:row.storeId,skuId:row.skuId,lowStockThreshold:row.lowStockThreshold,label:`${row.storeName} · ${row.productName} ${row.skuName}`});thresholdVisible.value=true}
async function saveThreshold(){try{saving.value=true;await api('/api/merchant/v1/inventory/threshold',{method:'PUT',body:JSON.stringify(threshold)});thresholdVisible.value=false;await changed();ElMessage.success('预警线已更新，两端将按相同规则提醒')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
const productVisible=ref(false),categoryVisible=ref(false),newProduct=reactive({imageUrl:'',categoryId:0,productCode:'',productName:'',skuCode:'',skuName:'标准规格',barcode:'',price:0}),newCategory=reactive({categoryCode:'',categoryName:''})
function openProduct(){Object.assign(newProduct,{imageUrl:'',categoryId:categories.value[0]?.id??0,productCode:'',productName:'',skuCode:'',skuName:'标准规格',barcode:'',price:0});productVisible.value=true}
async function saveCategory(){if(!newCategory.categoryCode.trim()||!newCategory.categoryName.trim()){ElMessage.warning('请填写分类编码和名称');return}try{saving.value=true;const category=await api<{id:number}>('/api/merchant/v1/categories',{method:'POST',body:JSON.stringify({...newCategory,sortOrder:0})});categoryVisible.value=false;await load();newProduct.categoryId=category.id;ElMessage.success('分类已创建')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function saveProduct(){if(photoBusy.value||saving.value)return;if(!newProduct.categoryId||!newProduct.productCode.trim()||!newProduct.productName.trim()||!newProduct.skuCode.trim()||!newProduct.skuName.trim()||newProduct.price<0){ElMessage.warning('请填写分类、商品编码、名称、规格与售价');return}try{saving.value=true;await api('/api/merchant/v1/products/with-sku',{method:'POST',body:JSON.stringify({...newProduct,priceCents:Math.round(newProduct.price*100)})});productVisible.value=false;await changed();ElMessage.success('租户商品已创建，可按门店分配入库')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
const photoBusy=ref(false),productEdit=ref<Product['spu']|null>(null)
async function saveProductInfo(){if(!productEdit.value||photoBusy.value||saving.value)return;if(!productEdit.value.categoryId||!productEdit.value.productName.trim()){ElMessage.warning('请填写名称并选择分类');return}try{saving.value=true;productEdit.value=await api<Product['spu']>(`/api/merchant/v1/products/${productEdit.value.id}`,{method:'PUT',body:JSON.stringify(productEdit.value)});await changed();ElMessage.success('商品照片和分类已保存')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
const editing=ref<Sku|null>(null),editForm=reactive({skuName:'',barcode:'',price:0,status:'ACTIVE'})
function openDetails(s:Sku & {spu:Product['spu']}){productEdit.value={...s.spu};editing.value=s;Object.assign(editForm,{skuName:s.skuName,barcode:s.barcode??'',price:s.basePriceCents/100,status:s.status})}
async function saveSku(){if(!editing.value||!editForm.skuName.trim())return;try{saving.value=true;editing.value=await api<Sku>(`/api/merchant/v1/skus/${editing.value.id}`,{method:'PUT',body:JSON.stringify({...editing.value,...editForm,basePriceCents:Math.round(editForm.price*100)})});await changed();ElMessage.success('商品规格已更新')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
watch(()=>props.storeId,()=>{query.value='';tab.value='stock'})
onMounted(load)
</script>
<template>
 <div class="page-heading"><div><div class="eyebrow">TENANT PRODUCTS & INVENTORY</div><h1>商品与门店库存</h1><p>租户统一提供商品、分配各店入库数量，持续掌握实际库存、可用库存与缺货情况。</p></div><div class="heading-actions"><el-button :loading="busy" @click="load">刷新</el-button><el-button v-if="canProductManage" @click="openProduct">新增租户商品</el-button><el-button v-if="canManage&&canProductView" type="primary" @click="openAllocation()">分配门店入库</el-button></div></div>
 <el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <el-tabs v-model="tab"><el-tab-pane label="各店库存" name="stock"/><el-tab-pane v-if="canProductView" label="租户商品目录" name="catalog"/><el-tab-pane label="分配入库记录" name="history"/><el-tab-pane label="门店盘点确认" name="counts"/></el-tabs>
 <template v-if="tab==='stock'"><section class="metric-grid"><article class="metric"><div>门店商品库存项</div><strong>{{filtered.length}}</strong></article><article class="metric"><div>实际库存</div><strong>{{totals.actual}}</strong></article><article class="metric"><div>可用库存</div><strong>{{totals.available}}</strong></article><article class="metric"><div>订单预占</div><strong>{{totals.reserved}}</strong></article></section>
 <div class="panel" v-loading="busy"><div class="filter-bar compact"><el-input v-model="query" placeholder="搜索门店、商品、规格或 SKU" clearable/><el-checkbox v-model="lowOnly">仅看低库存</el-checkbox></div><el-table :data="filtered" empty-text="暂无门店库存，请先创建租户商品并分配入库"><el-table-column prop="storeName" label="门店" min-width="120"/><el-table-column label="商品 / 规格" min-width="185"><template #default="{row}"><div class="cell-stack"><b>{{row.productName}}</b><small>{{row.skuName}} · {{row.skuCode}}</small></div></template></el-table-column><el-table-column prop="actualQuantity" label="实际"/><el-table-column prop="availableQuantity" label="可用"/><el-table-column prop="reservedQuantity" label="预占"/><el-table-column prop="lowStockThreshold" label="预警线"/><el-table-column label="库存提醒" min-width="110"><template #default="{row}"><el-tag :type="row.availableQuantity<=row.lowStockThreshold?'warning':'success'">{{row.availableQuantity===0?'缺货':row.availableQuantity<=row.lowStockThreshold?'低库存':'充足'}}</el-tag></template></el-table-column><el-table-column v-if="canManage" label="操作" min-width="170"><template #default="{row}"><el-button v-if="canProductView" link type="primary" @click="openAllocation(row)">分配补货</el-button><el-button link type="primary" @click="openThreshold(row)">预警线</el-button></template></el-table-column></el-table></div></template>
 <div v-else-if="tab==='catalog'" class="panel"><div class="filter-bar compact"><el-input v-model="query" placeholder="搜索商品、规格或 SKU" clearable/><el-button v-if="canProductManage" @click="categoryVisible=true">新增分类</el-button></div><el-table :data="catalogRows" empty-text="请先新增租户商品"><el-table-column prop="productName" label="租户商品"/><el-table-column label="分类"><template #default="{row}">{{categories.find(c=>c.id===row.spu.categoryId)?.categoryName||'未分类'}}</template></el-table-column><el-table-column prop="skuName" label="规格"/><el-table-column prop="skuCode" label="SKU"/><el-table-column label="统一售价"><template #default="{row}">{{money(row.basePriceCents)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}">{{row.status==='ACTIVE'?'已启用':row.status==='DRAFT'?'草稿':'停用'}}</template></el-table-column><el-table-column v-if="canProductManage" label="操作"><template #default="{row}"><el-button link type="primary" @click="openDetails(row)">详情</el-button></template></el-table-column></el-table></div>
 <div v-else-if="tab==='history'" class="panel"><el-table :data="allocations.filter(a=>!storeId||a.storeId===storeId)" empty-text="暂无租户分配记录"><el-table-column label="分配时间" min-width="175"><template #default="{row}">{{row.createdAt?.replace('T',' ').slice(0,19)}}</template></el-table-column><el-table-column prop="storeName" label="门店"/><el-table-column prop="productName" label="商品"/><el-table-column prop="skuName" label="规格"/><el-table-column prop="quantity" label="入库数量"/><el-table-column prop="reason" label="分配原因"/></el-table></div>
 <div v-else class="panel"><el-alert title="门店盘盈增加库存需由租户确认，避免绕过统一入库管理。" type="info" :closable="false"/><el-table :data="counts.filter(c=>!storeId||c.storeId===storeId)" empty-text="暂无盘点单"><el-table-column prop="storeName" label="门店"/><el-table-column prop="countNo" label="盘点单号"/><el-table-column prop="positiveDifferenceQuantity" label="盘盈数量"/><el-table-column label="状态"><template #default="{row}">{{row.status==='COMPLETED'?'已完成':'待确认'}}</template></el-table-column><el-table-column label="明细"><template #default="{row}"><el-button link type="primary" @click="showCount(row)">查看 / 确认</el-button></template></el-table-column></el-table></div>
 <el-drawer :model-value="!!countDetail" title="租户确认门店盘点" size="min(650px,100vw)" @close="countDetail=null"><template v-if="countDetail"><h3>{{countDetail.storeName}} · {{countDetail.countNo}}</h3><el-table :data="countDetail.items"><el-table-column prop="skuName" label="商品规格"/><el-table-column prop="expectedQuantity" label="账面库存"/><el-table-column prop="countedQuantity" label="实盘数量"/><el-table-column prop="differenceQuantity" label="差异"/></el-table><p>{{countDetail.remark}}</p></template><template #footer><el-button v-if="canManage&&countDetail?.status==='DRAFT'" type="primary" :loading="saving" @click="completeCount">确认盘点并更新库存</el-button></template></el-drawer>
 <el-drawer v-model="allocationVisible" title="租户分配门店入库" size="min(680px,100vw)"><el-form label-position="top"><el-form-item label="租户商品" required><el-select v-model="allocation.skuId" filterable style="width:100%" placeholder="选择已启用的租户商品"><el-option v-for="s in activeSkus" :key="s.id" :value="s.id" :label="`${s.productName} · ${s.skuName} · ${s.skuCode}`"/></el-select></el-form-item><el-table :data="allocation.items" empty-text="没有可分配的营业门店"><el-table-column prop="storeName" label="门店"/><el-table-column label="本次入库数量（0 表示不分配）" min-width="260"><template #default="{row}"><el-input-number v-model="row.quantity" :min="0" :precision="0" :max="1000000000"/></template></el-table-column></el-table><el-form-item label="分配原因 / 入库说明" required><el-input v-model="allocation.reason" type="textarea" maxlength="512" placeholder="例如：总部统一补货、首批铺货"/></el-form-item></el-form><template #footer><el-button @click="allocationVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="allocate">确认分配入库</el-button></template></el-drawer>
 <el-dialog v-model="thresholdVisible" title="设置门店商品预警线" width="min(480px,95vw)"><p>{{threshold.label}}</p><p>可用库存小于或等于此数量时，同时提醒租户与该门店；设为 0 时仅缺货提醒。</p><el-input-number v-model="threshold.lowStockThreshold" :min="0" :precision="0"/><template #footer><el-button type="primary" :loading="saving" @click="saveThreshold">保存预警线</el-button></template></el-dialog>
 <el-dialog v-model="productVisible" title="新增租户商品" width="min(560px,95vw)"><el-form label-position="top"><el-form-item label="商品分类" required><el-select v-model="newProduct.categoryId" placeholder="选择分类"><el-option v-for="c in categories" :key="c.id" :label="c.categoryName" :value="c.id"/></el-select><el-button link type="primary" @click="categoryVisible=true">新增分类</el-button></el-form-item><el-form-item label="商品实物照片"><ProductPhoto v-model="newProduct.imageUrl" @uploading="photoBusy=$event"/></el-form-item><el-form-item label="商品编码" required><el-input v-model="newProduct.productCode" maxlength="64"/></el-form-item><el-form-item label="商品名称" required><el-input v-model="newProduct.productName" maxlength="160"/></el-form-item><el-form-item label="SKU 编码" required><el-input v-model="newProduct.skuCode" maxlength="64"/></el-form-item><el-form-item label="规格名称" required><el-input v-model="newProduct.skuName" maxlength="128"/></el-form-item><el-form-item label="条码"><el-input v-model="newProduct.barcode" maxlength="64"/></el-form-item><el-form-item label="统一售价（元）"><el-input-number v-model="newProduct.price" :min="0" :precision="2"/></el-form-item></el-form><template #footer><el-button type="primary" :loading="saving" :disabled="photoBusy" @click="saveProduct">创建并启用商品</el-button></template></el-dialog>
 <el-dialog v-model="categoryVisible" title="新增商品分类" width="min(440px,95vw)" append-to-body><el-form label-position="top"><el-form-item label="分类编码"><el-input v-model="newCategory.categoryCode" maxlength="64"/></el-form-item><el-form-item label="分类名称"><el-input v-model="newCategory.categoryName" maxlength="128"/></el-form-item></el-form><template #footer><el-button type="primary" :loading="saving" @click="saveCategory">保存分类</el-button></template></el-dialog>

<el-dialog :model-value="!!productEdit" title="商品详情" width="min(680px,95vw)" :close-on-click-modal="false" @close="productEdit=null;editing=null"><h3>商品资料</h3><el-form v-if="productEdit" label-position="top"><el-form-item label="商品名称"><el-input v-model="productEdit.productName" maxlength="160"/></el-form-item><el-form-item label="商品分类" required><el-select v-model="productEdit.categoryId"><el-option v-for="c in categories" :key="c.id" :value="c.id" :label="c.categoryName"/></el-select><el-button link @click="categoryVisible=true">新增分类</el-button></el-form-item><el-form-item label="商品实物照片"><ProductPhoto v-model="productEdit.imageUrl" @uploading="photoBusy=$event"/></el-form-item></el-form><el-button type="primary" :loading="saving" :disabled="photoBusy" @click="saveProductInfo">保存商品资料</el-button><el-divider/><h3>规格与售价</h3><p v-if="editing" class="subtle">SKU：{{editing.skuCode}}</p><el-form label-position="top"><el-form-item label="规格名称"><el-input v-model="editForm.skuName" maxlength="128"/></el-form-item><el-form-item label="条码"><el-input v-model="editForm.barcode" maxlength="64"/></el-form-item><el-form-item label="统一售价（元）"><el-input-number v-model="editForm.price" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-select v-model="editForm.status"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item></el-form><el-button type="primary" :loading="saving" :disabled="photoBusy" @click="saveSku">保存规格与售价</el-button><template #footer><el-button :disabled="saving||photoBusy" @click="productEdit=null;editing=null">关闭</el-button></template></el-dialog>
</template>
