package com.smartmerchant.saas.merchant.interfaces;
import com.smartmerchant.saas.merchant.application.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;

@RestController @RequestMapping("/api/merchant/v1") public class InventoryController {
 private final InventoryService inventory;private final StockTransferService transfers;public InventoryController(InventoryService inventory,StockTransferService transfers){this.inventory=inventory;this.transfers=transfers;}
 @GetMapping("/inventory") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object inventory(@RequestParam long storeId){return json(inventory.inventory(storeId));}
 @GetMapping("/inventory/ledger") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object storeLedger(@RequestParam long storeId){return json(inventory.storeLedger(storeId));}
 @GetMapping("/stock-counts") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object counts(@RequestParam long storeId){return json(inventory.counts(storeId));}
 @GetMapping("/inventory/{skuId}/ledger") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object ledger(@PathVariable long skuId,@RequestParam long storeId){return json(inventory.ledger(storeId,skuId));}
 @PostMapping("/inventory/{skuId}/adjust") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object adjust(@PathVariable long skuId,@Valid @RequestBody Adjustment r){return inventory.adjust(r.storeId(),skuId,r.quantityDelta(),r.idempotencyKey(),r.reason());}
 @PostMapping("/inventory/{skuId}/reserve") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object reserve(@PathVariable long skuId,@Valid @RequestBody StockOperation r){return inventory.reserve(r.storeId(),skuId,r.quantity(),r.idempotencyKey(),r.businessId());}
 @PostMapping("/inventory/{skuId}/release") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object release(@PathVariable long skuId,@Valid @RequestBody StockOperation r){return inventory.release(r.storeId(),skuId,r.quantity(),r.idempotencyKey(),r.businessId());}
 @PostMapping("/inventory/{skuId}/deduct") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object deduct(@PathVariable long skuId,@Valid @RequestBody StockOperation r){return inventory.deductReserved(r.storeId(),skuId,r.quantity(),r.idempotencyKey(),r.businessId());}
 @PostMapping("/stock-counts") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object count(@Valid @RequestBody CountCreate r){return json(inventory.createCount(r.storeId(),r.countNo(),r.remark(),r.items().stream().map(i->new InventoryService.CountLine(i.skuId(),i.countedQuantity())).toList()));}
 @GetMapping("/stock-counts/{id}") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object count(@PathVariable long id){return json(inventory.count(id));}
 @PostMapping("/stock-counts/{id}/complete") @PreAuthorize("hasAuthority('merchant:inventory:manage')") public Object complete(@PathVariable long id){return json(inventory.completeCount(id));}
 @GetMapping("/transfers/shared-stock") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object sharedStock(@RequestParam long storeId,@RequestParam(defaultValue="") String query){return json(transfers.sharedStock(storeId,query));}
 @PostMapping("/transfers/requests") @PreAuthorize("hasAuthority('merchant:transfer:manage')") public Object requestTransfer(@Valid @RequestBody TransferRequest r){return json(transfers.request(r.transferNo(),r.sourceStoreId(),r.targetStoreId(),r.remark(),r.items().stream().map(i->new StockTransferService.Line(i.skuId(),i.quantity())).toList(),r.deliveryMode(),r.recipientName(),r.recipientPhone(),r.deliveryAddress(),r.orderId()));}
 @GetMapping("/transfers") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object transfers(){return json(transfers.list());}
 @GetMapping("/transfers/{id}") @PreAuthorize("hasAuthority('merchant:inventory:view')") public Object transfer(@PathVariable long id){return json(transfers.get(id));}
 @PostMapping("/transfers") @PreAuthorize("hasAuthority('merchant:transfer:manage')") public Object transfer(@Valid @RequestBody TransferCreate r){return json(transfers.create(r.transferNo(),r.sourceStoreId(),r.targetStoreId(),r.remark(),r.items().stream().map(i->new StockTransferService.Line(i.skuId(),i.quantity())).toList()));}
 @PostMapping("/transfers/{id}/approve") @PreAuthorize("hasAuthority('merchant:transfer:approve')") public Object approve(@PathVariable long id){return json(transfers.approve(id));}
 @PostMapping("/transfers/{id}/ship") @PreAuthorize("hasAuthority('merchant:transfer:manage')") public Object ship(@PathVariable long id){return json(transfers.ship(id));}
 @PostMapping("/transfers/{id}/receive") @PreAuthorize("hasAuthority('merchant:transfer:manage')") public Object receive(@PathVariable long id){return json(transfers.receive(id));}
 @PostMapping("/transfers/{id}/cancel") @PreAuthorize("hasAuthority('merchant:transfer:manage')") public Object cancel(@PathVariable long id){return json(transfers.cancel(id));}
 static Object json(Object value){if(value instanceof Map<?,?> map){var result=new LinkedHashMap<String,Object>();map.forEach((k,v)->result.put(camel(String.valueOf(k)),json(v)));return result;}if(value instanceof Collection<?> values)return values.stream().map(InventoryController::json).toList();return value;}
 private static String camel(String key){var parts=key.toLowerCase(Locale.ROOT).split("_");var result=new StringBuilder(parts[0]);for(int i=1;i<parts.length;i++)result.append(Character.toUpperCase(parts[i].charAt(0))).append(parts[i].substring(1));return result.toString();}
 public record Adjustment(@Positive long storeId,long quantityDelta,@NotBlank String idempotencyKey,@NotBlank String reason){}
 public record StockOperation(@Positive long storeId,@Positive long quantity,@NotBlank String idempotencyKey,Long businessId){}
 public record CountItem(@Positive long skuId,@PositiveOrZero long countedQuantity){}public record CountCreate(@Positive long storeId,@NotBlank String countNo,String remark,@NotEmpty List<@Valid CountItem> items){}
 public record TransferRequest(@NotBlank @Size(max=64) String transferNo,@Positive long sourceStoreId,@Positive long targetStoreId,@Size(max=512) String remark,@NotEmpty @Size(max=100) List<@Valid TransferItem> items,@NotBlank @Pattern(regexp="STORE|OTHER|CUSTOMER") String deliveryMode,@Size(max=80) String recipientName,@Size(max=32) String recipientPhone,@Size(max=512) String deliveryAddress,@Positive Long orderId){}
 public record TransferItem(@Positive long skuId,@Positive long quantity){}public record TransferCreate(@NotBlank String transferNo,@Positive long sourceStoreId,@Positive long targetStoreId,String remark,@NotEmpty List<@Valid TransferItem> items){}
}
