<script setup lang="ts">
import LoginScreen from '../../../packages/ui/src/LoginScreen.vue'
import { computed, onMounted, reactive, ref } from 'vue'
import { api, auth, login } from '@smart-merchant/api'
import { ElMessage, ElMessageBox } from 'element-plus'
import StorefrontSettings from './components/StorefrontSettings.vue'
import ConsumerSettings from './components/ConsumerSettings.vue'
import StorePermissions from './components/StorePermissions.vue'
import StorePassword from './components/StorePassword.vue'
import BusinessOverview from './components/BusinessOverview.vue'
import OrdersRevenue from './components/OrdersRevenue.vue'
import MembersMarketing from './components/MembersMarketing.vue'
import TenantInventory from './components/TenantInventory.vue'
import LowStockNotice from './components/LowStockNotice.vue'
import {useStockAlerts} from './useStockAlerts'
import { type Order, money } from './model'
import './shell.css'
import './erp.css'

type Store={id:number;storeCode:string;storeName:string;address:string;businessHours:string;status:string;version:number}
type Stock={lowStockThreshold:number;skuId:number;actualQuantity:number;availableQuantity:number;reservedQuantity:number}
type Transfer={id:number;sourceStoreId:number;targetStoreId:number;status:string}
type Overview={store:Store;skuCount:number;actualQuantity:number;availableQuantity:number;reservedQuantity:number;lowStockCount:number;transfersInTransit:number;completedOrders:number;revenueCents:number}
type StoreAccount={storeId:number;storeCode:string;storeName:string;userId:number;username:string;displayName:string;updatedAt:string}
type StoreQuota={used:number;limit:number|null;canCreate:boolean}

const signedIn=ref(Boolean(auth.accessToken)),loading=ref(false),dataLoading=ref(false),me=ref<any>()
const page=ref<'overview'|'stores'|'orders'|'members'|'inventory'|'consumer'>('overview'),selectedStoreId=ref<number>(0),stores=ref<Store[]>([]),overviews=ref<Overview[]>([]),orders=ref<Order[]>([]),accounts=ref<StoreAccount[]>([])
const quota=ref<StoreQuota>({used:0,limit:null,canCreate:true})
type Plan={planCode:string;planName:string;storeQuota:number|null}
type PublicPlan={id:number;planCode:string;planName:string;status:string}
const planVisible=ref(false),planLoading=ref(false),upgrading=ref(false),currentPlan=ref<Plan|null>(null),upgradePlans=ref<Plan[]>([]),planError=ref('')
const onboardingVisible=ref(false),onboardingLoading=ref(false),applicationId=ref(''),publicPlans=ref<PublicPlan[]>([])
const onboarding=reactive({merchantName:'',contactName:'',contactMobile:'',planCode:'STANDARD',password:'',confirmPassword:'',agreed:false})
async function openOnboarding(){onboardingVisible.value=true;applicationId.value='';if(!publicPlans.value.length)try{publicPlans.value=await api<PublicPlan[]>('/api/public/v1/plans');if(!publicPlans.value.some(p=>p.planCode===onboarding.planCode))onboarding.planCode=publicPlans.value[0]?.planCode||''}catch(e){ElMessage.error((e as Error).message)}}
async function submitOnboarding(){if(!onboarding.merchantName.trim()||!onboarding.contactName.trim()||!/^1[3-9]\d{9}$/.test(onboarding.contactMobile)||onboarding.password.length<8||onboarding.password.length>64||onboarding.password!==onboarding.confirmPassword||!onboarding.planCode||!onboarding.agreed){ElMessage.warning('请完整填写资料、确认密码并同意入驻条款');return}try{onboardingLoading.value=true;const result=await api<{id:string}>('/api/public/v1/tenant-applications',{method:'POST',body:JSON.stringify({merchantName:onboarding.merchantName.trim(),contactName:onboarding.contactName.trim(),contactMobile:onboarding.contactMobile,planCode:onboarding.planCode,password:onboarding.password})});applicationId.value=String(result.id);credentials.username=onboarding.contactMobile;ElMessage.success('入驻申请已提交，请等待平台审核')}catch(e){ElMessage.error((e as Error).message)}finally{onboardingLoading.value=false}}
async function openPlans(){planVisible.value=true;planLoading.value=true;planError.value='';currentPlan.value=null;upgradePlans.value=[];try{const [current,options]=await Promise.all([api<Plan>('/api/merchant/v1/subscription'),api<Plan[]>('/api/merchant/v1/subscription/upgrades')]);currentPlan.value=current;upgradePlans.value=options}catch(e){planError.value=(e as Error).message}finally{planLoading.value=false}}
async function upgrade(plan:Plan){try{await ElMessageBox.confirm(`确认升级为「${plan.planName}」？门店额度将调整为 ${plan.storeQuota??'不限'}，确认后立即生效。`,'升级套餐',{confirmButtonText:'确认升级',cancelButtonText:'取消'});upgrading.value=true;await api('/api/merchant/v1/subscription/upgrade',{method:'POST',body:JSON.stringify({planCode:plan.planCode})});await reload();await openPlans();ElMessage.success('套餐已升级，门店额度已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{upgrading.value=false}}
const createVisible=ref(false),now=ref(new Date()),revision=ref(0),editStore=ref<Store|null>(null),storeSearch=ref(''),storeStatus=ref(''),saving=ref(false),loadError=ref('')
const filteredStores=computed(()=>stores.value.filter(s=>(!selectedStoreId.value||s.id===selectedStoreId.value)&&(!storeStatus.value||s.status===storeStatus.value)&&`${s.storeName} ${s.storeCode} ${s.address} ${accounts.value.find(a=>a.storeId===s.id)?.username??''}`.toLowerCase().includes(storeSearch.value.trim().toLowerCase())))
const configurationStore=ref<Store|null>(null)
const permissionStore=ref<Store|null>(null)
const accountVisible=ref(false),accountMode=ref<'create'|'edit'>('create')
const credentials=reactive({username:'',password:''})
const newStore=reactive({storeCode:'',storeName:'',address:'',businessHours:''})
const accountForm=reactive({storeId:0,username:'',displayName:'',password:''})
const can=(code:string)=>me.value?.permissions?.includes(code)
const {alerts,alertError,alertUpdated,refreshAlerts}=useStockAlerts(()=>signedIn.value&&Boolean(can('merchant:inventory:view'))&&me.value?.dataScope==='TENANT_ALL')
const visibleOverviews=computed(()=>selectedStoreId.value?overviews.value.filter(x=>x.store.id===selectedStoreId.value):overviews.value)
const totals=computed(()=>visibleOverviews.value.reduce((r,x)=>({actual:r.actual+x.actualQuantity,available:r.available+x.availableQuantity,reserved:r.reserved+x.reservedQuantity,low:r.low+x.lowStockCount,transit:r.transit+x.transfersInTransit,sku:r.sku+x.skuCount,orders:r.orders+x.completedOrders,revenue:r.revenue+x.revenueCents}),{actual:0,available:0,reserved:0,low:0,transit:0,sku:0,orders:0,revenue:0}))
const updatedAt=computed(()=>now.value.toLocaleString('zh-CN',{hour12:false}))

async function signIn(){if(loading.value||!credentials.username.trim()||!credentials.password)return;try{loading.value=true;await login(credentials.username,credentials.password);signedIn.value=true;await reload()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function reload(){try{dataLoading.value=true;loadError.value='';me.value=await api('/api/merchant/v1/me');if(me.value.dataScope!=='TENANT_ALL')ElMessage.warning('当前账号不是租户总部权限，请使用门店端');stores.value=can('merchant:store:view')?await api('/api/merchant/v1/stores'):[];if(can('merchant:store:view')&&me.value.dataScope==='TENANT_ALL')quota.value=await api('/api/merchant/v1/stores/quota');if(can('iam:user:manage'))accounts.value=await api('/api/merchant/v1/stores/accounts');let transfers:Transfer[]=[];if(can('merchant:inventory:view'))transfers=await api('/api/merchant/v1/transfers');if(can('merchant:order:view'))orders.value=await api('/api/merchant/v1/orders');overviews.value=await Promise.all(stores.value.map(async store=>{let stock:Stock[]=[];let performance={completedOrders:0,revenueCents:0};if(can('merchant:inventory:view'))stock=await api(`/api/merchant/v1/inventory?storeId=${store.id}`);if(can('merchant:order:view'))performance=await api(`/api/merchant/v1/orders/performance?storeId=${store.id}`);return{store,skuCount:stock.length,actualQuantity:stock.reduce((n,s)=>n+s.actualQuantity,0),availableQuantity:stock.reduce((n,s)=>n+s.availableQuantity,0),reservedQuantity:stock.reduce((n,s)=>n+s.reservedQuantity,0),lowStockCount:stock.filter(s=>s.availableQuantity<=(s.lowStockThreshold??5)).length,transfersInTransit:transfers.filter(t=>(t.sourceStoreId===store.id||t.targetStoreId===store.id)&&t.status==='IN_TRANSIT').length,...performance}}));now.value=new Date();revision.value++;void refreshAlerts()}catch(e){loadError.value=(e as Error).message;ElMessage.error(loadError.value);if(!auth.accessToken)signedIn.value=false}finally{dataLoading.value=false}}
function openStore(store?:Store){editStore.value=store??null;Object.assign(newStore,store?{storeCode:store.storeCode,storeName:store.storeName,address:store.address,businessHours:store.businessHours}:{storeCode:'',storeName:'',address:'',businessHours:''});createVisible.value=true}
async function createStore(){if(!newStore.storeCode.trim()||!newStore.storeName.trim()||!newStore.address.trim()||!newStore.businessHours.trim()){ElMessage.warning('请填写门店编码、名称、地址和营业时间');return}try{saving.value=true;const savedStore=await api<Store>(editStore.value?`/api/merchant/v1/stores/${editStore.value.id}`:'/api/merchant/v1/stores',{method:editStore.value?'PUT':'POST',body:JSON.stringify({...newStore,...(editStore.value?{status:editStore.value.status,version:editStore.value.version}:{})})});createVisible.value=false;await reload();if(!editStore.value&&can('iam:user:manage'))permissionStore.value=savedStore;ElMessage.success(editStore.value?'门店档案已更新':'门店已添加，请继续配置登录账号与权限')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function toggleStore(store:Store){try{await ElMessageBox.confirm(store.status==='ACTIVE'?`确认停用「${store.storeName}」？请先检查该门店的待处理业务。`:`恢复「${store.storeName}」营业？`,'更新门店状态',{confirmButtonText:'确认',cancelButtonText:'取消',type:'warning'});await api(`/api/merchant/v1/stores/${store.id}`,{method:'PUT',body:JSON.stringify({storeName:store.storeName,address:store.address,businessHours:store.businessHours,status:store.status==='ACTIVE'?'INACTIVE':'ACTIVE',version:store.version})});await reload();ElMessage.success('门店状态已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
function manageAccount(store:Store){const current=accounts.value.find(a=>a.storeId===store.id);accountMode.value=current?'edit':'create';Object.assign(accountForm,{storeId:store.id,username:current?.username??`store-${store.id}-admin`,displayName:current?.displayName??`${store.storeName}管理员`,password:''});accountVisible.value=true}
async function saveAccount(){if(!accountForm.username.trim()||!accountForm.displayName.trim()){ElMessage.warning('请填写登录账号和账号名称');return}if((accountMode.value==='create'||accountForm.password)&& (accountForm.password.length<8||accountForm.password.length>64)){ElMessage.warning('密码需为 8 至 64 位');return}try{saving.value=true;await api(`/api/merchant/v1/stores/${accountForm.storeId}/account`,{method:accountMode.value==='create'?'POST':'PUT',body:JSON.stringify({username:accountForm.username.trim(),displayName:accountForm.displayName.trim(),password:accountForm.password||undefined})});accountVisible.value=false;accountForm.password='';await reload();ElMessage.success(accountMode.value==='create'?'门店独立账号已创建':'门店账号已更新')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
function logout(){auth.clear();signedIn.value=false}
onMounted(()=>{if(signedIn.value)reload()})
</script>

<template>
  <template v-if="!signedIn"><LoginScreen kind="merchant" v-model:username="credentials.username" v-model:password="credentials.password" :loading="loading" @submit="signIn"/><button class="tenant-apply-entry" @click="openOnboarding">还没有租户？自主申请入驻</button>
    <el-dialog v-model="onboardingVisible" title="租户自主入驻" width="min(560px,94vw)" :close-on-click-modal="!onboardingLoading">
      <el-result v-if="applicationId" icon="success" title="申请已提交" sub-title="平台审核通过后，可使用负责人手机号和申请密码登录租户经营中心。"><template #extra><p class="application-number">申请编号 {{applicationId}}</p><el-button type="primary" @click="onboardingVisible=false">返回登录</el-button></template></el-result>
      <el-form v-else label-position="top" @submit.prevent="submitOnboarding"><el-alert title="每个租户的数据、门店、商品、会员和订单均独立隔离。申请通过前不会创建租户或登录账号。" type="info" :closable="false" show-icon/><div class="onboarding-grid"><el-form-item label="商户 / 品牌名称" required><el-input v-model="onboarding.merchantName" maxlength="128" placeholder="例如：春风便利"/></el-form-item><el-form-item label="负责人姓名" required><el-input v-model="onboarding.contactName" maxlength="64"/></el-form-item><el-form-item label="负责人手机号（登录账号）" required><el-input v-model="onboarding.contactMobile" maxlength="11" inputmode="numeric" autocomplete="username"/></el-form-item><el-form-item label="申请套餐" required><el-select v-model="onboarding.planCode" style="width:100%"><el-option v-for="p in publicPlans" :key="p.id" :label="p.planName" :value="p.planCode"/></el-select></el-form-item><el-form-item label="登录密码" required><el-input v-model="onboarding.password" type="password" show-password minlength="8" maxlength="64" autocomplete="new-password"/></el-form-item><el-form-item label="确认密码" required><el-input v-model="onboarding.confirmPassword" type="password" show-password minlength="8" maxlength="64" autocomplete="new-password"/></el-form-item></div><el-checkbox v-model="onboarding.agreed">我确认资料真实，并同意平台审核后创建独立租户空间</el-checkbox><el-button class="onboarding-submit" type="primary" native-type="submit" :loading="onboardingLoading">提交入驻申请</el-button></el-form>
    </el-dialog>
  </template>

  <div v-else class="erp-shell">
    <aside class="sidebar">
      <div class="brand"><span class="brand-mark">S</span><div><strong>商户经营台</strong><small>SMART ERP CONSOLE</small></div></div>
      <section class="nav-group"><label>工作空间</label><button :class="{active:page==='overview'}" @click="page='overview'"><i>◈</i>经营总览</button><button v-if="can('merchant:store:view')" :class="{active:page==='stores'}" @click="page='stores'"><i>▦</i>门店管理</button><button v-if="can('merchant:inventory:view')&&me?.dataScope==='TENANT_ALL'" :class="{active:page==='inventory'}" @click="page='inventory'"><i>▦</i>商品与库存</button><button v-if="can('merchant:order:view')" :class="{active:page==='orders'}" @click="page='orders'"><i>▤</i>订单与营收</button><button v-if="can('merchant:member:view')||can('merchant:coupon:view')" :class="{active:page==='members'}" @click="page='members'"><i>♧</i>会员与营销</button><button v-if="can('merchant:store:manage')&&me?.dataScope==='TENANT_ALL'" :class="{active:page==='consumer'}" @click="page='consumer'"><i>⌂</i>消费者商城</button></section>
      <div class="sidebar-tip"><small>总部经营中心</small><p>多店协同 · 数据洞察</p><span>统一管理品牌旗下门店</span></div>
      <div class="account"><span>{{me?.displayName?.slice(0,1)??'管'}}</span><div><strong>{{me?.displayName??'租户负责人'}}</strong><small>总部管理员</small></div><button @click="logout">退出</button></div>
    </aside>

    <section class="workspace">
      <header class="topbar">
        <el-select v-model="selectedStoreId" class="store-select"><el-option label="全部门店" :value="0"/><el-option v-for="s in stores" :key="s.id" :label="s.storeName" :value="s.id"/></el-select>
        <div class="top-meta"><el-button v-if="can('merchant:store:manage')&&me?.dataScope==='TENANT_ALL'" type="primary" plain @click="openPlans">升级套餐</el-button><span>租户 {{me?.tenantId}}</span><span class="refresh-note">↻ 数据刷新于 {{updatedAt}}</span><el-button link :loading="dataLoading" @click="reload">刷新数据</el-button></div>
      </header>

      <div class="content" v-loading="dataLoading">
        <el-alert v-if="loadError" :title="loadError" type="error" :closable="false" show-icon/>
        <LowStockNotice :scope-key="`merchant-web:${me?.tenantId}:${me?.userId}`" :alerts="alerts" :error="alertError" :updated="alertUpdated" tenant @inventory="page='inventory'" @refresh="refreshAlerts"/>
        <ConsumerSettings v-if="page==='consumer'" @changed="reload"/><TenantInventory v-else-if="page==='inventory'" :stores="stores" :store-id="selectedStoreId" :can-manage="Boolean(can('merchant:inventory:manage'))" :can-product-manage="Boolean(can('merchant:product:manage'))" :can-product-view="Boolean(can('merchant:product:view'))" @changed="reload"/>
        <BusinessOverview v-else-if="page==='overview'" :stores="stores" :orders="orders" :store-id="selectedStoreId" :revision="revision" :permitted="Boolean(can('merchant:dashboard:view'))" :low-stock="alerts.filter(a=>!selectedStoreId||a.storeId===selectedStoreId).length" @orders="page='orders'" @stores="page='stores'"/>
        <template v-else-if="page==='stores'">
          <div class="page-heading"><div><p class="eyebrow">STORE NETWORK</p><h1>门店管理</h1><p>门店档案、营业状态、登录账号与功能授权，一处维护。</p></div><el-button v-if="can('merchant:store:manage')" type="primary" :disabled="!quota.canCreate" @click="openStore()">＋ 添加门店</el-button></div>
          <el-alert v-if="!quota.canCreate" :title="`门店额度已用完（${quota.used}/${quota.limit}），升级套餐可增加门店额度。`" type="warning" :closable="false"><el-button v-if="can('merchant:store:manage')&&me?.dataScope==='TENANT_ALL'" link type="primary" @click="openPlans">升级套餐</el-button></el-alert>
          <section class="metric-grid"><article class="metric"><div>门店总数 / 额度</div><strong>{{quota.used}} <small>/ {{quota.limit??'不限'}}</small></strong><p>品牌旗下门店</p></article><article class="metric"><div>营业门店</div><strong>{{stores.filter(s=>s.status==='ACTIVE').length}}</strong><p>当前正常营业</p></article><article class="metric"><div>已停用门店</div><strong>{{stores.filter(s=>s.status!=='ACTIVE').length}}</strong><p>可在档案中恢复营业</p></article><article class="metric"><div>已配置账号</div><strong>{{accounts.length}} <small>/ {{stores.length}}</small></strong><p>门店独立登录账号</p></article></section>
          <div class="panel"><div class="filter-bar compact"><el-input v-model="storeSearch" placeholder="搜索门店、编码、地址或账号" clearable/><el-select v-model="storeStatus" placeholder="全部营业状态" clearable><el-option label="营业中" value="ACTIVE"/><el-option label="已停用" value="INACTIVE"/></el-select><span class="subtle">{{filteredStores.length}} 家门店</span></div>
            <el-table :data="filteredStores" empty-text="暂无符合条件的门店" stripe><el-table-column label="门店档案" min-width="160"><template #default="s"><div class="store-cell"><span>{{s.row.storeName.slice(0,1)}}</span><div><b>{{s.row.storeName}}</b><small>{{s.row.storeCode}} · <span :style="{color:s.row.status==='ACTIVE'?'#17a785':'#98a5b8'}">{{s.row.status==='ACTIVE'?'营业中':'已停用'}}</span></small></div></div></template></el-table-column><el-table-column label="地址 / 营业时间" min-width="185"><template #default="s"><div class="cell-stack"><span>{{s.row.address||'待完善地址'}}</span><small>{{s.row.businessHours||'待设置营业时间'}}</small></div></template></el-table-column><el-table-column v-if="can('iam:user:manage')" label="登录账号 / 管理员" min-width="145"><template #default="s"><div class="cell-stack"><b>{{accounts.find(a=>a.storeId===s.row.id)?.username??'尚未配置'}}</b><small>{{accounts.find(a=>a.storeId===s.row.id)?.displayName??'点击配置账号'}}</small></div></template></el-table-column><el-table-column v-if="can('iam:user:manage')" label="登录密码" min-width="110"><template #default="s"><div class="cell-stack"><StorePassword v-if="accounts.some(a=>a.storeId===s.row.id)" :key="`${s.row.id}-${revision}`" :store-id="s.row.id"/><span v-else>未设置</span><el-button link type="primary" @click="manageAccount(s.row)">{{accounts.some(a=>a.storeId===s.row.id)?'修改账号':'配置账号'}}</el-button></div></template></el-table-column><el-table-column label="经营情况" min-width="130"><template #default="s"><div class="cell-stack"><span>{{overviews.find(o=>o.store.id===s.row.id)?.completedOrders??0}} 笔已核销</span><small>核销原价 {{money(overviews.find(o=>o.store.id===s.row.id)?.revenueCents??0)}}</small><small>低库存 {{alerts.filter(a=>a.storeId===s.row.id).length}} 项</small></div></template></el-table-column><el-table-column v-if="can('iam:user:manage')" label="账号权限" width="115"><template #default="s"><el-button link type="primary" @click="permissionStore=s.row">账号权限</el-button><div class="cell-stack"><small>本店账号授权</small></div></template></el-table-column><el-table-column v-if="can('merchant:store:manage')" label="操作" width="110" fixed="right"><template #default="s"><el-button link type="primary" @click="openStore(s.row)">编辑档案</el-button><el-button link type="primary" @click="configurationStore=s.row">门店配置</el-button><el-button link :type="s.row.status==='ACTIVE'?'warning':'success'" @click="toggleStore(s.row)">{{s.row.status==='ACTIVE'?'停用':'恢复'}}</el-button></template></el-table-column></el-table>
            <p class="subtle table-footnote">密码默认隐藏，点击小眼睛查看，30 秒后或离开窗口自动隐藏；旧账号需先重新设置一次密码才能查看。可通过“修改账号”更改账号名称及密码。</p>
          </div>
        </template>
        <MembersMarketing v-else-if="page==='members'" :permissions="me?.permissions??[]"/>
        <OrdersRevenue v-else :orders="orders" :stores="stores" :store-id="selectedStoreId" :revision="revision" :finance-allowed="Boolean(can('merchant:finance:view'))"/>
      </div>
    </section>

    <el-drawer :model-value="!!configurationStore" title="独立门店配置" size="min(760px,100vw)" @close="configurationStore=null"><StorefrontSettings v-if="configurationStore" :initial-store-id="String(configurationStore.id)" @changed="reload"/></el-drawer>
    <el-drawer v-model="createVisible" :title="editStore?'编辑门店档案':'添加新门店'" size="min(460px, 100vw)"><p class="drawer-tip">添加门店后将继续设置登录账号与功能权限。</p><el-form label-position="top"><el-form-item label="门店编码"><el-input v-model="newStore.storeCode" :disabled="Boolean(editStore)" placeholder="例如 SH-001"/></el-form-item><el-form-item label="门店名称"><el-input v-model="newStore.storeName"/></el-form-item><el-form-item label="详细地址"><el-input v-model="newStore.address" type="textarea" :rows="3"/></el-form-item><el-form-item label="营业时间"><el-input v-model="newStore.businessHours" placeholder="09:00-22:00"/></el-form-item><el-button type="primary" size="large" class="submit-store" :loading="saving" @click="createStore">{{editStore?'保存修改':can('iam:user:manage')?'下一步：配置账号与权限':'确认添加'}}</el-button></el-form></el-drawer>
    <el-drawer v-model="planVisible" title="套餐管理" size="min(480px, 100vw)"><div v-loading="planLoading"><el-alert v-if="planError" :title="planError" type="error" :closable="false"/><template v-else-if="currentPlan"><h3>当前套餐：{{currentPlan.planName}}</h3><p>门店额度：{{currentPlan.storeQuota??'不限'}} · 已使用 {{quota.used}}</p><p class="drawer-tip">选择更高套餐，确认后立即生效，无需联系管理员。</p><el-empty v-if="!upgradePlans.length" description="当前已无可升级套餐"/><el-card v-for="plan in upgradePlans" :key="plan.planCode" style="margin-top:16px"><h3>{{plan.planName}}</h3><p>门店额度：{{plan.storeQuota??'不限'}}</p><el-button type="primary" :loading="upgrading" :disabled="upgrading" @click="upgrade(plan)">升级至{{plan.planName}}</el-button></el-card></template></div></el-drawer>
    <StorePermissions :store="permissionStore" @close="permissionStore=null" @saved="reload"/>
    <el-drawer v-model="accountVisible" :title="accountMode==='create'?'创建门店独立账号':'修改门店账号'" size="min(460px, 100vw)" @closed="accountForm.password=''"><p class="drawer-tip">账号绑定后只能登录所属门店 ERP，无法切换或查看其他门店。</p><el-form label-position="top"><el-form-item label="登录账号"><el-input v-model="accountForm.username"/></el-form-item><el-form-item label="账号名称"><el-input v-model="accountForm.displayName"/></el-form-item><el-form-item label="登录密码"><el-input v-model="accountForm.password" type="password" show-password :placeholder="accountMode==='edit'?'留空保留原密码，填写则修改密码':'8 至 64 位'"/></el-form-item><el-button type="primary" size="large" class="submit-store" :loading="saving" @click="saveAccount">{{accountMode==='create'?'创建并绑定门店':'保存修改'}}</el-button></el-form></el-drawer>
  </div>
</template>



