import { enterRealStore } from './marketplace-helper'
import { test, expect } from '@playwright/test'
test('real profile, address CRUD, favorites, feedback, persistence and service boundaries', async ({ page, request }) => {
  test.setTimeout(90000)
  const tenant=process.env.H5_E2E_TENANT
  test.skip(!tenant,'Requires isolated H5_E2E_TENANT verification brand')
  const base='http://127.0.0.1:8080/api/consumer/v1'
  const mobile=`136${Date.now().toString().slice(-8)}`
  const feedbackMessage='H5反馈验收-'+mobile
  const session=await request.post(`${base}/auth/account/register`,{data:{tenantId:tenant,mobile,memberName:'会员验收',password:'Consumer-H5!2026'}})
  expect(session.ok()).toBe(true)
  const account=await session.json()
  const membership=await request.post(`${base}/auth/account/enter`,{headers:{Authorization:`Bearer ${account.accessToken}`},data:{tenantId:tenant,join:true}})
  expect(membership.ok()).toBe(true)
  const token=(await membership.json()).accessToken
  const headers={Authorization:`Bearer ${token}`}
  await page.addInitScript(account=>sessionStorage.setItem('consumer.account',JSON.stringify(account)),account)
  await enterRealStore(page,tenant!,'account')
  await expect(page.getByRole('heading',{name:'会员验收',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'账户设置',exact:true}).click()
  await page.getByLabel('昵称',{exact:true}).fill('小叶真实账户')
  await page.getByLabel('显示订单消息').uncheck()
  await page.getByRole('button',{name:'保存设置'}).click()
  await expect(page.getByRole('heading',{name:'小叶真实账户',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'收货地址',exact:true}).click()
  await page.getByRole('button',{name:'新增收货地址'}).click()
  await page.getByLabel('收货人',{exact:true}).fill('测试收货人')
  await page.getByLabel('详细地址',{exact:true}).fill('杭州市验收路 100 号')
  await page.getByRole('button',{name:'保存地址',exact:true}).click()
  await expect(page.getByRole('heading',{name:'杭州市验收路 100 号'})).toBeVisible()
  await page.getByRole('button',{name:'编辑地址'}).click()
  await page.getByLabel('详细地址',{exact:true}).fill('杭州市验收路 200 号')
  await page.getByRole('button',{name:'保存地址',exact:true}).click()
  await expect(page.getByRole('heading',{name:'杭州市验收路 200 号'})).toBeVisible()
  await enterRealStore(page,tenant!,'account')
  await page.getByRole('button',{name:'收货地址',exact:true}).click()
  await expect(page.getByRole('heading',{name:'杭州市验收路 200 号'})).toBeVisible()
  await page.getByRole('button',{name:'删除地址'}).click()
  await expect(page.getByText('还没有收货地址',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'关闭功能面板'}).click()
  await page.getByRole('button',{name:'帮助与反馈',exact:true}).click()
  await page.getByLabel('意见反馈').fill(feedbackMessage)
  await page.getByRole('button',{name:'提交反馈'}).click()
  await expect(page.getByText(feedbackMessage,{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'关闭功能面板'}).click()
  await page.getByRole('button',{name:'订单消息',exact:true}).click()
  await expect(page.getByText('订单消息已关闭，可在账户设置中开启。')).toBeVisible()
  await page.getByRole('button',{name:'关闭功能面板'}).click()
  await page.getByRole('navigation',{name:'店铺功能'}).getByRole('button',{name:'全部商品',exact:true}).click()
  await page.locator('.product-title-button').first().click()
  await expect(page.getByRole('dialog',{name:'商品规格'})).toBeVisible()
  await page.getByRole('button',{name:'收藏商品',exact:true}).click()
  await expect(page.getByRole('button',{name:'取消收藏',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'关闭规格'}).click()
  await enterRealStore(page,tenant!,'account')
  await page.getByRole('navigation',{name:'店铺功能'}).getByRole('button',{name:'商家会员',exact:true}).click()
  await page.getByRole('button',{name:'我的收藏',exact:true}).click()
  await expect(page.getByRole('button',{name:'选规格',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'取消收藏',exact:true}).click()
  await expect(page.getByText('当前门店暂无收藏商品')).toBeVisible()
  await page.getByRole('button',{name:'关闭功能面板'}).click()
  for(const label of ['礼品卡','在线充值']) {
    await expect(page.getByRole('button',{name:label,exact:true})).toHaveCount(0)
  }
  const profile=await request.get(`${base}/profile`,{headers})
  expect(await profile.json()).toEqual({name:'小叶真实账户',notifications:false})
  expect(await (await request.get(`${base}/profile/addresses`,{headers})).json()).toEqual([])
  expect(await (await request.get(`${base}/profile/favorites`,{headers})).json()).toEqual([])
  expect((await (await request.get(`${base}/profile/feedback`,{headers})).json())[0].content).toBe(feedbackMessage)
  const stores=await(await request.get(`${base}/catalog/tenants/${tenant}/stores`)).json()
  const suffix=process.env.H5_E2E_SUFFIX||stores[0].storeCode.replace('A-','')
  const owner=await request.post('http://127.0.0.1:8080/api/auth/v1/login',{data:{username:`139${suffix.slice(-8)}`,password:'M3-Test!2026'}})
  expect(owner.ok()).toBe(true)
  const ownerToken=(await owner.json()).accessToken
  const merchantBase='http://127.0.0.1:8080/api/merchant/v1/consumer-feedback'
  const feedbackId=(await(await request.get(`${base}/profile/feedback`,{headers})).json())[0].id
  expect((await request.get(merchantBase,{headers})).status()).toBe(403)
  const inbox=await request.get(merchantBase,{headers:{Authorization:`Bearer ${ownerToken}`}})
  expect(inbox.ok()).toBe(true)
  expect((await inbox.json()).some((f:any)=>f.id===feedbackId)).toBe(true)
  const merchant=await page.context().newPage()
  await merchant.addInitScript(token=>{if(location.port==='5174')localStorage.setItem('saas.accessToken',token)},ownerToken)
  await merchant.goto('http://127.0.0.1:5174/')
  await merchant.getByRole('button',{name:/消费者商城/}).click()
  await merchant.getByRole('button',{name:'加载 / 刷新反馈',exact:true}).click()
  const feedbackRow=merchant.getByRole('row').filter({hasText:feedbackMessage})
  await feedbackRow.getByRole('button',{name:'标记已处理',exact:true}).click()
  await expect(feedbackRow).toContainText('已处理')
  await merchant.close()
  await page.getByRole('button',{name:'帮助与反馈',exact:true}).click()
  await expect(page.locator('.address-row').filter({hasText:feedbackMessage})).toContainText('已处理')
  await page.getByRole('button',{name:'关闭功能面板'}).click()
  for(const width of [320,390]) {
    await page.setViewportSize({width,height:844})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  }
  await page.screenshot({path:'apps/consumer-web/qa/connected-account.png'})
  await page.getByRole('button',{name:'退出登录',exact:true}).click()
  await enterRealStore(page,tenant!)
  await page.getByRole('navigation',{name:'店铺功能'}).getByRole('button',{name:'商家会员',exact:true}).click()
  await expect(page.getByRole('button',{name:'登录 / 注册',exact:true})).toBeVisible()
})

