import { test, expect } from '@playwright/test'

test('store switching keeps independent carts and delivery totals', async ({ page }) => {
  await page.goto('/?preview=1#shop')
  await page.getByRole('button', { name: '选规格 云顶抹茶拿铁', exact: true }).click()
  await page.getByRole('button', { name: '加入购物袋 · ¥22' }).click()
  await page.locator('.shop-store > button').click()
  await page.locator('.store-choice').nth(1).getByRole('button').click()
  await page.getByRole('button', { name: '确认切换门店' }).click()
  await expect(page.getByRole('button', { name: '去结算', exact: true })).toBeDisabled()
  await page.locator('.shop-store > button').click()
  await page.locator('.store-choice').first().getByRole('button').click()
  await expect(page.locator('.bag-summary')).toContainText('¥22')
  await page.getByRole('button', { name: '外送', exact: true }).click()
  await page.getByRole('button', { name: '去结算', exact: true }).click()
  await expect(page.locator('.checkout-bottom')).toContainText('¥22')
  await expect(page.locator('.receipt-row').filter({ hasText: '配送费' })).toContainText('¥6')
})

test('independent preview supports customized purchase and repeat order', async ({ page }) => {
  const api: string[] = []
  page.on('request', r => { if (r.url().includes('/api/')) api.push(r.url()) })
  await page.goto('/?preview=1')
  await expect(page.getByRole('heading', { name: '把春天 喝进日常。' })).toBeVisible()
  await page.screenshot({ path: 'apps/consumer-web/qa/prototype-home.png', fullPage: true })
  await page.getByRole('button', { name: /到店自取 提前点/ }).click()
  await page.getByRole('button', { name: '选规格 云顶抹茶拿铁', exact: true }).click()
  await page.getByRole('button', { name: /超大杯/ }).click()
  await page.getByRole('button', { name: /轻芝士奶盖/ }).click()
  await page.getByRole('button', { name: '收藏饮品' }).click()
  await page.getByRole('button', { name: '增加数量', exact: true }).click()
  await page.screenshot({ path: 'apps/consumer-web/qa/prototype-options.png', fullPage: true })
  await page.getByRole('button', { name: '加入购物袋 · ¥58' }).click()
  await page.getByRole('button', { name: '去结算', exact: true }).click()
  await expect(page.locator('.checkout-bottom')).toContainText('¥52')
  await page.getByRole('button', { name: '确认下单', exact: true }).click()
  await page.getByRole('button', { name: '确认体验下单' }).click()
  await expect(page.getByText('Y101', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '确认已取餐' }).click()
  await page.getByRole('button', { name: '再来一单' }).click()
  await page.reload()
  await expect(page.locator('.bag-summary')).toContainText('¥58')
  expect(api).toEqual([])
})

test('member, address, coupons and responsive screens persist locally', async ({ page }) => {
  await page.goto('/?preview=1#addresses')
  await page.getByRole('button', { name: '新增收货地址' }).click()
  await page.getByLabel('联系人', { exact: true }).fill('测试用户')
  await page.getByLabel('手机号', { exact: true }).fill('13800000001')
  await page.getByLabel('详细地址').fill('杭州市测试路 100 号')
  await page.getByRole('button', { name: '保存地址', exact: true }).click()
  await page.reload()
  await expect(page.getByText('杭州市测试路 100 号', { exact: true })).toBeVisible()
  await page.goto('/?preview=1#coupons')
  await page.getByRole('button', { name: '领取', exact: true }).click()
  await expect(page.getByRole('button', { name: '已领取', exact: true })).toBeDisabled()
  await page.goto('/?preview=1#points')
  await page.getByRole('button', { name: '立即兑换', exact: true }).first().click()
  await expect(page.locator('.points-hero strong')).toHaveText('48')
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    for (const route of ['home','shop','me','stores','orders','gift','help','balance']) {
      await page.goto('/?preview=1#' + route)
      await expect(page.locator('main')).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${route} width ${width}`).toBe(true)
      if (width === 390 && ['shop','me'].includes(route)) await page.screenshot({ path: `apps/consumer-web/qa/prototype-${route}.png`, fullPage: true })
    }
  }
})
