import { test, expect, type Page } from '@playwright/test'

async function fixture(page: Page, existing = false) {
  const calls: { path: string; token: string; body: any }[] = []
  const bound = new Set(existing ? ['61', '62', '63'] : [])
  let failed = true
  await page.addInitScript(() => {
    localStorage.setItem('marketplace.visits', JSON.stringify([{ tenantId: '99', id: '991', storeName: '其他账号逛过的店', address: '' }]))
    sessionStorage.setItem('consumer.session:99', JSON.stringify('stale-other-owner'))
  })
  const store = (tenant: string) => ({ id: `${tenant}1`, tenantId: tenant, storeName: `${tenant}号邻里店`, address: '邻里路1号', businessHours: '09:00–21:00', city: '杭州', district: '西湖', coverUrl: '', pickupEnabled: true, shippingEnabled: false, distanceKm: null })
  const order = (id: number, tenant: string) => ({ id: String(id), orderNo: `订单${id}`, storeId: `${tenant}1`, status: 'PENDING_PAYMENT', totalQuantity: 1, payableAmountCents: 1000, totalAmountCents: 1000, items: [{ productName: `商品${id}`, skuName: '标准', quantity: 1 }], customerMobile: '13800138000' })
  await page.route('**/api/consumer/v1/**', async route => {
    const req = route.request(), url = new URL(req.url()), path = url.pathname.replace('/api/consumer/v1', '')
    const token = req.headers().authorization || '', body = req.method() === 'POST' ? req.postDataJSON() : undefined
    calls.push({ path, token, body })
    const send = (data: any, status = 200) => route.fulfill({ status, json: data })
    if (path === '/auth/account/login' || path === '/auth/account/register') return send({ accessToken: body.mobile==='13900139000'?'global-second':'global-owner', expiresIn: 7200, mobile: body.mobile, displayName: body.mobile==='13900139000'?'阿新':'小邻' })
    if (path === '/auth/account/memberships') return send([...(token==='Bearer global-second'?[]:bound)].map(tenantId => ({ tenantId, memberId: `${tenantId}01`, memberName: '小邻', status: 'ACTIVE' })))
    if (path === '/auth/account/activate' || path === '/auth/account/logout') return send({verified:true})
    if (path === '/auth/account/privacy') return send({historyEnabled:true})
    if (path === '/auth/account/addresses') return send([])
    if (path.startsWith('/auth/account/history')) return send([])
    if (path === '/auth/account/me' || path === '/auth/account/password') return send({ changed: true })
    if (path === '/auth/account/enter') {
      if (body.tenantId === '63' && failed) return send({ detail: '品牌暂不可用' }, 404)
      bound.add(body.tenantId)
      return send({ accessToken: `member-${body.tenantId}`, expiresIn: 7200, member: true })
    }
    if (path === '/catalog/stores') return send(['61', '62'].map(store))
    if (path.endsWith('/brand')) return send({ displayName: `${path.split('/')[3]}号邻里店`, contactPhone: '' })
    if (path.endsWith('/products')) return send({ store: store(path.split('/')[3]), products: [] })
    if (path.endsWith('/fulfillment')) return send({ pickupEnabled: true, shippingEnabled: false, pickupOnlySkus: [], excludedProvinces: [] })
    if (path.startsWith('/catalog/tenants/') && path.endsWith('/stores')) return send([store(path.split('/')[3])])
    if (path === '/wallet') return send({ id: '6101', mobile: '13800138000', memberName: '小邻', availablePoints: 0, storedValueCents: 0 })
    if (path === '/orders/capabilities') return send({ simulatedPaymentEnabled: false })
    if (path === '/profile') return send({ memberName: '小邻', notifications: true })
    if (path === '/orders') {
      const tenant = token.replace('Bearer member-', '')
      return send(url.searchParams.get('page') === '0'
        ? tenant === '61' ? Array.from({ length: 20 }, (_, i) => order(1000 - i, tenant)) : [order(2000 + Number(tenant), tenant)]
        : [order(800, tenant)])
    }
    if (path.startsWith('/orders/')) return send(order(Number(path.split('/')[2]), '62'))
    return send([])
  })
  return { calls, bound, recover: () => { failed = false } }
}
async function login(page: Page) {
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '我的', exact: true }).click()
  await page.getByRole('button', { name: '登录 / 注册', exact: true }).click()
  await page.getByLabel('手机号', { exact: true }).fill('13800138000')
  await page.getByLabel('密码', { exact: true }).fill('Unified!12345')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '小邻', exact: true })).toBeVisible()
}

async function addSecondAccount(page:Page) {
  await page.getByRole('button',{name:'切换账号',exact:true}).click()
  await page.getByRole('button',{name:'＋ 添加账号'}).click()
  await page.getByLabel('手机号',{exact:true}).fill('13900139000')
  await page.getByLabel('密码',{exact:true}).fill('Second!12345')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.getByRole('heading',{name:'阿新'})).toBeVisible()
}

test('history searches merchants and products, paginates, filters time and opens the actual SKU',async({page})=>{
  const {calls}=await fixture(page)
  const entry=(n:number)=>({tenantId:'61',storeId:'611',skuId:String(6100+n),merchantName:'悦享百货',storeName:'中心店',productName:`原味燕麦片${n}`,skuName:'500g',imageUrl:'',priceCents:1990,viewedAt:'2026-09-11T08:00:00'})
  const queries:URL[]=[]
  await page.route('**/api/consumer/v1/auth/account/history?*',route=>{const url=new URL(route.request().url());queries.push(url);return route.fulfill({json:url.searchParams.get('search')?[entry(1)]:url.searchParams.get('page')==='1'?[entry(31)]:Array.from({length:30},(_,i)=>entry(i+1))})})
  await page.route('**/api/consumer/v1/catalog/tenants/61/stores/611/products',route=>route.fulfill({json:{store:{id:'611',storeName:'中心店',address:'邻里路1号'},products:[{categoryId:'1',categoryName:'粮油',spuId:'1',productName:'原味燕麦片1',skuName:'500g',skuId:'6101',effectivePriceCents:2090,availableQuantity:10,selectable:true,imageUrl:''}]}}))
  await page.goto('/');await login(page);await page.getByRole('button',{name:/浏览足迹/}).click()
  await expect(page.locator('.history-row')).toHaveCount(30)
  await page.getByRole('button',{name:'加载更多足迹'}).click();await expect(page.locator('.history-row')).toHaveCount(31)
  await page.getByLabel('足迹时间范围').selectOption('7')
  await expect.poll(()=>queries.at(-1)?.searchParams.get('days')).toBe('7')
  await page.getByLabel('搜索浏览足迹').fill('燕麦');await page.getByRole('button',{name:'搜索',exact:true}).click()
  await expect(page.locator('.history-row')).toHaveCount(1)
  expect(queries.at(-1)?.searchParams.get('search')).toBe('燕麦')
  await page.screenshot({path:'apps/consumer-web/qa/account-history-mobile.png'})
  await page.locator('.history-row').click()
  await expect(page.getByRole('dialog',{name:'商品规格'})).toBeVisible()
  await expect(page.getByRole('dialog',{name:'商品规格'})).toContainText('¥20.90')
  await expect.poll(()=>calls.filter(c=>c.path==='/auth/account/history'&&c.body?.skuId==='6101').length).toBe(1)
})

test('saved accounts isolate carts and visits; cancelling account addition preserves login',async({page})=>{
  const {calls}=await fixture(page,true)
  await page.goto('/');await login(page)
  await page.evaluate(()=>{
    localStorage.setItem('consumer.owner:13800138000:visits',JSON.stringify([{tenantId:'61',id:'611',storeName:'小邻专属购物车',address:''}]))
    localStorage.setItem('consumer.owner:13800138000:cart:61:611',JSON.stringify({'6111':2}))
  })
  await page.getByRole('button',{name:'切换账号',exact:true}).click();await page.getByRole('button',{name:'＋ 添加账号'}).click()
  await page.getByRole('button',{name:'关闭登录'}).click()
  await expect(page.getByRole('heading',{name:'小邻',exact:true})).toBeVisible()
  expect(calls.some(c=>c.path==='/auth/account/logout')).toBe(false)
  await addSecondAccount(page)
  await page.getByRole('navigation',{name:'平台导航'}).getByRole('button',{name:'购物车',exact:true}).click()
  await expect(page.getByText('购物车还空着')).toBeVisible()
  await expect(page.getByText('小邻专属购物车')).toHaveCount(0)
  await page.getByRole('navigation',{name:'平台导航'}).getByRole('button',{name:'我的',exact:true}).click()
  await page.getByRole('button',{name:'切换账号',exact:true}).click();await page.getByRole('button',{name:/小邻/}).click()
  await expect(page.getByRole('heading',{name:'小邻',exact:true})).toBeVisible()
  expect(calls.filter(c=>c.path==='/auth/account/activate').at(-1)?.token).toBe('Bearer global-owner')
  await page.getByRole('navigation',{name:'平台导航'}).getByRole('button',{name:'购物车',exact:true}).click()
  await expect(page.getByText('小邻专属购物车')).toBeVisible()
  await expect(page.getByText('已选 2 件 · 进店核对价格与库存')).toBeVisible()
})

test('server expiry requires password even when the saved client timestamp is fresh',async({page})=>{
  await fixture(page,true)
  await page.goto('/');await login(page);await addSecondAccount(page)
  await page.route('**/api/consumer/v1/auth/account/activate',route=>route.fulfill({status:401,json:{detail:'需要重新验证'}}))
  await page.getByRole('button',{name:'切换账号',exact:true}).click();await page.getByRole('button',{name:/小邻/}).click()
  await expect(page.getByRole('heading',{name:'验证身份'})).toBeVisible()
  expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('consumer.account.active')||'null'))).toBe('13900139000')
  await page.getByRole('button',{name:'返回'}).click()
  await expect(page.getByRole('heading',{name:'阿新'})).toBeVisible()
})

test('password errors preserve login and privacy preferences have a working control',async({page})=>{
  await fixture(page)
  const writes:any[]=[]
  await page.route('**/api/consumer/v1/auth/account/privacy',route=>{const body=route.request().postDataJSON();if(body)writes.push(body);return route.fulfill({json:{historyEnabled:body?.historyEnabled??true}})})
  await page.route('**/api/consumer/v1/auth/account/password',route=>route.fulfill({status:401,json:{detail:'当前密码错误'}}))
  await page.goto('/');await login(page)
  await page.getByRole('button',{name:'账户设置'}).click();await page.getByRole('button',{name:/登录密码/}).click()
  await page.getByLabel('当前密码').fill('wrong');await page.getByLabel('新密码').fill('Changed!12345');await page.getByRole('button',{name:'确认修改'}).click()
  await expect(page.getByRole('alert')).toHaveText('当前密码错误')
  await page.getByRole('button',{name:'返回'}).click();await expect(page.getByRole('heading',{name:'小邻',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'账户设置'}).click();await page.getByRole('button',{name:/隐私与数据/}).click()
  await page.getByLabel('记录我的商品浏览足迹').uncheck()
  await expect.poll(()=>writes.length).toBe(1);expect(writes[0]).toEqual({historyEnabled:false})
})

test('one login automatically establishes both memberships and logout clears old sessions', async ({ page }) => {
  const { calls, bound } = await fixture(page)
  await page.goto('/')
  await login(page)
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '首页', exact: true }).click()
  await page.locator('.market-store[data-tenant-id="61"]').click()
  await expect.poll(() => bound.has('61')).toBe(true)
  await expect(page.getByRole('dialog', { name: '消费者登录' })).toHaveCount(0)
  await page.goto('/')
  await page.locator('.market-store[data-tenant-id="62"]').click()
  await expect.poll(() => bound.has('62')).toBe(true)
  expect(calls.filter(c => c.path === '/auth/account/login')).toHaveLength(1)
  expect(calls.filter(c => c.path === '/auth/account/enter').every(c => c.token === 'Bearer global-owner')).toBe(true)
  await page.goto('/')
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '我的', exact: true }).click()
  await page.getByRole('button',{name:/商家会员/}).click()
  await expect(page.getByText('61号邻里店',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'返回'}).click()
  await page.screenshot({ path: 'apps/consumer-web/qa/unified-account-mobile.png', fullPage: true })
  await page.getByRole('button',{name:'账户设置'}).click()
  await page.getByRole('button',{name:/退出当前账号/}).click()
  await expect(page.getByRole('button', { name: '登录 / 注册', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.keys(sessionStorage).filter(k => k.startsWith('consumer.session:')))).toEqual([])
})

test('orders use server memberships, isolate failure, paginate, and clear on logout', async ({ page }) => {
  const { calls, recover } = await fixture(page, true)
  await page.goto('/')
  await login(page)
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '订单', exact: true }).click()
  await expect(page.getByText('订单2062', { exact: true })).toBeVisible()
  await expect(page.getByText(/63号邻里店：品牌暂不可用/)).toBeVisible()
  expect(calls.filter(c => c.path === '/orders').every(c => ['Bearer member-61', 'Bearer member-62'].includes(c.token))).toBe(true)
  expect(calls.some(c => c.token.includes('stale-other-owner'))).toBe(false)
  const cards = page.locator('.market-visit').filter({ has: page.locator('small') })
  await expect(cards.first()).toContainText('订单2062')
  await page.screenshot({ path: 'apps/consumer-web/qa/unified-orders-mobile.png', fullPage: true })
  recover()
  await page.getByRole('button', { name: '加载更多 / 重试失败商家' }).click()
  await expect(page.getByText('订单800', { exact: true })).toBeVisible()
  await expect(page.getByText('订单2063', { exact: true })).toBeVisible()
  await expect(page.getByText('订单2062', { exact: true })).toHaveCount(1)
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '我的', exact: true }).click()
  await page.getByRole('button',{name:'账户设置'}).click()
  await page.getByRole('button',{name:/退出当前账号/}).click()
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '订单', exact: true }).click()
  await expect(page.getByText('订单2062', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '登录 / 注册', exact: true })).toBeVisible()
})

test('legacy membership asks for proof without losing the unified login', async ({ page }) => {
  const { calls } = await fixture(page)
  let linked = false
  await page.route('**/api/consumer/v1/auth/account/enter', async route => {
    const body = route.request().postDataJSON()
    if (!body.join) return route.fulfill({ json: { accessToken: 'shopper-61', expiresIn: 7200, member: false } })
    if (!linked && !body.legacyPassword) return route.fulfill({ status: 409, json: { detail: '已有商家会员，请验证原商家密码关联' } })
    if (!linked && body.legacyPassword !== 'Original!12345') return route.fulfill({ status: 401, json: { detail: '原商家密码错误' } })
    linked = true
    return route.fulfill({ json: { accessToken: 'member-61', expiresIn: 7200, member: true } })
  })
  await page.goto('/')
  await login(page)
  await page.getByRole('navigation', { name: '平台导航' }).getByRole('button', { name: '首页', exact: true }).click()
  await page.locator('.market-store[data-tenant-id="61"]').click()
  await page.getByRole('navigation',{name:'店铺功能'}).getByRole('button',{name:'商家会员',exact:true}).click()
  await page.getByRole('button',{name:'自愿加入商家会员',exact:true}).click()
  await page.getByLabel('原商家密码', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: '验证并关联', exact: true }).click()
  await expect(page.getByText('原商家密码错误', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(sessionStorage.getItem('consumer.accounts.v2') || '[]')[0].accessToken)).toBe('global-owner')
  await page.getByLabel('原商家密码', { exact: true }).fill('Original!12345')
  await page.getByRole('button', { name: '验证并关联', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '消费者登录' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('dialog', { name: '消费者登录' })).toHaveCount(0)
  expect(calls.filter(c => c.path === '/auth/account/login')).toHaveLength(1)
})

test('account center manages global addresses, history, and protected account switching',async({page})=>{
  const {calls}=await fixture(page,true)
  const addresses:any[]=[]
  const history=[{tenantId:'61',storeId:'611',skuId:'6111',merchantName:'悦享百货',storeName:'中心店',productName:'原味燕麦片',skuName:'500g',imageUrl:'',priceCents:1990,viewedAt:'2026-09-10T20:10:00'}]
  await page.route('**/api/consumer/v1/auth/account/addresses',async route=>{const body=route.request().method()==='POST'?route.request().postDataJSON():null;if(body){addresses.splice(0,addresses.length,{...body,id:'1',isDefault:true})}return route.fulfill({json:addresses})})
  await page.route('**/api/consumer/v1/auth/account/history?*',route=>route.fulfill({json:history}))
  await page.goto('/');await login(page)
  await page.getByRole('button',{name:/收货地址/}).click();await page.getByRole('button',{name:'＋ 新增收货地址'}).click()
  await page.getByLabel('收货人').fill('小邻');await page.getByLabel('手机号').fill('13800138000');await page.getByLabel('省份').fill('浙江省');await page.getByLabel('城市').fill('杭州市');await page.getByLabel('区县').fill('西湖区');await page.getByLabel('详细地址').fill('文一路18号')
  await page.getByRole('button',{name:'保存地址'}).click();await expect(page.getByText('浙江省杭州市西湖区文一路18号')).toBeVisible();await page.getByRole('button',{name:'返回'}).click()
  await page.getByRole('button',{name:/浏览足迹/}).click();await expect(page.getByText('原味燕麦片')).toBeVisible();await expect(page.getByText('悦享百货 · 中心店')).toBeVisible();await page.getByRole('button',{name:'返回'}).click()
  await page.getByRole('button',{name:'切换账号',exact:true}).click();await page.getByRole('button',{name:'＋ 添加账号'}).click()
  await page.getByLabel('手机号',{exact:true}).fill('13900139000');await page.getByLabel('密码',{exact:true}).fill('Second!12345');await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.getByRole('heading',{name:'阿新'})).toBeVisible()
  await page.evaluate(()=>{const rows=JSON.parse(sessionStorage.getItem('consumer.accounts.v2')||'[]');rows.find((x:any)=>x.mobile==='13800138000').lastUsedAt=0;sessionStorage.setItem('consumer.accounts.v2',JSON.stringify(rows))})
  await page.reload();await page.getByRole('navigation',{name:'平台导航'}).getByRole('button',{name:'我的',exact:true}).click();await page.getByRole('button',{name:'切换账号',exact:true}).click();await page.getByRole('button',{name:/小邻/}).click()
  await expect(page.getByRole('heading',{name:'验证身份'})).toBeVisible();await page.getByLabel('账号密码').fill('Unified!12345');await page.getByRole('button',{name:'验证并切换'}).click();await expect(page.getByRole('heading',{name:'小邻'})).toBeVisible()
  expect(calls.filter(c=>c.path==='/auth/account/login').length).toBeGreaterThanOrEqual(3)
})
