param([string]$BaseUrl="http://localhost:8080")
$ErrorActionPreference="Stop";$root=Split-Path -Parent $PSScriptRoot;$e=@{};Get-Content "$root\.env"|%{if($_-match'^([^#=]+)=(.*)$'){$e[$matches[1]]=$matches[2]}}
function Api($m,$p,$b=$null,$t=$null,$ok=@(200)){ $h=@{};if(-not $t -and $p -like "/api/consumer/*" -and $p -notlike "*/auth/*" -and $p -notlike "*/catalog/*"){$t=$script:consumerToken};if($t){$h.Authorization="Bearer $t"};$x=@{Method=$m;Uri="$BaseUrl$p";Headers=$h;TimeoutSec=30};if($null-ne$b){$x.ContentType="application/json";$x.Body=$b|ConvertTo-Json -Depth 8};try{$r=Invoke-WebRequest @x}catch{$s=[int]$_.Exception.Response.StatusCode;if($s-notin$ok){throw "$m $p failed: $s"};return $null};$content=if($r.Content-is[byte[]]){[Text.Encoding]::UTF8.GetString($r.Content)}else{[string]$r.Content};if($r.StatusCode-notin$ok){throw "$m $p failed: $($r.StatusCode) $content"};if(-not[string]::IsNullOrWhiteSpace($content)){return $content|ConvertFrom-Json}}
function Eq($a,$b,$m){if("$a"-ne"$b"){throw "$m expected=$b actual=$a"}}
$admin=(Api POST "/api/auth/v1/login" @{username=$e.BOOTSTRAP_ADMIN_USERNAME;password=$e.BOOTSTRAP_ADMIN_PASSWORD}).accessToken;$s=Get-Date -Format "MMddHHmmss";$mobile="139$($s.Substring($s.Length-8))";$pass="M4-Test!2026";$app=Api POST "/api/public/v1/tenant-applications" @{merchantName="M4-$s";contactName="验收";contactMobile=$mobile;planCode="STANDARD";password=$pass} $null @(201);$tenant=Api POST "/api/platform/v1/tenant-applications/$($app.id):approve" $null $admin;$token=(Api POST "/api/auth/v1/login" @{username=$mobile;password=$pass}).accessToken
$store=Api POST "/api/merchant/v1/stores" @{storeCode="M4-$s";storeName="M4门店";address="测试";businessHours="09:00-22:00"} $token;$cat=Api POST "/api/merchant/v1/categories" @{categoryCode="M4-$s";categoryName="测试";sortOrder=1} $token;$spu=Api POST "/api/merchant/v1/products" @{categoryId=$cat.id;spuCode="M4-$s";productName="M4商品"} $token;$spu=Api PUT "/api/merchant/v1/products/$($spu.id)" @{categoryId=$cat.id;productName=$spu.productName;status="ACTIVE";version=$spu.version} $token;$sku=Api POST "/api/merchant/v1/products/$($spu.id)/skus" @{skuCode="M4-$s";skuName="规格";basePriceCents=2000;allowStorePrice=$true} $token;$sku=Api PUT "/api/merchant/v1/skus/$($sku.id)" @{skuName=$sku.skuName;basePriceCents=2000;allowStorePrice=$true;status="ACTIVE";version=$sku.version} $token;Api PUT "/api/merchant/v1/stores/$($store.id)/products/$($sku.id)" @{sellable=$true;storePriceCents=2000} $token|Out-Null;Api POST "/api/merchant/v1/inventory/$($sku.id)/adjust" @{storeId=$store.id;quantityDelta=5;idempotencyKey="M4-$s";reason="验收"} $token|Out-Null
$script:consumerToken=(Api POST "/api/consumer/v1/auth/register" @{tenantId=$tenant.id;mobile="13800000000";memberName="M4会员";password="Consumer-Test!2026"}).accessToken
$member=Api POST "/api/consumer/v1/members" @{tenantId=$tenant.id;mobile="13800000000";memberName="M4会员"};Api POST "/api/merchant/v1/members/$($member.id)/points" @{delta=300;requestId="P-$s"} $token|Out-Null;Api POST "/api/merchant/v1/members/$($member.id)/stored-value" @{delta=500;requestId="V-$s"} $token|Out-Null;$now=Get-Date;$tpl=Api POST "/api/merchant/v1/coupon-templates" @{templateCode="C-$s";templateName="M4券";discountCents=200;minSpendCents=1000;totalQuantity=1;validFrom=$now.AddMinutes(-1).ToString("s");validTo=$now.AddDays(1).ToString("s")} $token;$tpl=Api PUT "/api/merchant/v1/coupon-templates/$($tpl.id)/status" @{status="ACTIVE";version=$tpl.version} $token;$coupon=Api POST "/api/consumer/v1/coupons/$($tpl.id)/claim" @{tenantId=$tenant.id;mobile="13800000000";requestId="C-$s"}
$order=Api POST "/api/consumer/v1/orders" @{tenantId=$tenant.id;storeId=$store.id;customerName="M4会员";customerMobile="13800000000";requestId="O-$s";items=@(@{skuId=$sku.id;quantity=1});benefits=@{couponId=$coupon.id;pointsToUse=100;storedValueToUseCents=300}};Eq $order.payableAmountCents 1400 "benefit quote";$paid=Api POST "/api/consumer/v1/orders/$($order.id)/simulate-payment" @{tenantId=$tenant.id;paymentRequestId="PAY-$s"}
$permissionIds=@(Api GET "/api/merchant/v1/permissions" $null $token|Where-Object{$_.permissionCode-in@("merchant:store:view","merchant:order:verify")}|ForEach-Object id);$role=Api POST "/api/merchant/v1/roles" @{code="M4-VERIFY-$s";name="M4核销员"} $token;Api PUT "/api/merchant/v1/roles/$($role.id)/permissions" @{ids=$permissionIds} $token|Out-Null;$workerName="m4-verify-$s";$worker=Api POST "/api/merchant/v1/users" @{username=$workerName;password="M4-Worker!2026";displayName="M4核销员";mobile=$null;dataScope="STORE_SELF"} $token;Api PUT "/api/merchant/v1/users/$($worker.id)/roles" @{ids=@($role.id)} $token|Out-Null;Api POST "/api/merchant/v1/employees" @{userId=$worker.id;employeeNo="M4-$s";employeeName="M4核销员";primaryStoreId=$store.id;jobTitle="核销员";storeIds=@($store.id)} $token|Out-Null;$workerToken=(Api POST "/api/auth/v1/login" @{username=$workerName;password="M4-Worker!2026"}).accessToken
Api POST "/api/merchant/v1/orders/$($order.id)/verify" @{pickupCode=$paid.pickupCode} $workerToken|Out-Null;Api POST "/api/consumer/v1/orders/$($order.id)/refund-request" @{reason="H5售后验收"}|Out-Null;Api POST "/api/merchant/v1/orders/$($order.id)/refund-request" @{approve=$true;reply="核实后同意退款"} $token|Out-Null;Api POST "/api/merchant/v1/orders/$($order.id)/refund-request" @{approve=$true;reply="重复审核"} $token|Out-Null;$after=Api GET "/api/consumer/v1/members?tenantId=$($tenant.id)&mobile=13800000000";Eq $after.availablePoints 300 "points refund";Eq $after.storedValueCents 500 "stored value refund";$stock=Api GET "/api/merchant/v1/inventory?storeId=$($store.id)" $null $token;Eq $stock[0].actualQuantity 5 "stock refund";[pscustomobject]@{result="PASSED";tenantId=$tenant.id;checks=@("benefit freeze","payment confirm","refund benefit rollback","stock restore")}|ConvertTo-Json
