<script setup lang="ts">
import LoginScreen from '../../../packages/ui/src/LoginScreen.vue'
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {api,auth,login} from '@smart-merchant/api'
import {ElMessage,ElMessageBox} from 'element-plus'
import Trend from './Trend.vue'
import './platform.css'
type Application={id:string;merchantName:string;contactName:string;contactMobile:string;requestedPlanCode:string;status:string}
type Tenant={id:string;tenantCode:string;tenantName:string;status:string;ownerName:string;ownerMobile:string;planCode:string;planName:string}
type Plan={id:string;planCode:string;planName:string;status:string;storeQuota:number|null}
type Summary={activeTenants:number;paidOrders:number;grossRevenueCents:number;netRevenueCents:number;refundCents:number}
const menus=[{id:'overview',name:'平台总览',icon:'◈',caption:'PLATFORM OVERVIEW',description:'从租户增长到交易表现，掌握平台运营全貌。'},{id:'applications',name:'入驻审核',icon:'▤',caption:'ONBOARDING REVIEW',description:'集中处理商户入驻申请，开启新的业务连接。'},{id:'tenants',name:'租户管理',icon:'▦',caption:'TENANT MANAGEMENT',description:'统一维护租户状态、负责人信息与套餐权益。'},{id:'plans',name:'套餐权益',icon:'◇',caption:'PLANS & ENTITLEMENTS',description:'管理可申请套餐与门店额度，支持不同规模的商户。'}]
const signedIn=ref(Boolean(auth.accessToken)),loading=ref(false),saving=ref(false),page=ref('overview'),me=ref<any>(),error=ref(''),chartError=ref(''),updated=ref(''),days=ref(7),analyticsLoading=ref(false)
const applications=ref<Application[]>([]),tenants=ref<Tenant[]>([]),plans=ref<Plan[]>([]),analytics=ref<Summary|null>(null),trend=ref<{label:string;amount:number;orders:number}[]>([])
const credentials=reactive({username:'',password:''}),search=ref(''),statusFilter=ref(''),planFilter=ref(''),pageNo=ref(1),detail=ref<Tenant|null>(null),review=ref<Application|null>(null),planDialog=ref<Tenant|null>(null),nextPlan=ref('')
const current=computed(()=>menus.find(x=>x.id===page.value)!),pending=computed(()=>applications.value.filter(x=>x.status==='PENDING')),active=computed(()=>tenants.value.filter(x=>x.status==='ACTIVE').length)
const can=(code:string)=>me.value?.permissions?.includes(code)
const planName=(code:string)=>plans.value.find(p=>p.planCode===code)?.planName??code
const money=(n:number|undefined)=>n===undefined?'—':'¥'+(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const label=(s:string)=>({ACTIVE:'正常',SUSPENDED:'已停用',PENDING:'待审核',APPROVED:'已通过',REJECTED:'已拒绝'} as Record<string,string>)[s]??s
const tag=(s:string)=>s==='ACTIVE'||s==='APPROVED'?'success':s==='PENDING'?'warning':'info'
const filteredTenants=computed(()=>tenants.value.filter(t=>(!statusFilter.value||t.status===statusFilter.value)&&(!planFilter.value||t.planCode===planFilter.value)&&`${t.tenantName} ${t.tenantCode} ${t.ownerName} ${t.ownerMobile}`.toLowerCase().includes(search.value.trim().toLowerCase())))
const filteredApps=computed(()=>applications.value.filter(t=>(!statusFilter.value||t.status===statusFilter.value)&&`${t.merchantName} ${t.contactName} ${t.contactMobile}`.toLowerCase().includes(search.value.trim().toLowerCase())))
const rows=computed(()=>page.value==='tenants'?filteredTenants.value:filteredApps.value)
const date=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const range=computed(()=>{const end=new Date(),start=new Date();start.setDate(start.getDate()-days.value+1);return{from:date(start),to:date(end)}})
function go(id:string,filter=''){page.value=id;search.value='';planFilter.value='';statusFilter.value=filter;pageNo.value=1}
watch([search,statusFilter,planFilter],()=>pageNo.value=1)
async function signIn(){if(loading.value||!credentials.username.trim()||!credentials.password)return;try{loading.value=true;await login(credentials.username,credentials.password);signedIn.value=true;await reload()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function reload(){if(loading.value&&me.value)return;loading.value=true;error.value='';try{me.value=await api('/api/platform/v1/me');if(!me.value.platform){auth.clear();signedIn.value=false;throw new Error('请使用超级平台管理员账号登录')}const result=await Promise.all([api<Application[]>('/api/platform/v1/tenant-applications'),api<Tenant[]>('/api/platform/v1/tenants'),api<Plan[]>('/api/platform/v1/plans')]);[applications.value,tenants.value,plans.value]=result;updated.value=new Date().toLocaleTimeString('zh-CN',{hour12:false});await loadAnalytics()}catch(e){error.value=(e as Error).message;if(!auth.accessToken)signedIn.value=false}finally{loading.value=false}}
async function loadAnalytics(){if(analyticsLoading.value)return;analyticsLoading.value=true;chartError.value='';analytics.value=null;trend.value=[];try{const {from,to}=range.value;analytics.value=await api(`/api/platform/v1/dashboard/summary?from=${from}&to=${to}`);const count=days.value,step=Math.ceil(count/7);const groups=[];for(let i=0;i<count;i+=step){const a=new Date(from+'T00:00:00'),b=new Date(from+'T00:00:00');a.setDate(a.getDate()+i);b.setDate(b.getDate()+Math.min(i+step-1,count-1));groups.push({from:date(a),to:date(b)})}trend.value=await Promise.all(groups.map(async g=>{const r=await api<Summary>(`/api/platform/v1/dashboard/summary?from=${g.from}&to=${g.to}`);return{label:g.from.slice(5)+(g.from===g.to?'':' ~ '+g.to.slice(5)),amount:r.grossRevenueCents,orders:r.paidOrders}}))}catch(e){chartError.value=(e as Error).message}finally{analyticsLoading.value=false}}
async function chooseRange(value:number){days.value=value;await loadAnalytics()}
async function approve(row:Application){try{await ElMessageBox.confirm(`确认通过「${row.merchantName}」的入驻申请？将开通 ${planName(row.requestedPlanCode)}，商户使用申请手机号及自设密码登录。`,'审核入驻申请',{confirmButtonText:'确认通过',cancelButtonText:'暂不处理'});saving.value=true;await api(`/api/platform/v1/tenant-applications/${row.id}:approve`,{method:'POST'});review.value=null;await reload();ElMessage.success('已通过审核，租户已开通')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function reject(row:Application){try{await ElMessageBox.confirm(`确认拒绝「${row.merchantName}」的入驻申请？拒绝后不会创建租户和登录账号。`,'拒绝入驻申请',{type:'warning',confirmButtonText:'确认拒绝',cancelButtonText:'返回'});saving.value=true;await api(`/api/platform/v1/tenant-applications/${row.id}:reject`,{method:'POST'});review.value=null;await reload();ElMessage.success('已拒绝该入驻申请')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function changeStatus(row:Tenant){const action=row.status==='ACTIVE'?'suspend':'resume';try{await ElMessageBox.confirm(action==='suspend'?`停用「${row.tenantName}」后，该租户将无法正常使用系统。确认停用？`:`确认恢复「${row.tenantName}」的使用权限？`,'变更租户状态',{type:'warning',confirmButtonText:action==='suspend'?'确认停用':'恢复使用',cancelButtonText:'取消'});saving.value=true;await api(`/api/platform/v1/tenants/${row.id}:${action}`,{method:'POST'});detail.value=null;await reload();ElMessage.success('租户状态已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
function openPlan(t:Tenant){planDialog.value=t;nextPlan.value=t.planCode}
async function savePlan(){if(!planDialog.value||nextPlan.value===planDialog.value.planCode)return;try{saving.value=true;await api(`/api/platform/v1/tenants/${planDialog.value.id}/plan`,{method:'PUT',body:JSON.stringify({planCode:nextPlan.value})});planDialog.value=null;detail.value=null;await reload();ElMessage.success('套餐权益已更新')}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
async function changePlanStatus(p:Plan){const active=p.status==='ACTIVE';try{await ElMessageBox.confirm(active?`停用「${p.planName}」后，新商户将无法申请此套餐，已有租户套餐保持不变。`:`重新开放「${p.planName}」供商户申请？`,'套餐申请设置',{confirmButtonText:active?'停用申请':'启用申请',cancelButtonText:'取消'});saving.value=true;await api(`/api/platform/v1/plans/${p.id}:${active?'disable':'enable'}`,{method:'POST'});await reload();ElMessage.success('套餐申请状态已更新')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{saving.value=false}}
function logout(){auth.clear();signedIn.value=false;me.value=null;credentials.password=''}
onMounted(()=>{if(signedIn.value)reload()})
</script>
<template>
 <LoginScreen v-if="!signedIn" kind="platform" v-model:username="credentials.username" v-model:password="credentials.password" :loading="loading" @submit="signIn"/>
 <div v-else class="platform-shell"><aside class="platform-sidebar"><div class="wordmark"><span>S</span><div>超级运营平台<small>PLATFORM CONSOLE</small></div></div><div class="nav-caption">运营工作空间</div><nav><button v-for="m in menus" :key="m.id" :class="{active:page===m.id}" @click="go(m.id)"><i>{{m.icon}}</i>{{m.name}}<b v-if="m.id==='applications'&&pending.length">{{pending.length}}</b></button></nav><div class="sidebar-note"><span>多租户 · 统一运营</span><p>连接商户与服务<br>让平台管理井然有序</p></div><div class="platform-user"><span>管</span><div>超级管理员<small>平台管理权限</small></div><button @click="logout">退出</button></div></aside>
 <section class="platform-main"><header class="platform-topbar"><span>管理工作台 <i>/</i> {{current.name}}</span><div><span class="scope-chip">● 平台管理</span><span class="updated">更新于 {{updated||'—'}}</span><el-button :loading="loading" @click="reload">刷新数据</el-button></div></header><div class="platform-content"><div class="heading"><div><p class="eyebrow">{{current.caption}}</p><h1>{{current.name}}</h1><p>{{current.description}}</p></div><el-button v-if="page==='overview'" type="primary" @click="go('applications','PENDING')">处理入驻申请 <span class="button-count">{{pending.length}}</span></el-button></div>
 <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon/>
 <template v-if="page==='overview'">
 <div class="metric-row"><article class="metric primary"><span>平台租户总数 <i>▦</i></span><strong>{{error?'—':tenants.length}}<small>家</small></strong><p>统一管理品牌租户与服务权益</p></article><article class="metric"><span>正常服务租户 <i class="green">✓</i></span><strong>{{error?'—':active}}<small>家</small></strong><p><em class="green">{{tenants.length?(active/tenants.length*100).toFixed(0):0}}%</em> 当前租户正常使用</p></article><article class="metric"><span>待审核申请 <i class="orange">◷</i></span><strong>{{error?'—':pending.length}}<small>条</small></strong><button @click="go('applications','PENDING')">查看待处理申请 →</button></article><article class="metric"><span>开放申请套餐 <i>◇</i></span><strong>{{error?'—':plans.filter(p=>p.status==='ACTIVE').length}}<small>种</small></strong><p>灵活支持商户业务规模</p></article></div>
 <div class="section-heading"><div><h2>交易数据概览</h2><p>全平台商户交易汇总，非平台服务费收入</p></div><div class="range"><button v-for="n in [7,14,30]" :key="n" :disabled="analyticsLoading" :class="{active:days===n}" @click="chooseRange(n)">近{{n}}天</button></div></div>
 <el-alert v-if="chartError" :title="chartError" type="warning" :closable="false"/>
 <div class="analytics-grid"><article class="panel trend-panel" v-loading="analyticsLoading"><div class="panel-head"><div><h3>商户交易实收趋势</h3><p>{{range.from}} — {{range.to}}</p></div><span class="legend">● 实收金额 / 元</span></div><div class="trade-kpis"><div><span>交易实收</span><b>{{money(analytics?.grossRevenueCents)}}</b></div><div><span>支付订单</span><b>{{analytics?.paidOrders??'—'}}<small> 笔</small></b></div><div><span>交易净收入</span><b>{{money(analytics?.netRevenueCents)}}</b></div><div><span>关联退款</span><b>{{money(analytics?.refundCents)}}</b></div></div><Trend v-if="trend.length" :rows="trend"/><el-empty v-else :description="chartError?'交易数据暂不可用':'正在加载交易数据'"/><p class="chart-note">按支付日期统计实收，净收入扣除关联订单累计退款；活跃交易租户 {{analytics?.activeTenants??'—'}} 家。</p></article>
 <article class="panel"><div class="panel-head"><div><h3>租户套餐分布</h3><p>当前租户使用的套餐结构</p></div><span class="subtle">{{tenants.length}} 家</span></div><div class="distribution"><div class="distribution-total"><strong>{{tenants.length}}</strong><span>平台租户</span></div><div v-for="(p,i) in plans" :key="p.id" class="distribution-item"><div><span><i :style="{background:['#3478f6','#29b8a2','#a389ec'][i%3]}"></i>{{p.planName}}</span><b>{{tenants.filter(t=>t.planCode===p.planCode).length}} <small>家</small></b></div><el-progress :percentage="tenants.length?Math.round(tenants.filter(t=>t.planCode===p.planCode).length/tenants.length*100):0" :show-text="false" :stroke-width="8" :color="['#3478f6','#29b8a2','#a389ec'][i%3]"/></div><el-empty v-if="!plans.length" description="暂无套餐" :image-size="60"/></div><button class="text-action" @click="go('plans')">查看套餐权益 →</button></article></div>
 <div class="bottom-grid"><article class="panel"><div class="panel-head"><div><h3>入驻待办</h3><p>待处理申请，审核通过后开通租户</p></div><button class="text-action" @click="go('applications','PENDING')">查看全部 →</button></div><div v-for="a in pending.slice(0,4)" :key="a.id" class="todo-row"><span class="avatar">{{a.merchantName.slice(0,1)}}</span><div><b>{{a.merchantName}}</b><small>{{a.contactName}} · {{planName(a.requestedPlanCode)}}</small></div><el-tag type="warning" effect="light">待审核</el-tag><el-button link type="primary" @click="review=a">查看申请</el-button></div><el-empty v-if="!pending.length" description="申请已处理完毕，暂无待办" :image-size="75"/></article><article class="panel quick-panel"><h3>运营快捷入口</h3><button @click="go('tenants')"><i>▦</i><div><b>租户档案</b><small>查看负责人、套餐和账号状态</small></div><span>→</span></button><button @click="go('tenants','SUSPENDED')"><i class="orange">Ⅱ</i><div><b>已停用租户</b><small>{{tenants.length-active}} 家租户等待恢复服务</small></div><span>→</span></button><button @click="go('plans')"><i class="green">◇</i><div><b>套餐与门店额度</b><small>管理套餐申请状态与租户权益</small></div><span>→</span></button></article></div>
 </template>
 <template v-else-if="page==='tenants'||page==='applications'"><div class="list-summary"><div><strong>{{page==='tenants'?tenants.length:applications.length}}</strong><span>{{page==='tenants'?'平台租户':'入驻申请'}}</span></div><div><strong class="green">{{page==='tenants'?active:applications.filter(a=>a.status==='APPROVED').length}}</strong><span>{{page==='tenants'?'正常服务':'审核通过'}}</span></div><div><strong class="orange">{{page==='tenants'?tenants.length-active:pending.length}}</strong><span>{{page==='tenants'?'已停用':'待处理'}}</span></div></div><section class="panel list-panel" v-loading="loading"><div class="filter-row"><el-input v-model="search" clearable :placeholder="page==='tenants'?'搜索租户、负责人或手机号':'搜索商户、联系人或手机号'"/><el-select v-model="statusFilter" clearable placeholder="全部状态"><el-option v-for="s in page==='tenants'?['ACTIVE','SUSPENDED']:['PENDING','APPROVED','REJECTED']" :key="s" :label="label(s)" :value="s"/></el-select><el-select v-if="page==='tenants'" v-model="planFilter" clearable placeholder="全部套餐"><el-option v-for="p in plans" :key="p.id" :label="p.planName" :value="p.planCode"/></el-select><span>共 {{rows.length}} 条</span></div>
 <el-table v-if="page==='tenants'" :data="filteredTenants.slice((pageNo-1)*10,pageNo*10)" empty-text="暂无符合条件的租户"><el-table-column label="租户信息" min-width="230"><template #default="{row}"><div class="entity-cell"><span class="avatar">{{row.tenantName.slice(0,1)}}</span><div><b>{{row.tenantName}}</b><small>{{row.tenantCode}}</small></div></div></template></el-table-column><el-table-column label="负责人" min-width="160"><template #default="{row}"><div class="stack"><b>{{row.ownerName||'未填写'}}</b><small>{{row.ownerMobile||'未填写手机号'}}</small></div></template></el-table-column><el-table-column label="套餐权益" min-width="135"><template #default="{row}"><el-tag effect="plain">{{planName(row.planCode)}}</el-tag></template></el-table-column><el-table-column label="服务状态" width="115"><template #default="{row}"><el-tag :type="tag(row.status)" round>{{label(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button link type="primary" @click="detail=row">详情</el-button><el-button link type="primary" @click="openPlan(row)">调整套餐</el-button><el-button link :disabled="saving" :type="row.status==='ACTIVE'?'danger':'success'" @click="changeStatus(row)">{{row.status==='ACTIVE'?'停用':'恢复'}}</el-button></template></el-table-column></el-table>
 <el-table v-else :data="filteredApps.slice((pageNo-1)*10,pageNo*10)" empty-text="暂无符合条件的入驻申请"><el-table-column label="申请商户" min-width="210"><template #default="{row}"><div class="entity-cell"><span class="avatar">{{row.merchantName.slice(0,1)}}</span><b>{{row.merchantName}}</b></div></template></el-table-column><el-table-column prop="contactName" label="联系人" min-width="110"/><el-table-column prop="contactMobile" label="联系手机" min-width="145"/><el-table-column label="申请套餐" min-width="120"><template #default="{row}">{{planName(row.requestedPlanCode)}}</template></el-table-column><el-table-column label="审核状态" width="110"><template #default="{row}"><el-tag :type="tag(row.status)" round>{{label(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="review=row">{{row.status==='PENDING'?'查看并审核':'申请详情'}}</el-button></template></el-table-column></el-table><div class="pagination"><span>每页 10 条记录</span><el-pagination v-model:current-page="pageNo" :page-size="10" :total="rows.length" layout="prev,pager,next"/></div></section></template>
 <template v-else><div class="plans-banner"><div><span>服务权益中心</span><h2>让每一种经营规模，都有合适的选择。</h2><p>套餐控制新商户申请资格与门店额度，已有租户的套餐可单独调整。</p></div><span class="banner-icon">◇</span></div><div class="plan-grid"><article v-for="(p,i) in plans" :key="p.id" class="panel plan-card" :class="{featured:i===1}"><div class="plan-top"><span class="plan-icon">{{i===0?'▦':'◇'}}</span><el-tag :type="p.status==='ACTIVE'?'success':'info'">{{p.status==='ACTIVE'?'开放申请':'暂停申请'}}</el-tag></div><p class="eyebrow">{{p.planCode}}</p><h2>{{p.planName}}</h2><p class="subtle">面向{{p.storeQuota===null?'多店规模化经营':'日常门店经营'}}的商户服务</p><div class="plan-quota"><strong>{{p.storeQuota??'不限'}}</strong><span>{{p.storeQuota===null?'门店数量':'家门店额度'}}</span></div><div class="plan-feature"><span>✓</span> 门店独立经营与数据隔离</div><div class="plan-feature"><span>✓</span> 租户统一管理门店账号</div><div class="plan-feature"><span>✓</span> 当前 {{tenants.filter(t=>t.planCode===p.planCode).length}} 家租户使用</div><el-button :type="p.status==='ACTIVE'?'default':'primary'" :disabled="saving" @click="changePlanStatus(p)">{{p.status==='ACTIVE'?'暂停新申请':'开放新申请'}}</el-button></article></div><el-empty v-if="!plans.length" description="暂无套餐数据"/><p class="footer-note">暂停套餐申请不会变更现有租户的套餐。门店额度按当前套餐配置执行。</p></template>
 <footer class="page-footer">SMART MERCHANT <span>平台运营管理中心 · 统一管理，清晰可控</span></footer></div></section>
 <el-drawer :model-value="!!detail" title="租户档案" size="min(480px,100vw)" @close="detail=null"><template v-if="detail"><div class="detail-hero"><span class="avatar">{{detail.tenantName.slice(0,1)}}</span><h2>{{detail.tenantName}}</h2><el-tag :type="tag(detail.status)">{{label(detail.status)}}</el-tag></div><dl><dt>租户编号</dt><dd>{{detail.id}}</dd><dt>租户账号</dt><dd>{{detail.tenantCode}}</dd><dt>负责人</dt><dd>{{detail.ownerName||'未填写'}}</dd><dt>联系手机</dt><dd>{{detail.ownerMobile||'未填写'}}</dd><dt>当前套餐</dt><dd>{{planName(detail.planCode)}}</dd><dt>门店额度</dt><dd>{{plans.find(p=>p.planCode===detail!.planCode)?.storeQuota??'不限'}}</dd></dl><el-button type="primary" @click="openPlan(detail)">调整套餐权益</el-button></template></el-drawer>
 <el-drawer :model-value="!!review" title="入驻申请详情" size="min(480px,100vw)" @close="review=null"><template v-if="review"><div class="detail-hero"><span class="avatar">{{review.merchantName.slice(0,1)}}</span><h2>{{review.merchantName}}</h2><el-tag :type="tag(review.status)">{{label(review.status)}}</el-tag></div><dl><dt>申请编号</dt><dd>{{review.id}}</dd><dt>联系人</dt><dd>{{review.contactName}}</dd><dt>联系手机</dt><dd>{{review.contactMobile}}</dd><dt>申请套餐</dt><dd>{{planName(review.requestedPlanCode)}}</dd></dl><el-alert title="审核通过后，商户使用申请手机号和自设密码登录租户后台。" type="info" :closable="false"/></template><template #footer><el-button @click="review=null">关闭</el-button><el-button v-if="review?.status==='PENDING'" type="danger" plain :loading="saving" @click="reject(review)">拒绝申请</el-button><el-button v-if="review?.status==='PENDING'" type="primary" :loading="saving" @click="approve(review)">审核通过并开通</el-button></template></el-drawer>
 <el-dialog :model-value="!!planDialog" title="调整租户套餐" width="min(460px,94vw)" @close="planDialog=null"><p class="subtle">为 {{planDialog?.tenantName}} 调整服务权益</p><el-form label-position="top"><el-form-item label="选择套餐"><el-select v-model="nextPlan" style="width:100%"><el-option v-for="p in plans.filter(p=>p.status==='ACTIVE')" :key="p.id" :label="p.planName+' · 门店额度 '+(p.storeQuota??'不限')" :value="p.planCode"/></el-select></el-form-item></el-form><el-alert title="保存后将更新该租户的套餐权益，门店额度由所选套餐决定。" type="info" :closable="false"/><template #footer><el-button @click="planDialog=null">取消</el-button><el-button type="primary" :disabled="!nextPlan||nextPlan===planDialog?.planCode" :loading="saving" @click="savePlan">确认调整</el-button></template></el-dialog>
 </div>
</template>
