package com.smartmerchant.saas.iam.interfaces;
import com.smartmerchant.saas.iam.application.IamManagementService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController public class IamController {private final IamManagementService service;private final String internalKey;public IamController(IamManagementService s,@Value("${saas.security.internal-signing-key}")String internalKey){service=s;this.internalKey=internalKey;}
 @GetMapping("/api/platform/v1/me") public Object platformMe(){return service.platformMe();}
 @GetMapping("/api/merchant/v1/me") public Object me(){return service.me();}
 @GetMapping("/api/merchant/v1/users") @PreAuthorize("hasAuthority('iam:user:manage')") public Object users(){return service.users();}
 @PostMapping("/api/merchant/v1/users") @PreAuthorize("hasAuthority('iam:user:manage')") public Object createUser(@Valid @RequestBody UserRequest r){return service.createUser(r.username(),r.password(),r.displayName(),r.mobile(),r.dataScope());}
 @GetMapping("/api/merchant/v1/roles") @PreAuthorize("hasAuthority('iam:role:manage')") public Object roles(){return service.roles();}
 @PostMapping("/api/merchant/v1/roles") @PreAuthorize("hasAuthority('iam:role:manage')") public Object createRole(@Valid @RequestBody RoleRequest r){return service.createRole(r.code(),r.name());}
 @GetMapping("/api/merchant/v1/permissions") @PreAuthorize("hasAuthority('iam:role:manage')") public Object permissions(){return service.permissions();}
 @GetMapping("/api/merchant/v1/users/{id}/roles") @PreAuthorize("hasAuthority('iam:role:manage')") public Object userRoles(@PathVariable long id){return service.userRoleIds(id);}
 @GetMapping("/api/merchant/v1/roles/{id}/permissions") @PreAuthorize("hasAuthority('iam:role:manage')") public Object rolePermissions(@PathVariable long id){return service.rolePermissionIds(id);}
 @PutMapping("/api/merchant/v1/users/{id}/roles") @PreAuthorize("hasAuthority('iam:role:manage')") public void assignRoles(@PathVariable long id,@RequestBody IdsRequest r){service.assignRoles(id,r.ids());}
 @PutMapping("/api/merchant/v1/roles/{id}/permissions") @PreAuthorize("hasAuthority('iam:role:manage')") public void assignPermissions(@PathVariable long id,@RequestBody IdsRequest r){service.assignPermissions(id,r.ids());}
 @PostMapping("/api/platform/v1/tenants/{tenantId}/owner") @PreAuthorize("hasAuthority('iam:tenant:provision')") public Object provision(@PathVariable long tenantId,@Valid @RequestBody OwnerRequest r){return service.provisionOwner(tenantId,r.username(),r.password(),r.displayName(),r.mobile());}
 @PostMapping("/internal/v1/tenants/{tenantId}/owner") public Object provisionInternal(@PathVariable long tenantId,@RequestHeader("X-Internal-Key")String key,@Valid @RequestBody InternalOwnerRequest r){if(!internalKey.equals(key))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.FORBIDDEN);return service.provisionOwnerHash(tenantId,r.username(),r.passwordHash(),r.displayName(),r.mobile());}
 @GetMapping("/internal/v1/usernames/{username}/availability") public Map<String,Boolean> usernameAvailability(@PathVariable String username,@RequestHeader("X-Internal-Key")String key){requireInternal(key);return Map.of("available",service.usernameAvailable(username));}
 @PostMapping("/internal/v1/store-accounts") public Object provisionStoreAccount(@RequestHeader("X-Internal-Key")String key,@Valid @RequestBody StoreAccountRequest r){requireInternal(key);var u=service.provisionStoreAccount(r.tenantId(),r.username(),r.password(),r.displayName(),r.permissions());return new StoreAccountResponse(u.getId(),u.getUsername(),u.getDisplayName());}
 @PutMapping("/internal/v1/store-accounts/{userId}/password") public void resetStorePassword(@RequestHeader("X-Internal-Key")String key,@PathVariable long userId,@Valid @RequestBody StorePasswordRequest r){requireInternal(key);service.resetStorePassword(r.tenantId(),userId,r.password());}

 @PostMapping("/internal/v1/store-accounts/access-query") public Object storeAccess(@RequestHeader("X-Internal-Key")String key,@Valid @RequestBody StoreAccessQuery r){requireInternal(key);return service.storeAccessAccounts(r.tenantId(),r.userIds());}
 @PutMapping("/internal/v1/store-accounts/{userId}/permissions") public void storePermissions(@RequestHeader("X-Internal-Key")String key,@PathVariable long userId,@Valid @RequestBody StorePermissionsRequest r){requireInternal(key);service.updateStorePermissions(r.tenantId(),userId,r.permissions());}
 public record StoreAccessQuery(@Positive long tenantId,@NotNull @Size(max=500) List<Long> userIds){}
 public record StorePermissionsRequest(@Positive long tenantId,@NotNull List<String> permissions){}
 @PutMapping("/internal/v1/store-accounts/{userId}") public Object editStore(@RequestHeader("X-Internal-Key")String key,@PathVariable long userId,@Valid @RequestBody StoreEdit r){requireInternal(key);var u=service.editStoreAccount(r.tenantId(),userId,r.username(),r.displayName(),r.password(),r.operatorId());return new StoreAccountResponse(u.getId(),u.getUsername(),u.getDisplayName());}
 @PostMapping("/internal/v1/store-accounts/{userId}/reveal") public Object revealStore(@RequestHeader("X-Internal-Key")String key,@PathVariable long userId,@Valid @RequestBody StoreReveal r){requireInternal(key);return org.springframework.http.ResponseEntity.ok().cacheControl(org.springframework.http.CacheControl.noStore()).body(service.revealStorePassword(r.tenantId(),userId,r.operatorId()));}
 public record StoreEdit(@Positive long tenantId,@NotBlank @Size(max=128) String username,@NotBlank @Size(max=128) String displayName,@Size(min=8,max=64) String password,@Positive long operatorId){}
 public record StoreReveal(@Positive long tenantId,@Positive long operatorId){}
 private void requireInternal(String key){if(!internalKey.equals(key))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.FORBIDDEN);}
 public record UserRequest(@NotBlank String username,@Size(min=8)String password,@NotBlank String displayName,String mobile,@Pattern(regexp="TENANT_ALL|STORE_SET|STORE_SELF|OWNER_SELF")String dataScope){} public record OwnerRequest(@NotBlank String username,@Size(min=8)String password,@NotBlank String displayName,String mobile){} public record InternalOwnerRequest(@NotBlank String username,@NotBlank String passwordHash,@NotBlank String displayName,String mobile){} public record StoreAccountRequest(@Positive long tenantId,@NotBlank String username,@NotBlank @Size(min=8)String password,@NotBlank String displayName,List<String> permissions){} public record StoreAccountResponse(long id,String username,String displayName){} public record StorePasswordRequest(@Positive long tenantId,@NotBlank @Size(min=8,max=64)String password){} public record RoleRequest(@NotBlank String code,@NotBlank String name){} public record IdsRequest(List<Long> ids){public IdsRequest{ids=ids==null?List.of():List.copyOf(ids);}}
}

