<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import {api} from '@smart-merchant/api'
import {ElMessage,ElMessageBox} from 'element-plus'
import {type Store,type Order,money,dateText} from '../model'
type Transfer={id:number;transferNo:string;sourceStoreId:number;targetStoreId:number;sourceStoreName:string;targetStoreName:string;status:string;deliveryMode:string;recipientName:string;recipientPhone:string;deliveryAddress:string;orderId:number|null;orderNo:string;orderPaidAmountCents:number;orderSyncPending:boolean;createdAt:string;remark:string;items?:{skuId:number;skuName:string;skuCode:string;productName:string;quantity:number}[]}
type Shared={storeId:number;storeName:string;address:string;skuId:number;skuCode:string;skuName:string;productName:string;availableQuantity:number}
const props=defineProps<{store:Store;transfers:any[];canManage:boolean;canOrders:boolean}>()
const emit=defineEmits<{changed:[]}>()
const busy=ref(false),stockBusy=ref(false),visible=ref(false),detail=ref<Transfer|null>(null),query=ref(''),shared=ref<Shared[]>([]),error=ref(''),direction=ref(''),orders=ref<Order[]>([]),ordersBusy=ref(false)
const productQuery=ref(''),productSearch=ref(''),orderQuery=ref(''),orderSearch=ref(''),ordersError=ref('')
const form=reactive({sourceStoreId:0,deliveryMode:'STORE',recipientName:'',recipientPhone:'',deliveryAddress:'',remark:'',orderId:undefined as number|undefined,transferNo:'',items:[] as {skuId:number;quantity:number}[]})
const labels:Record<string,string>={REQUESTED:'待供货店确认',DRAFT:'待总部审批',APPROVED:'待出库',IN_TRANSIT:'待收货',COMPLETED:'已完成',CANCELLED:'已取消'}
const modes:Record<string,string>={STORE:'调入申请门店',OTHER:'其它地址（需入库）',CUSTOMER:'直寄客户（不入库）'}
const rows=computed(()=>props.transfers.filter(t=>!direction.value||(direction.value==='supply'?t.sourceStoreId===props.store.id:t.targetStoreId===props.store.id)))
const pendingSupply=computed(()=>props.transfers.filter(t=>t.sourceStoreId===props.store.id&&['REQUESTED','APPROVED'].includes(t.status)).length)
const pendingReceive=computed(()=>props.transfers.filter(t=>t.targetStoreId===props.store.id&&t.status==='IN_TRANSIT').length)
const suppliers=computed(()=>[...new Map(allStock.value.map(s=>[s.storeId,{id:s.storeId,name:s.storeName}])).values()])
const allStock=ref<Shared[]>([])
const sourceStock=computed(()=>allStock.value.filter(s=>s.storeId===form.sourceStoreId))
const eligibleOrders=computed(()=>orders.value.filter(o=>o.storeId===props.store.id&&o.status==='PICKUP_READY'&&!o.directTransferId))
const searchedOrders=computed(()=>eligibleOrders.value.filter(o=>`${o.orderNo} ${o.customerName} ${o.customerMobile} ${o.items.map(i=>`${i.productName} ${i.skuName} ${i.skuCode}`).join(' ')}`.toLowerCase().includes(orderSearch.value.toLowerCase())))
const searchedStock=computed(()=>sourceStock.value.filter(s=>`${s.productName} ${s.skuName} ${s.skuCode}`.toLowerCase().includes(productSearch.value.toLowerCase())))
const selectedOrder=computed(()=>eligibleOrders.value.find(o=>o.id===form.orderId))
const lineStock=(id:number)=>sourceStock.value.find(s=>s.skuId===id)
const canSubmit=computed(()=>form.sourceStoreId>0&&form.items.length>0&&form.items.every(l=>Number.isSafeInteger(l.quantity)&&l.quantity>0&&(lineStock(l.skuId)?.availableQuantity??0)>=l.quantity)&&new Set(form.items.map(l=>l.skuId)).size===form.items.length)
let request=0
async function loadStock(){const id=++request;stockBusy.value=true;error.value='';try{const result=await api<Shared[]>(`/api/merchant/v1/transfers/shared-stock?storeId=${props.store.id}&query=${encodeURIComponent(query.value.trim())}`);if(id===request){shared.value=result;if(!query.value.trim())allStock.value=result}}catch(e){if(id===request){shared.value=[];error.value=(e as Error).message}}finally{if(id===request)stockBusy.value=false}}
async function loadOrders(){ordersBusy.value=true;ordersError.value='';try{orders.value=await api<Order[]>('/api/merchant/v1/orders')}catch(e){ordersError.value=(e as Error).message;orders.value=[]}finally{ordersBusy.value=false}}
async function open(){Object.assign(form,{sourceStoreId:0,deliveryMode:'STORE',recipientName:'',recipientPhone:'',deliveryAddress:'',remark:'',orderId:undefined,transferNo:`DB-${crypto.randomUUID()}`,items:[]});query.value='';productQuery.value='';productSearch.value='';orderQuery.value='';orderSearch.value='';shared.value=[];allStock.value=[];visible.value=true;await loadStock()}
watch(()=>form.sourceStoreId,()=>{if(form.deliveryMode!=='CUSTOMER')form.items=[]})
watch(()=>form.deliveryMode,async mode=>{form.items=[];form.orderId=undefined;if(mode==='CUSTOMER'){query.value='';await Promise.all([loadOrders(),loadStock()])}})
watch(selectedOrder,o=>{if(form.deliveryMode==='CUSTOMER'){form.items=o?.items.map(i=>({skuId:i.skuId,quantity:i.quantity}))??[];form.recipientName=o?.customerName??'';form.recipientPhone=o?.customerMobile??''}})
function add(row:Shared){const existing=form.items.find(l=>l.skuId===row.skuId);if(!existing)form.items.push({skuId:row.skuId,quantity:1})}
async function submit(){
 if(!canSubmit.value){ElMessage.warning('请选择供货店和商品，并检查可用库存与数量');return}
 if(form.deliveryMode==='STORE'&&!props.store.address?.trim()){ElMessage.warning('本店未设置地址，请选择其它地址并填写');return}
 if(form.deliveryMode!=='STORE'&&(!form.recipientName.trim()||!form.recipientPhone.trim()||form.deliveryAddress.trim().length<5)){ElMessage.warning('请填写收件人、电话和详细地址（至少 5 个字）');return}
 if(form.deliveryMode==='CUSTOMER'&&!selectedOrder.value){ElMessage.warning('请选择本店已支付待履约的销售订单');return}
 try{busy.value=true;await api('/api/merchant/v1/transfers/requests',{method:'POST',body:JSON.stringify({...form,targetStoreId:props.store.id,orderId:form.deliveryMode==='CUSTOMER'?form.orderId:null})});visible.value=false;emit('changed');ElMessage.success('申请已发送至供货门店，等待确认出库')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=false}
}
async function show(row:Transfer){try{detail.value=await api(`/api/merchant/v1/transfers/${row.id}`)}catch(e){ElMessage.error((e as Error).message)}}
async function act(row:Transfer,action:'ship'|'receive'|'cancel'){
 const message=action==='ship'?(row.deliveryMode==='CUSTOMER'?'确认按此地址直寄客户？将扣减本店库存、撤回申请店原订单扣减，并完成原订单，收入归申请店。':'确认供货并出库？将立即扣减本店实际及可用库存。'):action==='receive'?'确认商品已验收？将增加申请门店库存。':'确认取消或拒绝此申请？尚未出库的库存不会变化。'
 try{await ElMessageBox.confirm(message,'调拨确认',{confirmButtonText:'确认',cancelButtonText:'返回'});busy.value=true;await api(`/api/merchant/v1/transfers/${row.id}/${action}`,{method:'POST'});detail.value=null;emit('changed');ElMessage.success('调拨已处理')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}finally{busy.value=false}
}
</script>
<template>
 <div class="page-heading"><div><div class="eyebrow">SHARED INVENTORY</div><h1>同租户调拨收发</h1><p>向有货门店申请调拨；供货店确认扣库存，支持补货入库或关联订单直寄客户。</p></div><el-button v-if="canManage" type="primary" @click="open">查询共享库存 / 申请调拨</el-button></div>
 <section class="metric-grid"><article class="metric"><div>待本店供货确认</div><strong>{{pendingSupply}}</strong><p>打开明细，核对商品及收货地址后出库</p></article><article class="metric"><div>本店待收货</div><strong>{{pendingReceive}}</strong><p>直寄客户无需收货入库</p></article></section>
 <el-alert v-if="!canManage" title="当前账号只有查看权限，请在租户后台为本店启用“调拨收发”，再同步权限。" type="info" :closable="false"/>
 <div class="panel"><div class="filter-bar compact"><el-select v-model="direction" placeholder="全部方向" clearable><el-option label="向本店申请供货" value="supply"/><el-option label="本店申请调货" value="request"/></el-select><el-button @click="emit('changed')">刷新申请</el-button></div>
 <el-table :data="rows" empty-text="暂无调拨申请"><el-table-column prop="transferNo" label="调拨单号" min-width="180" show-overflow-tooltip/><el-table-column label="供货店 → 申请店" min-width="200"><template #default="{row}">{{row.sourceStoreName}} → {{row.targetStoreName}}</template></el-table-column><el-table-column label="配送方式" min-width="145"><template #default="{row}">{{modes[row.deliveryMode]??'门店调拨'}}</template></el-table-column><el-table-column label="状态" min-width="140"><template #default="{row}"><el-tag :type="row.status==='REQUESTED'?'warning':row.status==='COMPLETED'?'success':'info'">{{labels[row.status]??row.status}}</el-tag></template></el-table-column><el-table-column label="申请时间" min-width="175"><template #default="{row}">{{dateText(row.createdAt)}}</template></el-table-column><el-table-column label="操作" min-width="130"><template #default="{row}"><el-button link type="primary" @click="show(row)">明细 / 处理</el-button></template></el-table-column></el-table></div>
 <el-drawer v-model="visible" title="申请同租户库存调拨" size="min(920px,100vw)">
  <el-alert title="申请时检查可用库存；库存以供货店确认出库时为准，不足时不能出库。" type="info" :closable="false"/>
  <div class="filter-bar compact"><el-input v-model="query" placeholder="搜索商品名称、规格或 SKU，比较其它门店库存" clearable @keyup.enter="loadStock"/><el-button :loading="stockBusy" @click="loadStock">查询 / 刷新库存</el-button></div>
  <el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <el-table :data="shared" max-height="230" v-loading="stockBusy" empty-text="未找到其它门店的商品库存"><el-table-column prop="storeName" label="供货门店"/><el-table-column prop="productName" label="商品"/><el-table-column prop="skuName" label="规格"/><el-table-column prop="skuCode" label="SKU"/><el-table-column prop="availableQuantity" label="可用库存"/></el-table>
  <el-form label-position="top" style="margin-top:20px">
   <el-form-item label="申请及收款门店"><el-input :model-value="store.storeName" disabled/></el-form-item>
   <el-form-item label="选择供货门店" required><el-select v-model="form.sourceStoreId" placeholder="请选择同租户有货门店" filterable style="width:100%"><el-option v-for="s in suppliers" :key="s.id" :value="s.id" :label="s.name"/></el-select></el-form-item>
   <el-form-item label="配送方式" required><el-radio-group v-model="form.deliveryMode"><el-radio-button value="STORE">调入本店</el-radio-button><el-radio-button value="OTHER">其它地址，仍入本店库存</el-radio-button><el-radio-button v-if="canOrders" value="CUSTOMER">关联订单，直寄客户</el-radio-button></el-radio-group></el-form-item>
   <template v-if="form.deliveryMode==='CUSTOMER'"><el-form-item label="关联本店已支付待履约订单（整单直寄）" required><div style="display:flex;gap:8px;width:100%;margin-bottom:8px"><el-input v-model="orderQuery" placeholder="输入订单号、客户、手机号或商品搜索" clearable @keyup.enter="orderSearch=orderQuery.trim()" @clear="orderSearch=''"/><el-button @click="orderSearch=orderQuery.trim()">搜索订单</el-button><el-button :loading="ordersBusy" @click="loadOrders">刷新订单</el-button></div><el-select v-model="form.orderId" placeholder="请选择本店已支付待履约订单" filterable clearable :loading="ordersBusy" no-data-text="暂无可关联订单" no-match-text="未找到匹配订单" style="width:100%"><el-option v-for="o in searchedOrders" :key="o.id" :value="o.id" :label="`${o.orderNo} · ${o.customerName} · ${money(o.payableAmountCents)}`"/></el-select></el-form-item><el-alert v-if="ordersError" :title="ordersError" type="error" :closable="false"/><el-alert v-else-if="!ordersBusy&&!eligibleOrders.length" title="本店暂无可关联订单。请先在销售订单中完成收款；已完成、未支付或已关联调拨的订单不可选。选择订单后会自动带出整单商品。" type="info" :closable="false"/><el-alert v-else-if="!searchedOrders.length" title="没有匹配的订单，请更换搜索关键词。" type="info" :closable="false"/><el-alert title="复用原订单收款，不新增收款。供货店出库时自动完成订单；订单金额归申请门店。" type="success" :closable="false"/></template>
   <template v-else><div style="display:flex;gap:8px;margin:12px 0"><el-input v-model="productQuery" placeholder="搜索供货店商品名称、规格或 SKU" clearable @keyup.enter="productSearch=productQuery.trim()" @clear="productSearch=''"/><el-button @click="productSearch=productQuery.trim()">搜索商品</el-button></div><el-table :data="searchedStock" max-height="200" empty-text="选择供货门店后添加商品"><el-table-column prop="productName" label="商品"/><el-table-column prop="skuName" label="规格"/><el-table-column prop="availableQuantity" label="可用"/><el-table-column label="选择"><template #default="{row}"><el-button link type="primary" :disabled="row.availableQuantity<=0||form.items.some(i=>i.skuId===row.skuId)" @click="add(row)">添加</el-button></template></el-table-column></el-table></template>
   <h3>申请商品</h3><el-table :data="form.items" empty-text="请添加商品或选择关联订单"><el-table-column label="商品 / SKU"><template #default="{row}">{{lineStock(row.skuId)?.productName??selectedOrder?.items.find(i=>i.skuId===row.skuId)?.productName}} · {{lineStock(row.skuId)?.skuCode??row.skuId}}</template></el-table-column><el-table-column label="供货店可用" width="110"><template #default="{row}">{{lineStock(row.skuId)?.availableQuantity??0}}</template></el-table-column><el-table-column label="数量" width="180"><template #default="{row}"><el-input-number v-model="row.quantity" :min="1" :precision="0" :max="lineStock(row.skuId)?.availableQuantity??0" :disabled="form.deliveryMode==='CUSTOMER'"/></template></el-table-column><el-table-column v-if="form.deliveryMode!=='CUSTOMER'" label="操作" width="75"><template #default="{row}"><el-button link type="danger" @click="form.items=form.items.filter(i=>i!==row)">移除</el-button></template></el-table-column></el-table>
   <el-form-item v-if="form.deliveryMode==='STORE'" label="本店收货地址"><el-input :model-value="store.address||'本店未设置地址，请选择其它地址'" disabled/></el-form-item>
   <template v-else><el-form-item label="收件人" required><el-input v-model="form.recipientName" maxlength="80"/></el-form-item><el-form-item label="联系电话" required><el-input v-model="form.recipientPhone" maxlength="32"/></el-form-item><el-form-item label="详细收货地址（省市区、街道、门牌）" required><el-input v-model="form.deliveryAddress" type="textarea" :rows="3" maxlength="512"/></el-form-item></template>
   <el-form-item label="备注"><el-input v-model="form.remark" type="textarea" maxlength="512"/></el-form-item>
  </el-form><template #footer><el-button @click="visible=false">返回</el-button><el-button type="primary" :loading="busy" :disabled="!canSubmit||stockBusy" @click="submit">提交调拨申请</el-button></template>
 </el-drawer>
 <el-drawer :model-value="!!detail" title="调拨明细与处理" size="min(720px,100vw)" @close="detail=null"><template v-if="detail">
  <h3>{{detail.sourceStoreName}} → {{detail.targetStoreName}}</h3><p>{{detail.transferNo}} · {{labels[detail.status]}}</p>
  <el-descriptions :column="1" border><el-descriptions-item label="配送方式">{{modes[detail.deliveryMode]}}</el-descriptions-item><el-descriptions-item label="收件人">{{detail.recipientName||detail.targetStoreName}} {{detail.recipientPhone}}</el-descriptions-item><el-descriptions-item label="详细地址">{{detail.deliveryAddress||'历史单据未记录地址，请先与申请店核实'}}</el-descriptions-item><el-descriptions-item v-if="detail.orderId" label="关联订单 / 原现金收款">{{detail.orderNo}} / {{money(detail.orderPaidAmountCents)}}，归属 {{detail.targetStoreName}}</el-descriptions-item><el-descriptions-item label="备注">{{detail.remark||'—'}}</el-descriptions-item></el-descriptions>
  <el-table :data="detail.items"><el-table-column prop="productName" label="商品"/><el-table-column prop="skuCode" label="SKU"/><el-table-column prop="skuName" label="规格"/><el-table-column prop="quantity" label="数量"/></el-table>
  <el-alert v-if="detail.orderSyncPending" title="库存已完成出库，关联订单正在自动同步，请勿重复发货。" type="warning" :closable="false"/><p v-if="detail.deliveryMode==='CUSTOMER'">直寄客户：供货店出库即可完成，不产生申请门店调拨入库；原订单收入仍归申请店。</p>
 </template><template #footer><template v-if="detail&&canManage"><el-button v-if="detail.status==='REQUESTED'" :loading="busy" @click="act(detail,'cancel')">{{detail.sourceStoreId===store.id?'拒绝申请':'取消申请'}}</el-button><el-button v-if="detail.sourceStoreId===store.id&&['REQUESTED','APPROVED'].includes(detail.status)" type="primary" :loading="busy" @click="act(detail,'ship')">确认调拨并出库</el-button><el-button v-if="detail.sourceStoreId===store.id&&detail.deliveryMode==='CUSTOMER'&&detail.status==='COMPLETED'&&detail.orderSyncPending" :loading="busy" @click="act(detail,'ship')">同步关联订单状态</el-button><el-button v-if="detail.targetStoreId===store.id&&detail.status==='IN_TRANSIT'" type="primary" :loading="busy" @click="act(detail,'receive')">确认收货入库</el-button></template></template></el-drawer>
</template>
